/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -g3 -O0  -IC:\Nim\lib -o y:\nimcode\simplepaint\src\nimcache\SimplePaint_simplepaint.o y:\nimcode\simplepaint\src\nimcache\SimplePaint_simplepaint.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
typedef struct Ihandle94209 Ihandle94209;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Any145500 Any145500;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef N_CDECL_PTR(NCSTRING, TY94434) (Ihandle94209* ih, NCSTRING name);
typedef N_CDECL_PTR(Ihandle94209*, TY94385) (Ihandle94209* ih, NCSTRING name);
typedef N_CDECL_PTR(NCSTRING, TY96428) (Ihandle94209* ih, NCSTRING group, NCSTRING key);
typedef N_CDECL_PTR(Ihandle94209*, TY94217) (void);
typedef N_CDECL_PTR(void, TY94415) (Ihandle94209* ih, NCSTRING name, NCSTRING value);
typedef N_CDECL_PTR(void, TY94420) (Ihandle94209* ih, NCSTRING name, NCSTRING value);
typedef N_CDECL_PTR(void, TY94538) (Ihandle94209* ih, NCSTRING name, Ihandle94209* ihnamed);
typedef N_CDECL_PTR(int, TY94393) (Ihandle94209* ih, int x, int y);
typedef N_CDECL_PTR(int, TY94441) (Ihandle94209* ih, NCSTRING name);
typedef N_CDECL_PTR(void, TY96389) (Ihandle94209* ih, NCSTRING group, NCSTRING key, NCSTRING value);
typedef N_CDECL_PTR(void, TY94346) (Ihandle94209* ih);
struct  TGenericSeq  {NI len;
NI reserved;
};
struct  NimStringDesc  {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(int, TY94236) (NCSTRING title, NCSTRING msg, NCSTRING b1, NCSTRING b2, NCSTRING b3);
typedef N_CDECL_PTR(Ihandle94209*, TY94382) (Ihandle94209* ih);
struct  Any145500  {void* value;
void* rawtypeptr;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(Ihandle94209*, TY96353) (NCSTRING action);
typedef N_CDECL_PTR(Ihandle94209*, TY94671) (NCSTRING title);
typedef N_CDECL_PTR(Ihandle94209*, TY94638) (NCSTRING title, NCSTRING action);
typedef N_CDECL_PTR(Ihandle94209*, TY94655) (NCSTRING title, NCSTRING action);
typedef N_CDECL_PTR(int, Icallback94213) (Ihandle94209* arg);
typedef N_CDECL_PTR(Icallback94213, TY94501) (Ihandle94209* ih, NCSTRING name, Icallback94213 fn);
typedef N_CDECL_PTR(Ihandle94209*, TY94648) (Ihandle94209* child, ...);
typedef N_CDECL_PTR(Ihandle94209*, TY94646) (void);
typedef N_CDECL_PTR(Ihandle94209*, TY94642) (NCSTRING title, Ihandle94209* child);
typedef N_CDECL_PTR(Ihandle94209*, TY94596) (Ihandle94209* child, ...);
typedef N_CDECL_PTR(Ihandle94209*, TY94430) (Ihandle94209* ih, NCSTRING str);
typedef N_CDECL_PTR(Ihandle94209*, TY94582) (Ihandle94209* child, ...);
typedef N_CDECL_PTR(Ihandle94209*, TY94666) (Ihandle94209* child);
typedef N_CDECL_PTR(int, TY96474) (Ihandle94209* ih, NCSTRING group, NCSTRING key, int def);
typedef N_CDECL_PTR(int, TY94290) (int* argc, NCSTRING** argv);
typedef N_CDECL_PTR(void, TY96351) (void);
typedef N_CDECL_PTR(void, TY94298) (void);
typedef N_CDECL_PTR(Ihandle94209*, TY96381) (void);
typedef N_CDECL_PTR(int, TY96383) (Ihandle94209* ih);
typedef N_CDECL_PTR(void, TY96510) (Ihandle94209* ih, Ihandle94209* dialog, NCSTRING name);
typedef N_CDECL_PTR(int, TY94300) (void);
typedef N_CDECL_PTR(void, TY94296) (void);
struct  Ihandle94209  {char dummy;
};
typedef N_NIMCALL_PTR(void, TY145488) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY145493) (void* p);

#line 3 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
N_NIMCALL(int, selectfile_208001)(Ihandle94209* parentdlg, int isopen);
#line 303 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 298 "c:\\nim\\lib\\system\\excpt.nim"
N_NOINLINE(void, stackoverflow_22201)(void);
#line 49 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void);
#line 27 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
N_NIMCALL(void, savefile_208017)(Ihandle94209* canvas);
#line 32 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
N_NIMCALL(int, savecheck_208022)(Ihandle94209* ih);
#line 259 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
#line 54 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
N_CDECL(int, itemopenactioncb_208030)(Ihandle94209* itemopen);
#line 62 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
N_NIMCALL(void, checknewfile_208034)(Ihandle94209* dlg);
#line 65 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
N_NIMCALL(void, openfile_208039)(Ihandle94209* ih, NCSTRING filename);
#line 68 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
N_NIMCALL(int, configrecentcb_208045)(Ihandle94209* ih);
#line 244 "c:\\nim\\lib\\pure\\marshal.nim"
N_NIMCALL(NimStringDesc*, HEX24HEX24_208091)(Ihandle94209* x);
#line 136 "c:\\nim\\lib\\core\\typeinfo.nim"
static N_INLINE(Any145500, toany_208101)(Ihandle94209** x);
#line 122 "c:\\nim\\lib\\core\\typeinfo.nim"
static N_INLINE(Any145500, newany_146236)(void* value, TNimType* rawtype);
#line 74 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
N_NIMCALL(Ihandle94209*, createmaindialog_208051)(Ihandle94209* config);
#line 1267 "c:\\nim\\lib\\pure\\os.nim"
N_NIMCALL(NI, nosparamCount)(void);
#line 1272 "c:\\nim\\lib\\pure\\os.nim"
N_NIMCALL(NimStringDesc*, nosparamStr)(NI i);
#line 2579 "c:\\nim\\lib\\system.nim"
static N_INLINE(void, initStackBottomWith)(void* locals);
#line 110 "c:\\nim\\lib\\system\\gc_common.nim"
N_NOINLINE(void, setStackBottom)(void* thestackbottom);NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, Simplepaint_iupInit000)(void);
NIM_EXTERNC N_NOINLINE(void, Simplepaint_iupDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_typeinfoInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_typeinfoDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_intsetsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_intsetsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_marshalInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_marshalDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, simplepaintInit000)(void);
NIM_EXTERNC N_NOINLINE(void, simplepaintDatInit000)(void);
STRING_LITERAL(TMP1102, "check_new_file", 14);
STRING_LITERAL(TMP1103, "open_file", 9);
extern TY94434 Dl_94433;extern TY94385 Dl_94384;extern TY96428 Dl_96427;extern TY94217 Dl_94216;extern TY94415 Dl_94414;extern TY94420 Dl_94419;extern TY94538 Dl_94537;extern TY94393 Dl_94392;extern TY94441 Dl_94440;extern TY96389 Dl_96388;extern TY94346 Dl_94345;extern TFrame* frameptr_19436;
extern TY94236 Dl_94235;extern TY94382 Dl_94381;extern TNimType NTI94211; /* PIhandle */
extern TY96353 Dl_96352;extern TY94671 Dl_94670;extern TY94638 Dl_94637;extern TY94655 Dl_94654;extern TY94501 Dl_94500;extern TY94648 Dl_94647;extern TY94646 Dl_94645;extern TY94642 Dl_94641;extern TY94596 Dl_94595;extern TY94430 Dl_94429;extern TY94582 Dl_94581;extern TY94666 Dl_94665;extern TY96474 Dl_96473;extern TY94290 Dl_94289;extern TY96351 Dl_96350;extern TY94298 Dl_94297;Ihandle94209* config_208122;
extern TY96381 Dl_96380;extern TY96383 Dl_96382;Ihandle94209* dlg_208123;
extern TY96510 Dl_96509;extern TY94300 Dl_94299;extern TY94296 Dl_94295;

#line 303 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
	LOC1 = 0;
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
	{
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);	}
	goto LA2;
	LA4: ;
	{
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
#line 305 "c:\\nim\\lib\\system\\excpt.nim"
	(*s).prev = frameptr_19436;
#line 306 "c:\\nim\\lib\\system\\excpt.nim"
	frameptr_19436 = s;
#line 307 "c:\\nim\\lib\\system\\excpt.nim"
	{
#line 307 "c:\\nim\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;

#line 307 "c:\\nim\\lib\\system\\excpt.nim"
		stackoverflow_22201();
	}
	LA9: ;
}


#line 49 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 50 "c:\\nim\\lib\\system\\excpt.nim"
	frameptr_19436 = (*frameptr_19436).prev;}


#line 3 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
N_NIMCALL(int, selectfile_208001)(Ihandle94209* parentdlg, int isopen) {
	int result;
	Ihandle94209* config;
	NCSTRING LOC1;	Ihandle94209* canvas;
	NCSTRING dir;
	Ihandle94209* filedlg;
	int LOC8;	nimfr("select_file", "simplepaint.nim")
{	result = 0;
#line 4 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(4, "simplepaint.nim");
#line 4 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	LOC1 = 0;	LOC1 = Dl_94433(parentdlg, "CONFIG");	config = ((Ihandle94209*) (LOC1));
#line 5 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(5, "simplepaint.nim");	canvas = Dl_94384(parentdlg, "CANVAS");
#line 6 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(6, "simplepaint.nim");	dir = Dl_96427(config, "MainWindow", "LastDirectory");
#line 7 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(7, "simplepaint.nim");	filedlg = Dl_94216();
#line 8 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(8, "simplepaint.nim");	{
#line 8 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		if (!(isopen == ((NI32) 1))) goto LA4;

#line 9 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(9, "simplepaint.nim");		Dl_94414(filedlg, "DIALOGTYPE", "OPEN");
	}
	goto LA2;
	LA4: ;
	{		NCSTRING LOC7;
#line 11 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(11, "simplepaint.nim");		Dl_94414(filedlg, "DIALOGTYPE", "SAVE");

#line 12 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(12, "simplepaint.nim");
#line 12 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		LOC7 = 0;		LOC7 = Dl_94433(canvas, "FILENAME");		Dl_94419(filedlg, "FILE", LOC7);
	}
	LA2: ;

#line 13 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(13, "simplepaint.nim");	Dl_94414(filedlg, "EXTFILTER", "Image Files|*.bmp;*.jpg;*.png;*.tif;*.tga|All Files|*.*|");

#line 15 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(15, "simplepaint.nim");	Dl_94419(filedlg, "DIRECTORY", dir);

#line 16 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(16, "simplepaint.nim");	Dl_94537(filedlg, "PARENTDIALOG", parentdlg);

#line 17 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(17, "simplepaint.nim");	LOC8 = 0;	LOC8 = Dl_94392(filedlg, ((int) 65530), ((int) 65530));
#line 18 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(18, "simplepaint.nim");	{		int LOC11;		NCSTRING filename;

#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 18 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(18, "simplepaint.nim");		LOC11 = 0;		LOC11 = Dl_94440(filedlg, "STATUS");		if (!!((LOC11 == ((NI32) -1)))) goto LA12;

#line 19 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(19, "simplepaint.nim");		filename = Dl_94433(filedlg, "VALUE");
#line 22 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(22, "simplepaint.nim");		dir = Dl_94433(filedlg, "DIRECTORY");
#line 23 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(23, "simplepaint.nim");		Dl_96388(config, "MainWindow", "LastDirectory", dir);
	}
	LA12: ;

#line 24 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(24, "simplepaint.nim");	Dl_94345(filedlg);

#line 25 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(25, "simplepaint.nim");
#line 25 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	result = ((int) -2);	goto BeforeRet;
	}BeforeRet: ;
	popFrame();	return result;}


#line 27 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
N_NIMCALL(void, savefile_208017)(Ihandle94209* canvas) {
	NCSTRING filename;
	nimfr("save_file", "simplepaint.nim")

#line 28 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(28, "simplepaint.nim");	filename = Dl_94433(canvas, "FILENAME");	popFrame();}


#line 32 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
N_NIMCALL(int, savecheck_208022)(Ihandle94209* ih) {
	int result;
	Ihandle94209* canvas;
	int LOC1;	NimStringDesc* LOC2;	nimfr("save_check", "simplepaint.nim")
{	result = 0;
#line 33 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(33, "simplepaint.nim");	canvas = Dl_94384(ih, "CANVAS");
#line 35 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(35, "simplepaint.nim");
#line 35 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"

#line 35 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	LOC1 = 0;	LOC1 = Dl_94440(canvas, "DIRTY");	LOC2 = 0;	LOC2 = nimIntToStr(((NI) (LOC1)));	printf("%s\015\012", LOC2? (LOC2)->data:"nil");	fflush(stdout);
#line 36 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(36, "simplepaint.nim");	{		int LOC5;		int LOC8;
#line 36 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"

#line 36 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		LOC5 = 0;		LOC5 = Dl_94440(canvas, "DIRTY");		if (!(LOC5 == ((NI32) 1))) goto LA6;

#line 37 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(37, "simplepaint.nim");
#line 37 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		LOC8 = 0;		LOC8 = Dl_94235("Warning", "File not saved! Save it now?", "Yes", "No", "Cancel");		switch (LOC8) {
		case ((NI) 1):
		{
#line 39 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
			nimln(39, "simplepaint.nim");			savefile_208017(canvas);
		}
		break;
		case ((NI) 3):
		{
#line 43 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
			nimln(43, "simplepaint.nim");
#line 43 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
			result = ((int) 0);			goto BeforeRet;
		}
		break;
		default:
		{		}
		break;
		}
	}
	LA6: ;

#line 46 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(46, "simplepaint.nim");
#line 46 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	result = ((int) 1);	goto BeforeRet;
	}BeforeRet: ;
	popFrame();	return result;}


#line 54 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
N_CDECL(int, itemopenactioncb_208030)(Ihandle94209* itemopen) {
	int result;
	Ihandle94209* LOC6;	nimfr("item_open_action_cb", "simplepaint.nim")
{	result = 0;
#line 55 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(55, "simplepaint.nim");	{		int LOC3;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 55 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(55, "simplepaint.nim");		LOC3 = 0;		LOC3 = savecheck_208022(itemopen);		if (!!((LOC3 == ((NI32) 1)))) goto LA4;

#line 55 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"

#line 55 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		result = ((int) -2);		goto BeforeRet;
	}
	LA4: ;

#line 56 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(56, "simplepaint.nim");
#line 56 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"

#line 56 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	LOC6 = 0;	LOC6 = Dl_94381(itemopen);	result = selectfile_208001(LOC6, ((int) 1));	goto BeforeRet;
	}BeforeRet: ;
	popFrame();	return result;}


#line 62 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
N_NIMCALL(void, checknewfile_208034)(Ihandle94209* dlg) {
	nimfr("check_new_file", "simplepaint.nim")

#line 63 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(63, "simplepaint.nim");	printf("%s\015\012", ((NimStringDesc*) &TMP1102)? (((NimStringDesc*) &TMP1102))->data:"nil");	fflush(stdout);	popFrame();}


#line 65 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
N_NIMCALL(void, openfile_208039)(Ihandle94209* ih, NCSTRING filename) {
	nimfr("open_file", "simplepaint.nim")

#line 66 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(66, "simplepaint.nim");	printf("%s\015\012", ((NimStringDesc*) &TMP1103)? (((NimStringDesc*) &TMP1103))->data:"nil");	fflush(stdout);	popFrame();}


#line 68 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
N_NIMCALL(int, configrecentcb_208045)(Ihandle94209* ih) {
	int result;
	nimfr("config_recent_cb", "simplepaint.nim")
{	result = 0;
#line 69 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(69, "simplepaint.nim");	{		int LOC3;		NCSTRING filename;

#line 69 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"

#line 69 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		LOC3 = 0;		LOC3 = savecheck_208022(ih);		if (!(LOC3 == ((NI32) 1))) goto LA4;

#line 70 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(70, "simplepaint.nim");		filename = Dl_94433(ih, "TITLE");	}
	LA4: ;

#line 72 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(72, "simplepaint.nim");
#line 72 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	result = ((int) -2);	goto BeforeRet;
	}BeforeRet: ;
	popFrame();	return result;}


#line 122 "c:\\nim\\lib\\core\\typeinfo.nim"
static N_INLINE(Any145500, newany_146236)(void* value, TNimType* rawtype) {
	Any145500 result;
	nimfr("newAny", "typeinfo.nim")
	memset((void*)(&result), 0, sizeof(result));
#line 123 "c:\\nim\\lib\\core\\typeinfo.nim"
	nimln(123, "typeinfo.nim");	result.value = value;
#line 83 "c:\\nim\\lib\\core\\typeinfo.nim"
	nimln(83, "typeinfo.nim");	result.rawtypeptr = ((void*) (rawtype));	popFrame();	return result;}


#line 136 "c:\\nim\\lib\\core\\typeinfo.nim"
static N_INLINE(Any145500, toany_208101)(Ihandle94209** x) {
	Any145500 result;
	nimfr("toAny", "typeinfo.nim")
	memset((void*)(&result), 0, sizeof(result));
#line 137 "c:\\nim\\lib\\core\\typeinfo.nim"
	nimln(137, "typeinfo.nim");
#line 140 "c:\\nim\\lib\\core\\typeinfo.nim"
	nimln(140, "typeinfo.nim");
#line 140 "c:\\nim\\lib\\core\\typeinfo.nim"
	result = newany_146236(((void*) (x)), ((TNimType*) ((&NTI94211))));	popFrame();	return result;}


#line 74 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
N_NIMCALL(Ihandle94209*, createmaindialog_208051)(Ihandle94209* config) {
	Ihandle94209* result;
	Ihandle94209* canvas;
	Ihandle94209* statusbar;
	Ihandle94209* itemnew;
	Ihandle94209* btnnew;
	Ihandle94209* itemopen;
	Icallback94213 LOC1;	Ihandle94209* btnopen;
	Icallback94213 LOC2;	Ihandle94209* itemsave;
	Ihandle94209* btnsave;
	Ihandle94209* itemsaveas;
	Ihandle94209* itemrevert;
	Ihandle94209* itemexit;
	Ihandle94209* itemcopy;
	Ihandle94209* btncopy;
	Ihandle94209* itempaste;
	Ihandle94209* btnpaste;
	Ihandle94209* itembackground;
	Ihandle94209* itemtoolbar;
	Ihandle94209* itemstatusbar;
	Ihandle94209* itemhelp;
	Ihandle94209* itemabout;
	Ihandle94209* recentmenu;
	Ihandle94209* filemenu;
	Ihandle94209* LOC3;	Ihandle94209* LOC4;	Ihandle94209* editmenu;
	Ihandle94209* viewmenu;
	Ihandle94209* LOC5;	Ihandle94209* helpmenu;
	Ihandle94209* submenufile;
	Ihandle94209* submenuedit;
	Ihandle94209* submenuview;
	Ihandle94209* submenuhelp;
	Ihandle94209* menu;
	Ihandle94209* toolbar;
	Ihandle94209* LOC6;	Ihandle94209* LOC7;	Ihandle94209* vbox;
	Ihandle94209* dlg;
	NimStringDesc* LOC18;	nimfr("create_main_dialog", "simplepaint.nim")
{	result = 0;
#line 85 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(85, "simplepaint.nim");	canvas = Dl_96352(NIM_NIL);
#line 86 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(86, "simplepaint.nim");	Dl_94414(canvas, "NAME", "CANVAS");

#line 87 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(87, "simplepaint.nim");	Dl_94414(canvas, "DIRTY", "NO");

#line 88 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(88, "simplepaint.nim");	Dl_94414(canvas, "BUFFER", "DOUBLE");

#line 92 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(92, "simplepaint.nim");	statusbar = Dl_94670("(0, 0) = [0   0   0]");
#line 93 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(93, "simplepaint.nim");	Dl_94414(statusbar, "NAME", "STATUSBAR");

#line 94 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(94, "simplepaint.nim");	Dl_94414(statusbar, "EXPAND", "HORIZONTAL");

#line 95 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(95, "simplepaint.nim");	Dl_94414(statusbar, "PADDING", "10x5");

#line 97 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(97, "simplepaint.nim");	itemnew = Dl_94637("&New\011Ctrl+N", NIM_NIL);
#line 98 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(98, "simplepaint.nim");	Dl_94414(itemnew, "IMAGE", "IUP_FileNew");

#line 100 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(100, "simplepaint.nim");	btnnew = Dl_94654(NIM_NIL, NIM_NIL);
#line 101 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(101, "simplepaint.nim");	Dl_94414(btnnew, "IMAGE", "IUP_FileNew");

#line 102 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(102, "simplepaint.nim");	Dl_94414(btnnew, "FLAT", "Yes");

#line 104 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(104, "simplepaint.nim");	Dl_94414(btnnew, "TIP", "New (Ctrl+N)");

#line 105 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(105, "simplepaint.nim");	Dl_94414(btnnew, "CANFOCUS", "No");

#line 107 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(107, "simplepaint.nim");	itemopen = Dl_94637("&Open...\011Ctrl+O", NIM_NIL);
#line 108 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(108, "simplepaint.nim");	Dl_94414(itemopen, "IMAGE", "IUP_FileOpen");

#line 109 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(109, "simplepaint.nim");
#line 109 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	LOC1 = 0;	LOC1 = Dl_94500(itemopen, "ACTION", itemopenactioncb_208030);
#line 110 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(110, "simplepaint.nim");	btnopen = Dl_94654(NIM_NIL, NIM_NIL);
#line 111 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(111, "simplepaint.nim");	Dl_94414(btnopen, "IMAGE", "IUP_FileOpen");

#line 112 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(112, "simplepaint.nim");	Dl_94414(btnopen, "FLAT", "Yes");

#line 113 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(113, "simplepaint.nim");	LOC2 = 0;	LOC2 = Dl_94500(btnopen, "ACTION", itemopenactioncb_208030);
#line 114 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(114, "simplepaint.nim");	Dl_94414(btnopen, "TIP", "Open (Ctrl+O)");

#line 115 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(115, "simplepaint.nim");	Dl_94414(btnopen, "CANFOCUS", "No");

#line 117 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(117, "simplepaint.nim");	itemsave = Dl_94637("&Save\011Ctrl+S", NIM_NIL);
#line 118 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(118, "simplepaint.nim");	Dl_94414(itemsave, "NAME", "ITEM_SAVE");

#line 119 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(119, "simplepaint.nim");	Dl_94414(itemsave, "IMAGE", "IUP_FileSave");

#line 121 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(121, "simplepaint.nim");	btnsave = Dl_94654(NIM_NIL, NIM_NIL);
#line 122 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(122, "simplepaint.nim");	Dl_94414(btnsave, "IMAGE", "IUP_FileSave");

#line 123 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(123, "simplepaint.nim");	Dl_94414(btnsave, "FLAT", "Yes");

#line 125 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(125, "simplepaint.nim");	Dl_94414(btnsave, "TIP", "Save (Ctrl+S)");

#line 126 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(126, "simplepaint.nim");	Dl_94414(btnsave, "CANFOCUS", "No");

#line 128 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(128, "simplepaint.nim");	itemsaveas = Dl_94637("Save &As...", NIM_NIL);
#line 129 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(129, "simplepaint.nim");	Dl_94414(itemsaveas, "NAME", "ITEM_SAVEAS");

#line 132 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(132, "simplepaint.nim");	itemrevert = Dl_94637("&Revert", NIM_NIL);
#line 133 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(133, "simplepaint.nim");	Dl_94414(itemrevert, "NAME", "ITEM_REVERT");

#line 136 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(136, "simplepaint.nim");	itemexit = Dl_94637("E&xit", NIM_NIL);
#line 139 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(139, "simplepaint.nim");	itemcopy = Dl_94637("&Copy\011Ctrl+C", NIM_NIL);
#line 140 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(140, "simplepaint.nim");	Dl_94414(itemcopy, "NAME", "ITEM_COPY");

#line 141 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(141, "simplepaint.nim");	Dl_94414(itemcopy, "IMAGE", "IUP_EditCopy");

#line 143 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(143, "simplepaint.nim");	btncopy = Dl_94654(NIM_NIL, NIM_NIL);
#line 144 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(144, "simplepaint.nim");	Dl_94414(btncopy, "IMAGE", "IUP_EditCopy");

#line 145 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(145, "simplepaint.nim");	Dl_94414(btncopy, "FLAT", "Yes");

#line 147 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(147, "simplepaint.nim");	Dl_94414(btncopy, "TIP", "Copy (Ctrl+C)");

#line 148 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(148, "simplepaint.nim");	Dl_94414(btncopy, "CANFOCUS", "No");

#line 150 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(150, "simplepaint.nim");	itempaste = Dl_94637("&Paste\011Ctrl+V", NIM_NIL);
#line 151 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(151, "simplepaint.nim");	Dl_94414(itempaste, "NAME", "ITEM_PASTE");

#line 152 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(152, "simplepaint.nim");	Dl_94414(itempaste, "IMAGE", "IUP_EditPaste");

#line 154 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(154, "simplepaint.nim");	btnpaste = Dl_94654(NIM_NIL, NIM_NIL);
#line 155 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(155, "simplepaint.nim");	Dl_94414(btnpaste, "IMAGE", "IUP_EditPaste");

#line 156 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(156, "simplepaint.nim");	Dl_94414(btnpaste, "FLAT", "Yes");

#line 158 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(158, "simplepaint.nim");	Dl_94414(btnpaste, "TIP", "Paste (Ctrl+V)");

#line 159 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(159, "simplepaint.nim");	Dl_94414(btnpaste, "CANFOCUS", "No");

#line 161 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(161, "simplepaint.nim");	itembackground = Dl_94637("&Background...", NIM_NIL);
#line 164 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(164, "simplepaint.nim");	itemtoolbar = Dl_94637("&Toobar", NIM_NIL);
#line 166 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(166, "simplepaint.nim");	Dl_94414(itemtoolbar, "VALUE", "ON");

#line 168 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(168, "simplepaint.nim");	itemstatusbar = Dl_94637("&Statusbar", NIM_NIL);
#line 170 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(170, "simplepaint.nim");	Dl_94414(itemstatusbar, "VALUE", "ON");

#line 172 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(172, "simplepaint.nim");	itemhelp = Dl_94637("&Help...", NIM_NIL);
#line 175 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(175, "simplepaint.nim");	itemabout = Dl_94637("&About...", NIM_NIL);
#line 178 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(178, "simplepaint.nim");	recentmenu = Dl_94647(NIM_NIL);
#line 180 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(180, "simplepaint.nim");
#line 186 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(186, "simplepaint.nim");	LOC3 = 0;	LOC3 = Dl_94645();
#line 187 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(187, "simplepaint.nim");	LOC4 = 0;	LOC4 = Dl_94641("Recent &Files", recentmenu);	filemenu = Dl_94647(itemnew, itemopen, itemsave, itemsaveas, itemrevert, LOC3, LOC4, itemexit, NIM_NIL);
#line 190 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(190, "simplepaint.nim");	editmenu = Dl_94647(itemcopy, itempaste, NIM_NIL);
#line 194 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(194, "simplepaint.nim");
#line 196 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(196, "simplepaint.nim");	LOC5 = 0;	LOC5 = Dl_94645();	viewmenu = Dl_94647(itembackground, LOC5, itemtoolbar, itemstatusbar, NIM_NIL);
#line 200 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(200, "simplepaint.nim");	helpmenu = Dl_94647(itemhelp, itemabout, NIM_NIL);
#line 208 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(208, "simplepaint.nim");	submenufile = Dl_94641("&File", filemenu);
#line 209 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(209, "simplepaint.nim");	submenuedit = Dl_94641("&Edit", editmenu);
#line 210 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(210, "simplepaint.nim");	submenuview = Dl_94641("&View", viewmenu);
#line 211 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(211, "simplepaint.nim");	submenuhelp = Dl_94641("&Help", helpmenu);
#line 213 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(213, "simplepaint.nim");	menu = Dl_94647(submenufile, submenuedit, submenuview, submenuhelp, NIM_NIL);
#line 220 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(220, "simplepaint.nim");
#line 224 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(224, "simplepaint.nim");
#line 224 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	LOC6 = 0;	LOC6 = Dl_94670(NIM_NIL);	LOC7 = 0;	LOC7 = Dl_94429(LOC6, "SEPARATOR=VERTICAL");	toolbar = Dl_94595(btnnew, btnopen, btnsave, LOC7, btncopy, btnpaste, NIM_NIL);
#line 228 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(228, "simplepaint.nim");	Dl_94414(toolbar, "MARGIN", "5x5");

#line 229 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(229, "simplepaint.nim");	Dl_94414(toolbar, "GAP", "2");

#line 231 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(231, "simplepaint.nim");	vbox = Dl_94581(toolbar, canvas, statusbar, NIM_NIL);
#line 237 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(237, "simplepaint.nim");	dlg = Dl_94665(vbox);
#line 238 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(238, "simplepaint.nim");	Dl_94537(dlg, "MENU", menu);

#line 239 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(239, "simplepaint.nim");	Dl_94414(dlg, "SIZE", "HALFxHALF");

#line 250 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(250, "simplepaint.nim");	Dl_94537(NIM_NIL, "PARENTDIALOG", dlg);

#line 256 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(256, "simplepaint.nim");	{		int LOC10;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 256 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(256, "simplepaint.nim");		LOC10 = 0;		LOC10 = Dl_96473(config, "MainWindow", "Toolbar", ((int) 1));		if (!!((LOC10 == ((NI32) 1)))) goto LA11;

#line 257 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(257, "simplepaint.nim");		Dl_94414(itemtoolbar, "VALUE", "OFF");

#line 258 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(258, "simplepaint.nim");		Dl_94414(toolbar, "FLOATING", "YES");

#line 259 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(259, "simplepaint.nim");		Dl_94414(toolbar, "VISIBLE", "NO");
	}
	LA11: ;

#line 264 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(264, "simplepaint.nim");	{		int LOC15;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 264 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(264, "simplepaint.nim");		LOC15 = 0;		LOC15 = Dl_96473(config, "MainWindow", "Statusbar", ((int) 1));		if (!!((LOC15 == ((NI32) 1)))) goto LA16;

#line 265 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(265, "simplepaint.nim");		Dl_94414(itemstatusbar, "VALUE", "OFF");

#line 266 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(266, "simplepaint.nim");		Dl_94414(statusbar, "FLOATING", "YES");

#line 267 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(267, "simplepaint.nim");		Dl_94414(statusbar, "VISIBLE", "NO");
	}
	LA16: ;

#line 272 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(272, "simplepaint.nim");
#line 272 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	LOC18 = 0;	LOC18 = HEX24HEX24_208091(config);	Dl_94414(dlg, "CONFIG", LOC18->data);

#line 274 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(274, "simplepaint.nim");
#line 274 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	result = dlg;	goto BeforeRet;
	}BeforeRet: ;
	popFrame();	return result;}


#line 2579 "c:\\nim\\lib\\system.nim"
static N_INLINE(void, initStackBottomWith)(void* locals) {

#line 2583 "c:\\nim\\lib\\system.nim"
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	Simplepaint_iupDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_winleanDatInit000();
	stdlib_timesDatInit000();
	stdlib_osDatInit000();
	stdlib_streamsDatInit000();
	stdlib_typeinfoDatInit000();
	stdlib_etcprivDatInit000();
	stdlib_hashesDatInit000();
	stdlib_lexbaseDatInit000();
	stdlib_unicodeDatInit000();
	stdlib_macrosDatInit000();
	stdlib_jsonDatInit000();
	stdlib_mathDatInit000();
	stdlib_intsetsDatInit000();
	stdlib_tablesDatInit000();
	stdlib_marshalDatInit000();
	simplepaintDatInit000();
	Simplepaint_iupInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	stdlib_winleanInit000();
	stdlib_timesInit000();
	stdlib_osInit000();
	stdlib_streamsInit000();
	stdlib_typeinfoInit000();
	stdlib_etcprivInit000();
	stdlib_hashesInit000();
	stdlib_lexbaseInit000();
	stdlib_unicodeInit000();
	stdlib_macrosInit000();
	stdlib_jsonInit000();
	stdlib_mathInit000();
	stdlib_intsetsInit000();
	stdlib_tablesInit000();
	stdlib_marshalInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	simplepaintInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, simplepaintInit000)(void) {
	int LOC1;	int LOC2;	int LOC9;	nimfr("simplepaint", "simplepaint.nim")

#line 282 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(282, "simplepaint.nim");
#line 282 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	LOC1 = 0;	LOC1 = Dl_94289(NIM_NIL, NIM_NIL);
#line 283 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(283, "simplepaint.nim");	Dl_96350();

#line 284 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(284, "simplepaint.nim");	Dl_94297();

#line 286 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(286, "simplepaint.nim");	config_208122 = Dl_96380();
#line 287 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(287, "simplepaint.nim");	Dl_94414(config_208122, "APP_NAME", "simple_paint");

#line 288 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(288, "simplepaint.nim");
#line 288 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	LOC2 = 0;	LOC2 = Dl_96382(config_208122);
#line 290 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(290, "simplepaint.nim");	dlg_208123 = createmaindialog_208051(config_208122);
#line 293 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(293, "simplepaint.nim");	Dl_96509(config_208122, dlg_208123, "MainWindow");

#line 296 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(296, "simplepaint.nim");	{		NI LOC5;		NimStringDesc* LOC8;
#line 357 "c:\\nim\\lib\\system.nim"
		nimln(357, "system.nim");
#line 296 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		nimln(296, "simplepaint.nim");		LOC5 = 0;		LOC5 = nosparamCount();		if (!(((NI) 0) < LOC5)) goto LA6;

#line 296 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"

#line 296 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
		LOC8 = 0;		LOC8 = nosparamStr(((NI) 1));		openfile_208039(dlg_208123, LOC8->data);
	}
	LA6: ;

#line 303 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(303, "simplepaint.nim");	checknewfile_208034(dlg_208123);

#line 305 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(305, "simplepaint.nim");
#line 305 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	LOC9 = 0;	LOC9 = Dl_94299();
#line 307 "y:\\nimcode\\simplepaint\\src\\simplepaint.nim"
	nimln(307, "simplepaint.nim");	Dl_94295();
	popFrame();}

NIM_EXTERNC N_NOINLINE(void, simplepaintDatInit000)(void) {
}

