/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -g3 -O0  -IC:\Nim\lib -o y:\nimcode\simplepaint\src\nimcache\stdlib_os.o y:\nimcode\simplepaint\src\nimcache\stdlib_os.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct TY15805 TY15805;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47704 Cell47704;
typedef struct Cellseq47720 Cellseq47720;
typedef struct Gcheap50018 Gcheap50018;
typedef struct Gcstack50016 Gcstack50016;
typedef struct Cellset47716 Cellset47716;
typedef struct Pagedesc47712 Pagedesc47712;
typedef struct Memregion29888 Memregion29888;
typedef struct Smallchunk29840 Smallchunk29840;
typedef struct Llchunk29882 Llchunk29882;
typedef struct Bigchunk29842 Bigchunk29842;
typedef struct Intset29814 Intset29814;
typedef struct Trunk29810 Trunk29810;
typedef struct Avlnode29886 Avlnode29886;
typedef struct Gcstat50014 Gcstat50014;
typedef struct Basechunk29838 Basechunk29838;
typedef struct Freecell29830 Freecell29830;
struct  TGenericSeq  {NI len;
NI reserved;
};
struct  NimStringDesc  {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell47704  {NI refcount;
TNimType* typ;
};
struct  Cellseq47720  {NI len;
NI cap;
Cell47704** d;
};
struct  Cellset47716  {NI counter;
NI max;
Pagedesc47712* head;
Pagedesc47712** data;
};
typedef Smallchunk29840* TY29903[512];
typedef Trunk29810* Trunkbuckets29812[256];
struct  Intset29814  {Trunkbuckets29812 data;
};
struct  Memregion29888  {NI minlargeobj;
NI maxlargeobj;
TY29903 freesmallchunks;
Llchunk29882* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29842* freechunkslist;
Intset29814 chunkstarts;
Avlnode29886* root;
Avlnode29886* deleted;
Avlnode29886* last;
Avlnode29886* freeavlnodes;
};
struct  Gcstat50014  {NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap50018  {Gcstack50016* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47720 zct;
Cellseq47720 decstack;
Cellset47716 cycleroots;
Cellseq47720 tempstack;
NI recgclock;
Memregion29888 region;
Gcstat50014 stat;
};
typedef N_STDCALL_PTR(NI16*, TY110434) (void);
struct  Gcstack50016  {Gcstack50016* prev;
Gcstack50016* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY29819[8];
struct  Pagedesc47712  {Pagedesc47712* next;
NI key;
TY29819 bits;
};
struct  Basechunk29838  {NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29840  {  Basechunk29838 Sup;Smallchunk29840* next;
Smallchunk29840* prev;
Freecell29830* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29882  {NI size;
NI acc;
Llchunk29882* next;
};
struct  Bigchunk29842  {  Basechunk29838 Sup;Bigchunk29842* next;
Bigchunk29842* prev;
NI align;
NF data;
};
struct  Trunk29810  {Trunk29810* next;
NI key;
TY29819 bits;
};
typedef Avlnode29886* TY29893[2];
struct  Avlnode29886  {TY29893 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell29830  {Freecell29830* next;
NI zerofield;
};
struct TY15805 {  TGenericSeq Sup;  NimStringDesc* data[SEQ_DECL_SIZE];};
#line 2199 "c:\\nim\\lib\\system.nim"
static N_INLINE(NimStringDesc*, pop_132640)(TY15805** s);
#line 326 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b);
#line 13 "c:\\nim\\lib\\system\\arithm.nim"
N_NOINLINE(void, raiseOverflow)(void);
#line 18 "c:\\nim\\lib\\system\\chcks.nim"
N_NOINLINE(void, raiseIndexError)(void);
#line 90 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
#line 30 "c:\\nim\\lib\\system\\chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
#line 12 "c:\\nim\\lib\\system\\chcks.nim"
N_NOINLINE(void, raiseRangeError)(NI64 val);
#line 221 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
#line 303 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 298 "c:\\nim\\lib\\system\\excpt.nim"
N_NOINLINE(void, stackoverflow_22201)(void);
#line 49 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void);
#line 1033 "c:\\nim\\lib\\pure\\os.nim"
N_NIMCALL(TY15805*, nosparseCmdLine)(NimStringDesc* c);
#line 473 "c:\\nim\\lib\\system\\gc.nim"
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
#line 188 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
#line 319 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b);
#line 338 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, divInt)(NI a, NI b);
#line 17 "c:\\nim\\lib\\system\\arithm.nim"
N_NOINLINE(void, raiseDivByZero)(void);
#line 126 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
#line 346 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, modInt)(NI a, NI b);
#line 213 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
#line 99 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
#line 244 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
#line 129 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(Cell47704*, usrtocell_51640)(void* usr);
#line 208 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, rtladdzct_53201)(Cell47704* c);
#line 120 "c:\\nim\\lib\\system\\gc.nim"
N_NOINLINE(void, addzct_51617)(Cellseq47720* s, Cell47704* c);
#line 159 "c:\\nim\\lib\\system\\widestrs.nim"
N_NIMCALL(NimStringDesc*, HEX24_84072)(NI16* s);
#line 261 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);STRING_LITERAL(TMP1120, "", 0);
NIM_BOOL envcomputed_130401;
TY15805* environment_130403;
extern TFrame* frameptr_19436;
TY15805* ownargv_137402;
extern TNimType NTI15805; /* seq[string] */
extern Gcheap50018 gch_50059;
extern TY110434 Dl_110433;

#line 326 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 327 "c:\\nim\\lib\\system\\arithm.nim"

#line 327 "c:\\nim\\lib\\system\\arithm.nim"
	result = (NI)((NU64)(a) - (NU64)(b));
#line 328 "c:\\nim\\lib\\system\\arithm.nim"
	{		NIM_BOOL LOC3;
#line 328 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = 0;
#line 353 "c:\\nim\\lib\\system.nim"

#line 328 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ a));		if (LOC3) goto LA4;

#line 353 "c:\\nim\\lib\\system.nim"

#line 328 "c:\\nim\\lib\\system\\arithm.nim"

#line 328 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));		LA4: ;
		if (!LOC3) goto LA5;

#line 329 "c:\\nim\\lib\\system\\arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 330 "c:\\nim\\lib\\system\\arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 30 "c:\\nim\\lib\\system\\chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
#line 31 "c:\\nim\\lib\\system\\chcks.nim"
	{		NIM_BOOL LOC3;
#line 31 "c:\\nim\\lib\\system\\chcks.nim"
		LOC3 = 0;
#line 353 "c:\\nim\\lib\\system.nim"
		LOC3 = (a <= i);		if (!(LOC3)) goto LA4;

#line 31 "c:\\nim\\lib\\system\\chcks.nim"
		LOC3 = (i <= b);		LA4: ;
		if (!LOC3) goto LA5;

#line 32 "c:\\nim\\lib\\system\\chcks.nim"

#line 32 "c:\\nim\\lib\\system\\chcks.nim"
		result = i;		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
#line 34 "c:\\nim\\lib\\system\\chcks.nim"
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;}


#line 303 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
	LOC1 = 0;
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
	{
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);	}
	goto LA2;
	LA4: ;
	{
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
#line 305 "c:\\nim\\lib\\system\\excpt.nim"
	(*s).prev = frameptr_19436;
#line 306 "c:\\nim\\lib\\system\\excpt.nim"
	frameptr_19436 = s;
#line 307 "c:\\nim\\lib\\system\\excpt.nim"
	{
#line 307 "c:\\nim\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;

#line 307 "c:\\nim\\lib\\system\\excpt.nim"
		stackoverflow_22201();
	}
	LA9: ;
}


#line 49 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 50 "c:\\nim\\lib\\system\\excpt.nim"
	frameptr_19436 = (*frameptr_19436).prev;}


#line 2199 "c:\\nim\\lib\\system.nim"
static N_INLINE(NimStringDesc*, pop_132640)(TY15805** s) {
	NimStringDesc* result;
	NI L;
	NI TMP604;	nimfr("pop", "system.nim")
	result = 0;
#line 2202 "c:\\nim\\lib\\system.nim"
	nimln(2202, "system.nim");
#line 2202 "c:\\nim\\lib\\system.nim"

#line 2202 "c:\\nim\\lib\\system.nim"
	TMP604 = subInt(((*s) ? (*s)->Sup.len : 0), ((NI) 1));	L = (NI)(TMP604);
#line 2203 "c:\\nim\\lib\\system.nim"
	nimln(2203, "system.nim");	if ((NU)(L) >= (NU)((*s)->Sup.len)) raiseIndexError();	result = copyString((*s)->data[L]);
#line 2204 "c:\\nim\\lib\\system.nim"
	nimln(2204, "system.nim");	(*s) = (TY15805*) setLengthSeq(&((*s))->Sup, sizeof(NimStringDesc*), ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));	popFrame();	return result;}


#line 319 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 320 "c:\\nim\\lib\\system\\arithm.nim"

#line 320 "c:\\nim\\lib\\system\\arithm.nim"
	result = (NI)((NU64)(a) + (NU64)(b));
#line 321 "c:\\nim\\lib\\system\\arithm.nim"
	{		NIM_BOOL LOC3;
#line 321 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = 0;
#line 353 "c:\\nim\\lib\\system.nim"

#line 321 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ a));		if (LOC3) goto LA4;

#line 353 "c:\\nim\\lib\\system.nim"

#line 321 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ b));		LA4: ;
		if (!LOC3) goto LA5;

#line 322 "c:\\nim\\lib\\system\\arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 323 "c:\\nim\\lib\\system\\arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 338 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 339 "c:\\nim\\lib\\system\\arithm.nim"
	{
#line 339 "c:\\nim\\lib\\system\\arithm.nim"
		if (!(b == ((NI) 0))) goto LA3;

#line 340 "c:\\nim\\lib\\system\\arithm.nim"
		raiseDivByZero();
	}
	LA3: ;

#line 341 "c:\\nim\\lib\\system\\arithm.nim"
	{		NIM_BOOL LOC7;
#line 341 "c:\\nim\\lib\\system\\arithm.nim"
		LOC7 = 0;
#line 341 "c:\\nim\\lib\\system\\arithm.nim"
		LOC7 = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));		if (!(LOC7)) goto LA8;

#line 341 "c:\\nim\\lib\\system\\arithm.nim"
		LOC7 = (b == ((NI) -1));		LA8: ;
		if (!LOC7) goto LA9;

#line 342 "c:\\nim\\lib\\system\\arithm.nim"
		raiseOverflow();
	}
	LA9: ;

#line 343 "c:\\nim\\lib\\system\\arithm.nim"

#line 343 "c:\\nim\\lib\\system\\arithm.nim"

#line 343 "c:\\nim\\lib\\system\\arithm.nim"
	result = (NI)(a / b);	goto BeforeRet;
	}BeforeRet: ;
	return result;}


#line 346 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 347 "c:\\nim\\lib\\system\\arithm.nim"
	{
#line 347 "c:\\nim\\lib\\system\\arithm.nim"
		if (!(b == ((NI) 0))) goto LA3;

#line 348 "c:\\nim\\lib\\system\\arithm.nim"
		raiseDivByZero();
	}
	LA3: ;

#line 349 "c:\\nim\\lib\\system\\arithm.nim"

#line 349 "c:\\nim\\lib\\system\\arithm.nim"

#line 349 "c:\\nim\\lib\\system\\arithm.nim"
	result = (NI)(a % b);	goto BeforeRet;
	}BeforeRet: ;
	return result;}


#line 129 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(Cell47704*, usrtocell_51640)(void* usr) {
	Cell47704* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
#line 131 "c:\\nim\\lib\\system\\gc.nim"
	nimln(131, "gc.nim");
#line 131 "c:\\nim\\lib\\system\\gc.nim"

#line 131 "c:\\nim\\lib\\system\\gc.nim"
	result = ((Cell47704*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47704))))));	popFrame();	return result;}


#line 208 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, rtladdzct_53201)(Cell47704* c) {
	nimfr("rtlAddZCT", "gc.nim")

#line 212 "c:\\nim\\lib\\system\\gc.nim"
	nimln(212, "gc.nim");	addzct_51617((&gch_50059.zct), c);
	popFrame();}


#line 244 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell47704* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")

#line 246 "c:\\nim\\lib\\system\\gc.nim"
	nimln(246, "gc.nim");	c = usrtocell_51640(p);
#line 248 "c:\\nim\\lib\\system\\gc.nim"
	nimln(248, "gc.nim");	{
#line 180 "c:\\nim\\lib\\system\\gc.nim"
		nimln(180, "gc.nim");		(*c).refcount -= ((NI) 8);
#line 181 "c:\\nim\\lib\\system\\gc.nim"
		nimln(181, "gc.nim");		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;

#line 249 "c:\\nim\\lib\\system\\gc.nim"
		nimln(249, "gc.nim");		rtladdzct_53201(c);
	}
	LA3: ;
	popFrame();}


#line 1033 "c:\\nim\\lib\\pure\\os.nim"
N_NIMCALL(TY15805*, nosparseCmdLine)(NimStringDesc* c) {
	TY15805* result;
	NI i;
	NimStringDesc* a;
	nimfr("parseCmdLine", "os.nim")
	result = 0;
#line 1064 "c:\\nim\\lib\\pure\\os.nim"
	nimln(1064, "os.nim");	result = (TY15805*) newSeq((&NTI15805), 0);
#line 1065 "c:\\nim\\lib\\pure\\os.nim"
	nimln(1065, "os.nim");	i = ((NI) 0);
#line 1066 "c:\\nim\\lib\\pure\\os.nim"
	nimln(1066, "os.nim");	a = copyString(((NimStringDesc*) &TMP1120));	{
#line 1067 "c:\\nim\\lib\\pure\\os.nim"
		nimln(1067, "os.nim");		while (1) {			NIM_BOOL inquote;
			NimStringDesc* LOC49;
#line 1068 "c:\\nim\\lib\\pure\\os.nim"
			nimln(1068, "os.nim");			a = setLengthStr(a, ((NI) 0));			{
#line 1070 "c:\\nim\\lib\\pure\\os.nim"
				nimln(1070, "os.nim");				while (1) {					NIM_BOOL LOC5;					NIM_BOOL LOC6;					NIM_BOOL LOC7;					NI TMP1121;
#line 1070 "c:\\nim\\lib\\pure\\os.nim"
					LOC5 = 0;
#line 1070 "c:\\nim\\lib\\pure\\os.nim"
					LOC6 = 0;
#line 1070 "c:\\nim\\lib\\pure\\os.nim"
					LOC7 = 0;
#line 1070 "c:\\nim\\lib\\pure\\os.nim"
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();					LOC7 = ((NU8)(c->data[i]) == (NU8)(32));					if (LOC7) goto LA8;

#line 1070 "c:\\nim\\lib\\pure\\os.nim"
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();					LOC7 = ((NU8)(c->data[i]) == (NU8)(9));					LA8: ;
					LOC6 = LOC7;					if (LOC6) goto LA9;

#line 1070 "c:\\nim\\lib\\pure\\os.nim"
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();					LOC6 = ((NU8)(c->data[i]) == (NU8)(10));					LA9: ;
					LOC5 = LOC6;					if (LOC5) goto LA10;

#line 1070 "c:\\nim\\lib\\pure\\os.nim"
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();					LOC5 = ((NU8)(c->data[i]) == (NU8)(13));					LA10: ;
					if (!LOC5) goto LA4;

#line 1070 "c:\\nim\\lib\\pure\\os.nim"
					TMP1121 = addInt(i, ((NI) 1));					i = (NI)(TMP1121);				} LA4: ;			}

#line 1073 "c:\\nim\\lib\\pure\\os.nim"
			nimln(1073, "os.nim");			{
#line 1073 "c:\\nim\\lib\\pure\\os.nim"
				if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();				if (!((NU8)(c->data[i]) == (NU8)(0))) goto LA13;

#line 1073 "c:\\nim\\lib\\pure\\os.nim"
				goto LA1;
			}
			LA13: ;

#line 1074 "c:\\nim\\lib\\pure\\os.nim"
			nimln(1074, "os.nim");			inquote = NIM_FALSE;			{
#line 1075 "c:\\nim\\lib\\pure\\os.nim"
				nimln(1075, "os.nim");				while (1) {
#line 1076 "c:\\nim\\lib\\pure\\os.nim"
					nimln(1076, "os.nim");					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();					switch (((NU8)(c->data[i]))) {
					case 0:
					{
#line 1077 "c:\\nim\\lib\\pure\\os.nim"
						nimln(1077, "os.nim");						goto LA15;
					}
					break;
					case 92:
					{						NI j;

#line 1079 "c:\\nim\\lib\\pure\\os.nim"
						nimln(1079, "os.nim");						j = i;						{
#line 1080 "c:\\nim\\lib\\pure\\os.nim"
							nimln(1080, "os.nim");							while (1) {								NI TMP1122;
#line 1080 "c:\\nim\\lib\\pure\\os.nim"
								if ((NU)(j) > (NU)(c->Sup.len)) raiseIndexError();								if (!((NU8)(c->data[j]) == (NU8)(92))) goto LA20;

#line 1080 "c:\\nim\\lib\\pure\\os.nim"
								TMP1122 = addInt(j, ((NI) 1));								j = (NI)(TMP1122);							} LA20: ;						}

#line 1081 "c:\\nim\\lib\\pure\\os.nim"
						nimln(1081, "os.nim");						{
#line 1081 "c:\\nim\\lib\\pure\\os.nim"
							if ((NU)(j) > (NU)(c->Sup.len)) raiseIndexError();							if (!((NU8)(c->data[j]) == (NU8)(34))) goto LA23;
							{								NI k_134621;
								NI HEX3Atmp_134683;
								NI TMP1123;								NI TMP1124;								NI res_134686;
								k_134621 = 0;								HEX3Atmp_134683 = 0;
#line 1082 "c:\\nim\\lib\\pure\\os.nim"
								nimln(1082, "os.nim");
#line 1082 "c:\\nim\\lib\\pure\\os.nim"

#line 1082 "c:\\nim\\lib\\pure\\os.nim"
								TMP1123 = subInt(j, i);								TMP1124 = divInt((NI)(TMP1123), ((NI) 2));								HEX3Atmp_134683 = (NI)(TMP1124);
#line 1874 "c:\\nim\\lib\\system.nim"
								nimln(1874, "system.nim");								res_134686 = ((NI) 1);								{
#line 1875 "c:\\nim\\lib\\system.nim"
									nimln(1875, "system.nim");									while (1) {										NI TMP1125;
#line 1875 "c:\\nim\\lib\\system.nim"
										if (!(res_134686 <= HEX3Atmp_134683)) goto LA27;

#line 1876 "c:\\nim\\lib\\system.nim"
										nimln(1876, "system.nim");										k_134621 = res_134686;
#line 1082 "c:\\nim\\lib\\pure\\os.nim"
										nimln(1082, "os.nim");										a = addChar(a, 92);
#line 1895 "c:\\nim\\lib\\system.nim"
										nimln(1895, "system.nim");										TMP1125 = addInt(res_134686, ((NI) 1));										res_134686 = (NI)(TMP1125);									} LA27: ;								}
							}

#line 1083 "c:\\nim\\lib\\pure\\os.nim"
							nimln(1083, "os.nim");							{								NI TMP1126;								NI TMP1127;
#line 1083 "c:\\nim\\lib\\pure\\os.nim"

#line 1083 "c:\\nim\\lib\\pure\\os.nim"

#line 1083 "c:\\nim\\lib\\pure\\os.nim"
								TMP1126 = subInt(j, i);								TMP1127 = modInt((NI)(TMP1126), ((NI) 2));								if (!(((NI) ((NI)(TMP1127))) == ((NI) 0))) goto LA30;

#line 1084 "c:\\nim\\lib\\pure\\os.nim"
								nimln(1084, "os.nim");								i = j;							}
							goto LA28;
							LA30: ;
							{								NI TMP1128;
#line 1086 "c:\\nim\\lib\\pure\\os.nim"
								nimln(1086, "os.nim");								a = addChar(a, 34);
#line 1087 "c:\\nim\\lib\\pure\\os.nim"
								nimln(1087, "os.nim");
#line 1087 "c:\\nim\\lib\\pure\\os.nim"
								TMP1128 = addInt(j, ((NI) 1));								i = (NI)(TMP1128);							}
							LA28: ;
						}
						goto LA21;
						LA23: ;
						{							NI TMP1129;
#line 1089 "c:\\nim\\lib\\pure\\os.nim"
							nimln(1089, "os.nim");							if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();							a = addChar(a, c->data[i]);
#line 1090 "c:\\nim\\lib\\pure\\os.nim"
							nimln(1090, "os.nim");							TMP1129 = addInt(i, ((NI) 1));							i = (NI)(TMP1129);						}
						LA21: ;
					}
					break;
					case 34:
					{						NI TMP1130;
#line 1092 "c:\\nim\\lib\\pure\\os.nim"
						nimln(1092, "os.nim");						TMP1130 = addInt(i, ((NI) 1));						i = (NI)(TMP1130);
#line 1093 "c:\\nim\\lib\\pure\\os.nim"
						nimln(1093, "os.nim");						{
#line 1093 "c:\\nim\\lib\\pure\\os.nim"
							if (!!(inquote)) goto LA37;

#line 1093 "c:\\nim\\lib\\pure\\os.nim"
							inquote = NIM_TRUE;						}
						goto LA35;
						LA37: ;
						{							NI TMP1131;
#line 1094 "c:\\nim\\lib\\pure\\os.nim"
							nimln(1094, "os.nim");							if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();							if (!((NU8)(c->data[i]) == (NU8)(34))) goto LA40;

#line 1095 "c:\\nim\\lib\\pure\\os.nim"
							nimln(1095, "os.nim");							if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();							a = addChar(a, c->data[i]);
#line 1096 "c:\\nim\\lib\\pure\\os.nim"
							nimln(1096, "os.nim");							TMP1131 = addInt(i, ((NI) 1));							i = (NI)(TMP1131);						}
						goto LA35;
						LA40: ;
						{
#line 1098 "c:\\nim\\lib\\pure\\os.nim"
							nimln(1098, "os.nim");							inquote = NIM_FALSE;
#line 1099 "c:\\nim\\lib\\pure\\os.nim"
							nimln(1099, "os.nim");							goto LA15;
						}
						LA35: ;
					}
					break;
					case 32:
					case 9:
					{						NI TMP1132;
#line 1101 "c:\\nim\\lib\\pure\\os.nim"
						nimln(1101, "os.nim");						{
#line 1101 "c:\\nim\\lib\\pure\\os.nim"
							if (!!(inquote)) goto LA46;

#line 1101 "c:\\nim\\lib\\pure\\os.nim"
							goto LA15;
						}
						LA46: ;

#line 1102 "c:\\nim\\lib\\pure\\os.nim"
						nimln(1102, "os.nim");						if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();						a = addChar(a, c->data[i]);
#line 1103 "c:\\nim\\lib\\pure\\os.nim"
						nimln(1103, "os.nim");						TMP1132 = addInt(i, ((NI) 1));						i = (NI)(TMP1132);					}
					break;
					default:
					{						NI TMP1133;
#line 1105 "c:\\nim\\lib\\pure\\os.nim"
						nimln(1105, "os.nim");						if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();						a = addChar(a, c->data[i]);
#line 1106 "c:\\nim\\lib\\pure\\os.nim"
						nimln(1106, "os.nim");						TMP1133 = addInt(i, ((NI) 1));						i = (NI)(TMP1133);					}
					break;
					}
				}
			} LA15: ;
#line 1121 "c:\\nim\\lib\\pure\\os.nim"
			nimln(1121, "os.nim");			result = (TY15805*) incrSeqV2(&(result)->Sup, sizeof(NimStringDesc*));			LOC49 = 0;			LOC49 = result->data[result->Sup.len]; result->data[result->Sup.len] = copyStringRC1(a);			if (LOC49) nimGCunrefNoCycle(LOC49);			++result->Sup.len;		}
	} LA1: ;	popFrame();	return result;}


#line 261 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")

#line 264 "c:\\nim\\lib\\system\\gc.nim"
	nimln(264, "gc.nim");	{		Cell47704* c;

#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
		if (!!((src == NIM_NIL))) goto LA3;

#line 265 "c:\\nim\\lib\\system\\gc.nim"
		nimln(265, "gc.nim");		c = usrtocell_51640(src);
#line 182 "c:\\nim\\lib\\system\\gc.nim"
		nimln(182, "gc.nim");		(*c).refcount += ((NI) 8);	}
	LA3: ;

#line 267 "c:\\nim\\lib\\system\\gc.nim"
	nimln(267, "gc.nim");	{		Cell47704* c;

#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
		if (!!(((*dest) == NIM_NIL))) goto LA7;

#line 268 "c:\\nim\\lib\\system\\gc.nim"
		nimln(268, "gc.nim");		c = usrtocell_51640((*dest));
#line 269 "c:\\nim\\lib\\system\\gc.nim"
		nimln(269, "gc.nim");		{
#line 180 "c:\\nim\\lib\\system\\gc.nim"
			nimln(180, "gc.nim");			(*c).refcount -= ((NI) 8);
#line 181 "c:\\nim\\lib\\system\\gc.nim"
			nimln(181, "gc.nim");			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;

#line 270 "c:\\nim\\lib\\system\\gc.nim"
			nimln(270, "gc.nim");			rtladdzct_53201(c);
		}
		LA11: ;
	}
	LA7: ;

#line 271 "c:\\nim\\lib\\system\\gc.nim"
	nimln(271, "gc.nim");	(*dest) = src;	popFrame();}


#line 1267 "c:\\nim\\lib\\pure\\os.nim"
N_NIMCALL(NI, nosparamCount)(void) {
	NI result;
	NI TMP1134;	nimfr("paramCount", "os.nim")
	result = 0;
#line 1269 "c:\\nim\\lib\\pure\\os.nim"
	nimln(1269, "os.nim");	{		NI16* LOC5;		NimStringDesc* LOC6;
#line 1269 "c:\\nim\\lib\\pure\\os.nim"
		if (!ownargv_137402 == 0) goto LA3;

#line 1269 "c:\\nim\\lib\\pure\\os.nim"

#line 1269 "c:\\nim\\lib\\pure\\os.nim"

#line 168 "c:\\nim\\lib\\pure\\os.nim"
		nimln(168, "os.nim");		LOC5 = 0;		LOC5 = Dl_110433();		LOC6 = 0;		LOC6 = HEX24_84072(LOC5);		asgnRefNoCycle((void**) (&ownargv_137402), nosparseCmdLine(LOC6));	}
	LA3: ;

#line 1270 "c:\\nim\\lib\\pure\\os.nim"
	nimln(1270, "os.nim");
#line 1270 "c:\\nim\\lib\\pure\\os.nim"

#line 1270 "c:\\nim\\lib\\pure\\os.nim"
	TMP1134 = subInt((ownargv_137402 ? ownargv_137402->Sup.len : 0), ((NI) 1));	result = (NI)(TMP1134);	popFrame();	return result;}


#line 1272 "c:\\nim\\lib\\pure\\os.nim"
N_NIMCALL(NimStringDesc*, nosparamStr)(NI i) {
	NimStringDesc* result;
	nimfr("paramStr", "os.nim")
{	result = 0;
#line 1275 "c:\\nim\\lib\\pure\\os.nim"
	nimln(1275, "os.nim");	{		NI16* LOC5;		NimStringDesc* LOC6;
#line 1275 "c:\\nim\\lib\\pure\\os.nim"
		if (!ownargv_137402 == 0) goto LA3;

#line 1275 "c:\\nim\\lib\\pure\\os.nim"

#line 1275 "c:\\nim\\lib\\pure\\os.nim"

#line 168 "c:\\nim\\lib\\pure\\os.nim"
		nimln(168, "os.nim");		LOC5 = 0;		LOC5 = Dl_110433();		LOC6 = 0;		LOC6 = HEX24_84072(LOC5);		asgnRefNoCycle((void**) (&ownargv_137402), nosparseCmdLine(LOC6));	}
	LA3: ;

#line 1276 "c:\\nim\\lib\\pure\\os.nim"
	nimln(1276, "os.nim");
#line 1276 "c:\\nim\\lib\\pure\\os.nim"
	if ((NU)(i) >= (NU)(ownargv_137402->Sup.len)) raiseIndexError();	result = copyString(ownargv_137402->data[i]);	goto BeforeRet;
	}BeforeRet: ;
	popFrame();	return result;}
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void) {
	nimfr("os", "os.nim")
	popFrame();}

NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void) {
}

