/* Generated by Nim Compiler v0.13.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -g3 -O0  -I/home/fedorov_ag/Nim/lib -o /home/fedorov_ag/projects/SimplePaint/src/nimcache/stdlib_etcpriv.o /home/fedorov_ag/projects/SimplePaint/src/nimcache/stdlib_etcpriv.c */
#define NIM_INTBITS 64

#include "nimbase.h"

#line 20 "/home/fedorov_ag/Nim/lib/pure/etcpriv.nim"
static N_INLINE(NIM_BOOL, ismagicidentseparatorrune_156008)(NCSTRING cs, NI i);
#line 319 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b);
#line 13 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
N_NOINLINE(void, raiseOverflow)(void);
#line 303 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 298 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
N_NOINLINE(void, stackoverflow_22201)(void);
#line 49 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void);extern TFrame* frameptr_19436;


#line 319 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 320 "/home/fedorov_ag/Nim/lib/system/arithm.nim"

#line 320 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	result = (NI)((NU64)(a) + (NU64)(b));
#line 321 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	{		NIM_BOOL LOC3;
#line 321 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = 0;
#line 353 "/home/fedorov_ag/Nim/lib/system.nim"

#line 321 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ a));		if (LOC3) goto LA4;

#line 353 "/home/fedorov_ag/Nim/lib/system.nim"

#line 321 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ b));		LA4: ;
		if (!LOC3) goto LA5;

#line 322 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 323 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 303 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	LOC1 = 0;
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	{
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);	}
	goto LA2;
	LA4: ;
	{
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
#line 305 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	(*s).prev = frameptr_19436;
#line 306 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	frameptr_19436 = s;
#line 307 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	{
#line 307 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;

#line 307 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		stackoverflow_22201();
	}
	LA9: ;
}


#line 49 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 50 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	frameptr_19436 = (*frameptr_19436).prev;}


#line 20 "/home/fedorov_ag/Nim/lib/pure/etcpriv.nim"
static N_INLINE(NIM_BOOL, ismagicidentseparatorrune_156008)(NCSTRING cs, NI i) {
	NIM_BOOL result;
	NIM_BOOL LOC1;	NIM_BOOL LOC2;	NI TMP697;	NI TMP698;	nimfr("isMagicIdentSeparatorRune", "etcpriv.nim")
	result = 0;
#line 21 "/home/fedorov_ag/Nim/lib/pure/etcpriv.nim"
	nimln(21, "etcpriv.nim");
#line 22 "/home/fedorov_ag/Nim/lib/pure/etcpriv.nim"
	nimln(22, "etcpriv.nim");	LOC1 = 0;
#line 21 "/home/fedorov_ag/Nim/lib/pure/etcpriv.nim"
	nimln(21, "etcpriv.nim");	LOC2 = 0;
#line 21 "/home/fedorov_ag/Nim/lib/pure/etcpriv.nim"
	LOC2 = ((NU8)(cs[i]) == (NU8)(226));	if (!(LOC2)) goto LA3;

#line 22 "/home/fedorov_ag/Nim/lib/pure/etcpriv.nim"
	nimln(22, "etcpriv.nim");
#line 22 "/home/fedorov_ag/Nim/lib/pure/etcpriv.nim"
	TMP697 = addInt(i, ((NI) 1));	LOC2 = ((NU8)(cs[(NI)(TMP697)]) == (NU8)(128));	LA3: ;
	LOC1 = LOC2;	if (!(LOC1)) goto LA4;

#line 23 "/home/fedorov_ag/Nim/lib/pure/etcpriv.nim"
	nimln(23, "etcpriv.nim");
#line 23 "/home/fedorov_ag/Nim/lib/pure/etcpriv.nim"
	TMP698 = addInt(i, ((NI) 2));	LOC1 = ((NU8)(cs[(NI)(TMP698)]) == (NU8)(147));	LA4: ;
	result = LOC1;	popFrame();	return result;}
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit000)(void) {
	nimfr("etcpriv", "etcpriv.nim")
	popFrame();}

NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit000)(void) {
}

