/* Generated by Nim Compiler v0.13.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -g3 -O0  -I/home/fedorov_ag/Nim/lib -o /home/fedorov_ag/projects/SimplePaint/src/nimcache/stdlib_math.o /home/fedorov_ag/projects/SimplePaint/src/nimcache/stdlib_math.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <math.h>
#include <stdlib.h>

#line 24 "/home/fedorov_ag/Nim/lib/pure/math.nim"
N_NIMCALL(NI, binom_192202)(NI n, NI k);
#line 372 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
N_NIMCALL(NI, mulInt)(NI a, NI b);
#line 326 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b);
#line 13 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
N_NOINLINE(void, raiseOverflow)(void);
#line 319 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b);
#line 338 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, divInt)(NI a, NI b);
#line 17 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
N_NOINLINE(void, raiseDivByZero)(void);
#line 303 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 298 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
N_NOINLINE(void, stackoverflow_22201)(void);
#line 49 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void);
#line 32 "/home/fedorov_ag/Nim/lib/pure/math.nim"
N_NIMCALL(NI, fac_192226)(NI n);N_NIMCALL(NU8, classify_192617)(NF x);
N_NIMCALL(NIM_BOOL, ispoweroftwo_192623)(NI x);
N_NIMCALL(NI, nextpoweroftwo_192627)(NI x);
N_NIMCALL(NI, countbits32_193219)(NI32 n);
N_NIMCALL(NF, log2_193416)(NF x);
N_NIMCALL(NF, random_193273)(NF max);
N_NIMCALL(void, randomize_193276)(void);
N_NIMCALL(void, randomize_193401)(NI seed);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(NI, random_193270)(NI max);
N_NIMCALL(NF, mod_194617)(NF x, NF y);
extern TFrame* frameptr_19436;


#line 326 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 327 "/home/fedorov_ag/Nim/lib/system/arithm.nim"

#line 327 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	result = (NI)((NU64)(a) - (NU64)(b));
#line 328 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	{		NIM_BOOL LOC3;
#line 328 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = 0;
#line 353 "/home/fedorov_ag/Nim/lib/system.nim"

#line 328 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ a));		if (LOC3) goto LA4;

#line 353 "/home/fedorov_ag/Nim/lib/system.nim"

#line 328 "/home/fedorov_ag/Nim/lib/system/arithm.nim"

#line 328 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));		LA4: ;
		if (!LOC3) goto LA5;

#line 329 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 330 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 319 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 320 "/home/fedorov_ag/Nim/lib/system/arithm.nim"

#line 320 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	result = (NI)((NU64)(a) + (NU64)(b));
#line 321 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	{		NIM_BOOL LOC3;
#line 321 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = 0;
#line 353 "/home/fedorov_ag/Nim/lib/system.nim"

#line 321 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ a));		if (LOC3) goto LA4;

#line 353 "/home/fedorov_ag/Nim/lib/system.nim"

#line 321 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ b));		LA4: ;
		if (!LOC3) goto LA5;

#line 322 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 323 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 338 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 339 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	{
#line 339 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		if (!(b == ((NI) 0))) goto LA3;

#line 340 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		raiseDivByZero();
	}
	LA3: ;

#line 341 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	{		NIM_BOOL LOC7;
#line 341 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC7 = 0;
#line 341 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC7 = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));		if (!(LOC7)) goto LA8;

#line 341 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC7 = (b == ((NI) -1));		LA8: ;
		if (!LOC7) goto LA9;

#line 342 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		raiseOverflow();
	}
	LA9: ;

#line 343 "/home/fedorov_ag/Nim/lib/system/arithm.nim"

#line 343 "/home/fedorov_ag/Nim/lib/system/arithm.nim"

#line 343 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	result = (NI)(a / b);	goto BeforeRet;
	}BeforeRet: ;
	return result;}


#line 303 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	LOC1 = 0;
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	{
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);	}
	goto LA2;
	LA4: ;
	{
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
#line 305 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	(*s).prev = frameptr_19436;
#line 306 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	frameptr_19436 = s;
#line 307 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	{
#line 307 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;

#line 307 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		stackoverflow_22201();
	}
	LA9: ;
}


#line 49 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 50 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	frameptr_19436 = (*frameptr_19436).prev;}


#line 24 "/home/fedorov_ag/Nim/lib/pure/math.nim"
N_NIMCALL(NI, binom_192202)(NI n, NI k) {
	NI result;
	nimfr("binom", "math.nim")
{	result = 0;
#line 26 "/home/fedorov_ag/Nim/lib/pure/math.nim"
	nimln(26, "math.nim");	{
#line 26 "/home/fedorov_ag/Nim/lib/pure/math.nim"
		if (!(k <= ((NI) 0))) goto LA3;

#line 26 "/home/fedorov_ag/Nim/lib/pure/math.nim"

#line 26 "/home/fedorov_ag/Nim/lib/pure/math.nim"
		result = ((NI) 1);		goto BeforeRet;
	}
	LA3: ;

#line 27 "/home/fedorov_ag/Nim/lib/pure/math.nim"
	nimln(27, "math.nim");	{		NI TMP976;		NI TMP977;
#line 357 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(357, "system.nim");
#line 27 "/home/fedorov_ag/Nim/lib/pure/math.nim"
		nimln(27, "math.nim");		TMP976 = mulInt(((NI) 2), k);		if (!(n < (NI)(TMP976))) goto LA7;

#line 27 "/home/fedorov_ag/Nim/lib/pure/math.nim"

#line 27 "/home/fedorov_ag/Nim/lib/pure/math.nim"

#line 27 "/home/fedorov_ag/Nim/lib/pure/math.nim"
		TMP977 = subInt(n, k);		result = binom_192202(n, (NI)(TMP977));		goto BeforeRet;
	}
	LA7: ;

#line 28 "/home/fedorov_ag/Nim/lib/pure/math.nim"
	nimln(28, "math.nim");	result = n;	{		NI i_192218;
		NI res_192222;
		i_192218 = 0;
#line 1874 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(1874, "system.nim");		res_192222 = ((NI) 2);		{
#line 1875 "/home/fedorov_ag/Nim/lib/system.nim"
			nimln(1875, "system.nim");			while (1) {				NI TMP978;				NI TMP979;				NI TMP980;				NI TMP981;				NI TMP982;
#line 1875 "/home/fedorov_ag/Nim/lib/system.nim"
				if (!(res_192222 <= k)) goto LA11;

#line 1876 "/home/fedorov_ag/Nim/lib/system.nim"
				nimln(1876, "system.nim");				i_192218 = res_192222;
#line 30 "/home/fedorov_ag/Nim/lib/pure/math.nim"
				nimln(30, "math.nim");
#line 30 "/home/fedorov_ag/Nim/lib/pure/math.nim"

#line 30 "/home/fedorov_ag/Nim/lib/pure/math.nim"

#line 30 "/home/fedorov_ag/Nim/lib/pure/math.nim"

#line 30 "/home/fedorov_ag/Nim/lib/pure/math.nim"
				TMP978 = addInt(n, ((NI) 1));				TMP979 = subInt((NI)(TMP978), i_192218);				TMP980 = mulInt(result, (NI)(TMP979));				TMP981 = divInt((NI)(TMP980), i_192218);				result = (NI)(TMP981);
#line 1890 "/home/fedorov_ag/Nim/lib/system.nim"
				nimln(1890, "system.nim");				TMP982 = addInt(res_192222, ((NI) 1));				res_192222 = (NI)(TMP982);			} LA11: ;		}
	}
	}BeforeRet: ;
	popFrame();	return result;}


#line 32 "/home/fedorov_ag/Nim/lib/pure/math.nim"
N_NIMCALL(NI, fac_192226)(NI n) {
	NI result;
	nimfr("fac", "math.nim")
	result = 0;
#line 34 "/home/fedorov_ag/Nim/lib/pure/math.nim"
	nimln(34, "math.nim");	result = ((NI) 1);	{		NI i_192241;
		NI res_192245;
		i_192241 = 0;
#line 1874 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(1874, "system.nim");		res_192245 = ((NI) 2);		{
#line 1875 "/home/fedorov_ag/Nim/lib/system.nim"
			nimln(1875, "system.nim");			while (1) {				NI TMP983;				NI TMP984;
#line 1875 "/home/fedorov_ag/Nim/lib/system.nim"
				if (!(res_192245 <= n)) goto LA3;

#line 1876 "/home/fedorov_ag/Nim/lib/system.nim"
				nimln(1876, "system.nim");				i_192241 = res_192245;
#line 36 "/home/fedorov_ag/Nim/lib/pure/math.nim"
				nimln(36, "math.nim");
#line 36 "/home/fedorov_ag/Nim/lib/pure/math.nim"
				TMP983 = mulInt(result, i_192241);				result = (NI)(TMP983);
#line 1890 "/home/fedorov_ag/Nim/lib/system.nim"
				nimln(1890, "system.nim");				TMP984 = addInt(res_192245, ((NI) 1));				res_192245 = (NI)(TMP984);			} LA3: ;		}
	}
	popFrame();	return result;}

N_NIMCALL(NU8, classify_192617)(NF x) {
	NU8 result;
{	result = 0;
	{
		if (!(x == 0.0)) goto LA3;
		{
			if (!(((NF)(1.0000000000000000e+00) / (NF)(x)) == INF)) goto LA7;
			result = ((NU8) 2);
			goto BeforeRet;
		}
		goto LA5;
		LA7: ;
		{
			result = ((NU8) 3);
			goto BeforeRet;
		}
		LA5: ;
	}
	LA3: ;
	{
		if (!(((NF)(x) * (NF)(5.0000000000000000e-01)) == x)) goto LA12;
		{
			if (!(0.0 < x)) goto LA16;
			result = ((NU8) 5);
			goto BeforeRet;
		}
		goto LA14;
		LA16: ;
		{
			result = ((NU8) 6);
			goto BeforeRet;
		}
		LA14: ;
	}
	LA12: ;
	{
		if (!!((x == x))) goto LA21;
		result = ((NU8) 4);
		goto BeforeRet;
	}
	LA21: ;
	result = ((NU8) 0);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, ispoweroftwo_192623)(NI x) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
{	result = 0;
	LOC1 = 0;
	LOC1 = (((NI) 0) < x);
	if (!(LOC1)) goto LA2;
	LOC1 = ((NI)(x & (NI)(x - ((NI) 1))) == ((NI) 0));
	LA2: ;
	result = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, nextpoweroftwo_192627)(NI x) {
	NI result;
	result = 0;
	result = (NI)(x - ((NI) 1));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 32))));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 16))));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 8))));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 4))));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 2))));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 1))));
	result += ((NI) ((NI)(((NI) 1) + ((NI) ((x <= ((NI) 0)))))));
	return result;
}

N_NIMCALL(NI, countbits32_193219)(NI32 n) {
	NI result;
	NI32 v;
	result = 0;
	v = n;
	v = (NI32)((NU32)(v) - (NU32)((NI32)((NI32)((NU32)(v) >> (NU32)(((NI32) 1))) & ((NI32) 1431655765))));
	v = (NI32)((NU32)((NI32)(v & ((NI32) 858993459))) + (NU32)((NI32)((NI32)((NU32)(v) >> (NU32)(((NI32) 2))) & ((NI32) 858993459))));
	result = ((NI) ((NI32)((NU32)((NI32)((NU32)((NI32)((NI32)((NU32)(v) + (NU32)((NI32)((NU32)(v) >> (NU32)(((NI32) 4))))) & ((NI32) 252645135))) * (NU32)(((NI32) 16843009)))) >> (NU32)(((NI32) 24)))));
	return result;
}

N_NIMCALL(NF, log2_193416)(NF x) {
	NF result;
	NF LOC1;
	NF LOC2;
{	result = 0;
	LOC1 = 0;
	LOC1 = log(x);
	LOC2 = 0;
	LOC2 = log(2.0000000000000000e+00);
	result = ((NF)(LOC1) / (NF)(LOC2));
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NF, random_193273)(NF max) {
	NF result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = drand48();
	result = ((NF)(LOC1) * (NF)(max));
	return result;
}

N_NIMCALL(void, randomize_193401)(NI seed) {
	srand(((int) (seed)));
	srand48(seed);
}

N_NIMCALL(void, randomize_193276)(void) {
	union { NF source; NI dest; } LOC1;
	LOC1.source = ntepochTime();
	randomize_193401(LOC1.dest);
}

N_NIMCALL(NI, random_193270)(NI max) {
	NI result;
	int LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = rand();
	result = (NI)(((NI) (LOC1)) % max);
	return result;
}

N_NIMCALL(NF, mod_194617)(NF x, NF y) {
	NF result;
	result = 0;
	{
		if (!(y == 0.0)) goto LA3;
		result = x;
	}
	goto LA1;
	LA3: ;
	{
		NF LOC6;
		LOC6 = 0;
		LOC6 = floor(((NF)(x) / (NF)(y)));
		result = ((NF)(x) - (NF)(((NF)(y) * (NF)(LOC6))));
	}
	LA1: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void) {
	nimfr("math", "math.nim")
	popFrame();}

NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void) {
}

