/* Generated by Nim Compiler v0.13.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -g3 -O0  -I/home/fedorov_ag/Nim/lib -o /home/fedorov_ag/NimCode/SimplePaint/src/nimcache/stdlib_posix.o /home/fedorov_ag/NimCode/SimplePaint/src/nimcache/stdlib_posix.c */
#define NIM_INTBITS 64

#include "nimbase.h"

#line 303 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 298 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
N_NOINLINE(void, stackoverflow_22201)(void);
#line 49 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void);extern TFrame* frameptr_19436;


#line 303 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	LOC1 = 0;
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	{
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);	}
	goto LA2;
	LA4: ;
	{
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
#line 305 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	(*s).prev = frameptr_19436;
#line 306 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	frameptr_19436 = s;
#line 307 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	{
#line 307 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;

#line 307 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		stackoverflow_22201();
	}
	LA9: ;
}


#line 49 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 50 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	frameptr_19436 = (*frameptr_19436).prev;}
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void) {
	nimfr("posix", "posix.nim")
	popFrame();}

NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void) {
}

