/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -g3 -O0  -IC:\Nim\lib -o y:\nimcode\simplepaint\src\nimcache\stdlib_intsets.o y:\nimcode\simplepaint\src\nimcache\stdlib_intsets.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Trunk199025 Trunk199025;
typedef struct Intset199029 Intset199029;
typedef struct Trunkseq199027 Trunkseq199027;
typedef struct Cell47704 Cell47704;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cellset47716 Cellset47716;
typedef struct Gcheap50018 Gcheap50018;
typedef struct Gcstack50016 Gcstack50016;
typedef struct Cellseq47720 Cellseq47720;
typedef struct Pagedesc47712 Pagedesc47712;
typedef struct Memregion29888 Memregion29888;
typedef struct Smallchunk29840 Smallchunk29840;
typedef struct Llchunk29882 Llchunk29882;
typedef struct Bigchunk29842 Bigchunk29842;
typedef struct Intset29814 Intset29814;
typedef struct Trunk29810 Trunk29810;
typedef struct Avlnode29886 Avlnode29886;
typedef struct Gcstat50014 Gcstat50014;
typedef struct Basechunk29838 Basechunk29838;
typedef struct Freecell29830 Freecell29830;
struct  TGenericSeq  {NI len;
NI reserved;
};
struct  NimStringDesc  {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Intset199029  {NI counter;
NI max;
Trunk199025* head;
Trunkseq199027* data;
};
typedef NI TY29819[8];
struct  Trunk199025  {Trunk199025* next;
NI key;
TY29819 bits;
};
struct  Cell47704  {NI refcount;
TNimType* typ;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  Cellseq47720  {NI len;
NI cap;
Cell47704** d;
};
struct  Cellset47716  {NI counter;
NI max;
Pagedesc47712* head;
Pagedesc47712** data;
};
typedef Smallchunk29840* TY29903[512];
typedef Trunk29810* Trunkbuckets29812[256];
struct  Intset29814  {Trunkbuckets29812 data;
};
struct  Memregion29888  {NI minlargeobj;
NI maxlargeobj;
TY29903 freesmallchunks;
Llchunk29882* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29842* freechunkslist;
Intset29814 chunkstarts;
Avlnode29886* root;
Avlnode29886* deleted;
Avlnode29886* last;
Avlnode29886* freeavlnodes;
};
struct  Gcstat50014  {NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap50018  {Gcstack50016* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47720 zct;
Cellseq47720 decstack;
Cellset47716 cycleroots;
Cellseq47720 tempstack;
NI recgclock;
Memregion29888 region;
Gcstat50014 stat;
};
struct  TNimNode  {NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Gcstack50016  {Gcstack50016* prev;
Gcstack50016* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Pagedesc47712  {Pagedesc47712* next;
NI key;
TY29819 bits;
};
struct  Basechunk29838  {NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29840  {  Basechunk29838 Sup;Smallchunk29840* next;
Smallchunk29840* prev;
Freecell29830* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29882  {NI size;
NI acc;
Llchunk29882* next;
};
struct  Bigchunk29842  {  Basechunk29838 Sup;Bigchunk29842* next;
Bigchunk29842* prev;
NI align;
NF data;
};
struct  Trunk29810  {Trunk29810* next;
NI key;
TY29819 bits;
};
typedef Avlnode29886* TY29893[2];
struct  Avlnode29886  {TY29893 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell29830  {Freecell29830* next;
NI zerofield;
};
struct Trunkseq199027 {  TGenericSeq Sup;  Trunk199025* data[SEQ_DECL_SIZE];};
#line 47 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
static N_INLINE(NIM_BOOL, mustrehash_199042)(NI length, NI counter);
#line 3329 "c:\\nim\\lib\\system.nim"
N_NIMCALL(void, failedassertimpl_90316)(NimStringDesc* msg);
#line 372 "c:\\nim\\lib\\system\\arithm.nim"
N_NIMCALL(NI, mulInt)(NI a, NI b);
#line 326 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b);
#line 13 "c:\\nim\\lib\\system\\arithm.nim"
N_NOINLINE(void, raiseOverflow)(void);
#line 303 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 298 "c:\\nim\\lib\\system\\excpt.nim"
N_NOINLINE(void, stackoverflow_22201)(void);
#line 49 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void);
#line 51 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
static N_INLINE(NI, nexttry_199201)(NI h, NI maxhash);
#line 319 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b);
#line 54 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(Trunk199025*, intsetget_199206)(Intset199029* t, NI key);
#line 18 "c:\\nim\\lib\\system\\chcks.nim"
N_NOINLINE(void, raiseIndexError)(void);
#line 62 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(void, intsetrawinsert_199225)(Intset199029* t, Trunkseq199027** data, Trunk199025* desc);
#line 253 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, asgnRef)(void** dest, void* src);
#line 227 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, incref_54019)(Cell47704* c);
#line 133 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(NIM_BOOL, canbecycleroot_51658)(Cell47704* c);
#line 197 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, rtladdcycleroot_52420)(Cell47704* c);
#line 159 "c:\\nim\\lib\\system\\cellsets.nim"
N_NOINLINE(void, incl_48447)(Cellset47716* s, Cell47704* cell);
#line 129 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(Cell47704*, usrtocell_51640)(void* usr);
#line 216 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, decref_53601)(Cell47704* c);
#line 208 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, rtladdzct_53201)(Cell47704* c);
#line 120 "c:\\nim\\lib\\system\\gc.nim"
N_NOINLINE(void, addzct_51617)(Cellseq47720* s, Cell47704* c);
#line 70 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(void, intsetenlarge_199602)(Intset199029* t);
#line 30 "c:\\nim\\lib\\system\\chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
#line 12 "c:\\nim\\lib\\system\\chcks.nim"
N_NOINLINE(void, raiseRangeError)(NI64 val);
#line 735 "c:\\nim\\lib\\system\\gc.nim"
N_NIMCALL(void, nimGCvisit)(void* d, NI op);N_NIMCALL(void, TMP1008)(void* p, NI op);
N_NIMCALL(void, TMP1009)(void* p, NI op);

#line 473 "c:\\nim\\lib\\system\\gc.nim"
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
#line 273 "c:\\nim\\lib\\system\\gc.nim"
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
#line 79 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(Trunk199025*, intsetput_199661)(Intset199029* t, NI key);
#line 468 "c:\\nim\\lib\\system\\gc.nim"
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
#line 96 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(NIM_BOOL, contains_199811)(Intset199029* s, NI key);
#line 105 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(void, incl_199832)(Intset199029* s, NI key);
#line 112 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(void, excl_199841)(Intset199029* s, NI key);
#line 120 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(NIM_BOOL, containsorincl_199862)(Intset199029* s, NI key);
#line 134 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(void, initintset_199885)(Intset199029* Result);
#line 141 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
static N_INLINE(NIM_BOOL, isnil_199898)(Intset199029* x);
#line 143 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(void, assign_199910)(Intset199029* dest, Intset199029* src);
#line 192 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(NimStringDesc*, HEX24_200072)(Intset199029* s);
#line 90 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
#line 179 "c:\\nim\\lib\\system\\sysstr.nim"
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
#line 168 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
#line 259 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
#line 196 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
static N_INLINE(NIM_BOOL, empty_200090)(Intset199029* s);STRING_LITERAL(TMP995, "\015\012  counter < length ", 21);
STRING_LITERAL(TMP1001, "\015\012  not (data[h] == desc) ", 26);
STRING_LITERAL(TMP1002, "data[h] == nil ", 15);
STRING_LITERAL(TMP1013, "t.data[h] == nil ", 17);
STRING_LITERAL(TMP1014, "dest.data[h] == nil ", 20);
STRING_LITERAL(TMP1015, "{", 1);
STRING_LITERAL(TMP1016, ", ", 2);
STRING_LITERAL(TMP1019, "}", 1);
extern TFrame* frameptr_19436;
extern Gcheap50018 gch_50059;
TNimType NTI199025; /* Trunk */
extern TNimType NTI104; /* int */
extern TNimType NTI29819; /* array[0..7, int] */
TNimType NTI199023; /* PTrunk */
TNimType NTI199027; /* TrunkSeq */


#line 326 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 327 "c:\\nim\\lib\\system\\arithm.nim"

#line 327 "c:\\nim\\lib\\system\\arithm.nim"
	result = (NI)((NU64)(a) - (NU64)(b));
#line 328 "c:\\nim\\lib\\system\\arithm.nim"
	{		NIM_BOOL LOC3;
#line 328 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = 0;
#line 353 "c:\\nim\\lib\\system.nim"

#line 328 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ a));		if (LOC3) goto LA4;

#line 353 "c:\\nim\\lib\\system.nim"

#line 328 "c:\\nim\\lib\\system\\arithm.nim"

#line 328 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));		LA4: ;
		if (!LOC3) goto LA5;

#line 329 "c:\\nim\\lib\\system\\arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 330 "c:\\nim\\lib\\system\\arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 303 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
	LOC1 = 0;
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
	{
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);	}
	goto LA2;
	LA4: ;
	{
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
#line 305 "c:\\nim\\lib\\system\\excpt.nim"
	(*s).prev = frameptr_19436;
#line 306 "c:\\nim\\lib\\system\\excpt.nim"
	frameptr_19436 = s;
#line 307 "c:\\nim\\lib\\system\\excpt.nim"
	{
#line 307 "c:\\nim\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;

#line 307 "c:\\nim\\lib\\system\\excpt.nim"
		stackoverflow_22201();
	}
	LA9: ;
}


#line 49 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 50 "c:\\nim\\lib\\system\\excpt.nim"
	frameptr_19436 = (*frameptr_19436).prev;}


#line 47 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
static N_INLINE(NIM_BOOL, mustrehash_199042)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;	NI TMP996;	NI TMP997;	NI TMP998;	nimfr("mustRehash", "intsets.nim")
	result = 0;
#line 48 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(48, "intsets.nim");	{
#line 48 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 48 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		if (!!((counter < length))) goto LA3;

#line 48 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		failedassertimpl_90316(((NimStringDesc*) &TMP995));
	}
	LA3: ;

#line 49 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(49, "intsets.nim");
#line 49 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	LOC5 = 0;
#line 49 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 49 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	TMP996 = mulInt(length, ((NI) 2));
#line 49 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	TMP997 = mulInt(counter, ((NI) 3));	LOC5 = ((NI)(TMP996) < (NI)(TMP997));	if (LOC5) goto LA6;

#line 49 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 49 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	TMP998 = subInt(length, counter);	LOC5 = ((NI)(TMP998) < ((NI) 4));	LA6: ;
	result = LOC5;	popFrame();	return result;}


#line 319 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 320 "c:\\nim\\lib\\system\\arithm.nim"

#line 320 "c:\\nim\\lib\\system\\arithm.nim"
	result = (NI)((NU64)(a) + (NU64)(b));
#line 321 "c:\\nim\\lib\\system\\arithm.nim"
	{		NIM_BOOL LOC3;
#line 321 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = 0;
#line 353 "c:\\nim\\lib\\system.nim"

#line 321 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ a));		if (LOC3) goto LA4;

#line 353 "c:\\nim\\lib\\system.nim"

#line 321 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ b));		LA4: ;
		if (!LOC3) goto LA5;

#line 322 "c:\\nim\\lib\\system\\arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 323 "c:\\nim\\lib\\system\\arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 51 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
static N_INLINE(NI, nexttry_199201)(NI h, NI maxhash) {
	NI result;
	NI TMP999;	NI TMP1000;	nimfr("nextTry", "intsets.nim")
	result = 0;
#line 52 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(52, "intsets.nim");
#line 52 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 52 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 52 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	TMP999 = mulInt(((NI) 5), h);	TMP1000 = addInt((NI)(TMP999), ((NI) 1));	result = (NI)((NI)(TMP1000) & maxhash);	popFrame();	return result;}


#line 54 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(Trunk199025*, intsetget_199206)(Intset199029* t, NI key) {
	Trunk199025* result;
	NI h;
	nimfr("intSetGet", "intsets.nim")
{	result = 0;
#line 55 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(55, "intsets.nim");
#line 55 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	h = (NI)(key & (*t).max);	{
#line 56 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(56, "intsets.nim");		while (1) {
#line 349 "c:\\nim\\lib\\system.nim"
			nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();			if (!!(((*t).data->data[h] == NIM_NIL))) goto LA2;

#line 57 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(57, "intsets.nim");			{
#line 57 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();				if (!((*(*t).data->data[h]).key == key)) goto LA5;

#line 58 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
				nimln(58, "intsets.nim");
#line 58 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();				result = (*t).data->data[h];				goto BeforeRet;
			}
			LA5: ;

#line 59 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(59, "intsets.nim");			h = nexttry_199201(h, (*t).max);		} LA2: ;	}

#line 60 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(60, "intsets.nim");	result = NIM_NIL;	}BeforeRet: ;
	popFrame();	return result;}


#line 133 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(NIM_BOOL, canbecycleroot_51658)(Cell47704* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
#line 134 "c:\\nim\\lib\\system\\gc.nim"
	nimln(134, "gc.nim");
#line 1104 "c:\\nim\\lib\\system.nim"
	nimln(1104, "system.nim");
#line 1104 "c:\\nim\\lib\\system.nim"
	result = !((((*(*c).typ).flags &(1U<<((NU)(((NU8) 1))&7U)))!=0));	popFrame();	return result;}


#line 197 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, rtladdcycleroot_52420)(Cell47704* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")

#line 202 "c:\\nim\\lib\\system\\gc.nim"
	nimln(202, "gc.nim");	{
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 147 "c:\\nim\\lib\\system\\gc.nim"
		nimln(147, "gc.nim");		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;

#line 152 "c:\\nim\\lib\\system\\gc.nim"
		nimln(152, "gc.nim");
#line 152 "c:\\nim\\lib\\system\\gc.nim"

#line 152 "c:\\nim\\lib\\system\\gc.nim"
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
#line 204 "c:\\nim\\lib\\system\\gc.nim"
		nimln(204, "gc.nim");		incl_48447((&gch_50059.cycleroots), c);
	}
	LA3: ;
	popFrame();}


#line 227 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, incref_54019)(Cell47704* c) {
	nimfr("incRef", "gc.nim")

#line 229 "c:\\nim\\lib\\system\\gc.nim"
	nimln(229, "gc.nim");
#line 229 "c:\\nim\\lib\\system\\gc.nim"
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
#line 232 "c:\\nim\\lib\\system\\gc.nim"
	nimln(232, "gc.nim");	{		NIM_BOOL LOC3;
#line 232 "c:\\nim\\lib\\system\\gc.nim"
		LOC3 = 0;		LOC3 = canbecycleroot_51658(c);		if (!LOC3) goto LA4;

#line 233 "c:\\nim\\lib\\system\\gc.nim"
		nimln(233, "gc.nim");		rtladdcycleroot_52420(c);
	}
	LA4: ;
	popFrame();}


#line 129 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(Cell47704*, usrtocell_51640)(void* usr) {
	Cell47704* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
#line 131 "c:\\nim\\lib\\system\\gc.nim"
	nimln(131, "gc.nim");
#line 131 "c:\\nim\\lib\\system\\gc.nim"

#line 131 "c:\\nim\\lib\\system\\gc.nim"
	result = ((Cell47704*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47704))))));	popFrame();	return result;}


#line 208 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, rtladdzct_53201)(Cell47704* c) {
	nimfr("rtlAddZCT", "gc.nim")

#line 212 "c:\\nim\\lib\\system\\gc.nim"
	nimln(212, "gc.nim");	addzct_51617((&gch_50059.zct), c);
	popFrame();}


#line 216 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, decref_53601)(Cell47704* c) {
	nimfr("decRef", "gc.nim")

#line 219 "c:\\nim\\lib\\system\\gc.nim"
	nimln(219, "gc.nim");	{
#line 180 "c:\\nim\\lib\\system\\gc.nim"
		nimln(180, "gc.nim");		(*c).refcount -= ((NI) 8);
#line 181 "c:\\nim\\lib\\system\\gc.nim"
		nimln(181, "gc.nim");		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;

#line 220 "c:\\nim\\lib\\system\\gc.nim"
		nimln(220, "gc.nim");		rtladdzct_53201(c);
	}
	goto LA1;
	LA3: ;
	{		NIM_BOOL LOC6;
#line 221 "c:\\nim\\lib\\system\\gc.nim"
		nimln(221, "gc.nim");		LOC6 = 0;		LOC6 = canbecycleroot_51658(c);		if (!LOC6) goto LA7;

#line 224 "c:\\nim\\lib\\system\\gc.nim"
		nimln(224, "gc.nim");		rtladdcycleroot_52420(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();}


#line 253 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")

#line 257 "c:\\nim\\lib\\system\\gc.nim"
	nimln(257, "gc.nim");	{		Cell47704* LOC5;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
		if (!!((src == NIM_NIL))) goto LA3;

#line 257 "c:\\nim\\lib\\system\\gc.nim"
		nimln(257, "gc.nim");
#line 257 "c:\\nim\\lib\\system\\gc.nim"
		LOC5 = 0;		LOC5 = usrtocell_51640(src);		incref_54019(LOC5);
	}
	LA3: ;

#line 258 "c:\\nim\\lib\\system\\gc.nim"
	nimln(258, "gc.nim");	{		Cell47704* LOC10;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
		if (!!(((*dest) == NIM_NIL))) goto LA8;

#line 258 "c:\\nim\\lib\\system\\gc.nim"
		nimln(258, "gc.nim");
#line 258 "c:\\nim\\lib\\system\\gc.nim"
		LOC10 = 0;		LOC10 = usrtocell_51640((*dest));		decref_53601(LOC10);
	}
	LA8: ;

#line 259 "c:\\nim\\lib\\system\\gc.nim"
	nimln(259, "gc.nim");	(*dest) = src;	popFrame();}


#line 62 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(void, intsetrawinsert_199225)(Intset199029* t, Trunkseq199027** data, Trunk199025* desc) {
	NI h;
	nimfr("intSetRawInsert", "intsets.nim")

#line 63 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(63, "intsets.nim");
#line 63 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	h = (NI)((*desc).key & (*t).max);	{
#line 64 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(64, "intsets.nim");		while (1) {
#line 349 "c:\\nim\\lib\\system.nim"
			nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
			if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();			if (!!(((*data)->data[h] == NIM_NIL))) goto LA2;

#line 65 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(65, "intsets.nim");			{
#line 65 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 65 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 65 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
				if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();				if (!!(!(((*data)->data[h] == desc)))) goto LA5;

#line 65 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
				failedassertimpl_90316(((NimStringDesc*) &TMP1001));
			}
			LA5: ;

#line 66 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(66, "intsets.nim");			h = nexttry_199201(h, (*t).max);		} LA2: ;	}

#line 67 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(67, "intsets.nim");	{
#line 67 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 67 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();		if (!!(((*data)->data[h] == NIM_NIL))) goto LA9;

#line 67 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		failedassertimpl_90316(((NimStringDesc*) &TMP1002));
	}
	LA9: ;

#line 68 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(68, "intsets.nim");	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();	asgnRef((void**) (&(*data)->data[h]), desc);	popFrame();}


#line 30 "c:\\nim\\lib\\system\\chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
#line 31 "c:\\nim\\lib\\system\\chcks.nim"
	{		NIM_BOOL LOC3;
#line 31 "c:\\nim\\lib\\system\\chcks.nim"
		LOC3 = 0;
#line 353 "c:\\nim\\lib\\system.nim"
		LOC3 = (a <= i);		if (!(LOC3)) goto LA4;

#line 31 "c:\\nim\\lib\\system\\chcks.nim"
		LOC3 = (i <= b);		LA4: ;
		if (!LOC3) goto LA5;

#line 32 "c:\\nim\\lib\\system\\chcks.nim"

#line 32 "c:\\nim\\lib\\system\\chcks.nim"
		result = i;		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
#line 34 "c:\\nim\\lib\\system\\chcks.nim"
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;}
N_NIMCALL(void, TMP1008)(void* p, NI op) {
	Trunk199025* a;
	NI LOC1;	a = (Trunk199025*)p;
	nimGCvisit((void*)(*a).next, op);	LOC1 = 0;	for (LOC1 = 0; LOC1 < 8; LOC1++) {	}
}
N_NIMCALL(void, TMP1009)(void* p, NI op) {
	Trunkseq199027* a;
	NI LOC1;	a = (Trunkseq199027*)p;
	LOC1 = 0;	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);	}
}


#line 70 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(void, intsetenlarge_199602)(Intset199029* t) {
	Trunkseq199027* n;
	NI oldmax;
	NI TMP1003;	NI TMP1004;	NI TMP1005;	NI TMP1006;	Trunkseq199027* LOC8;	nimfr("intSetEnlarge", "intsets.nim")
	n = 0;
#line 72 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(72, "intsets.nim");	oldmax = (*t).max;
#line 73 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(73, "intsets.nim");
#line 73 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 73 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 73 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	TMP1003 = addInt((*t).max, ((NI) 1));	TMP1004 = mulInt((NI)(TMP1003), ((NI) 2));	TMP1005 = subInt((NI)(TMP1004), ((NI) 1));	(*t).max = (NI)(TMP1005);
#line 74 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(74, "intsets.nim");
#line 74 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	TMP1006 = addInt((*t).max, ((NI) 1));	n = (Trunkseq199027*) newSeq((&NTI199027), ((NI)chckRange((NI)(TMP1006), ((NI) 0), ((NI) IL64(9223372036854775807)))));	{		NI i_199629;
		NI res_199657;
		i_199629 = 0;
#line 1874 "c:\\nim\\lib\\system.nim"
		nimln(1874, "system.nim");		res_199657 = ((NI) 0);		{
#line 1875 "c:\\nim\\lib\\system.nim"
			nimln(1875, "system.nim");			while (1) {				NI TMP1010;
#line 1875 "c:\\nim\\lib\\system.nim"
				if (!(res_199657 <= oldmax)) goto LA3;

#line 1876 "c:\\nim\\lib\\system.nim"
				nimln(1876, "system.nim");				i_199629 = res_199657;
#line 76 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
				nimln(76, "intsets.nim");				{
#line 349 "c:\\nim\\lib\\system.nim"
					nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
					if ((NU)(i_199629) >= (NU)((*t).data->Sup.len)) raiseIndexError();					if (!!(((*t).data->data[i_199629] == NIM_NIL))) goto LA6;

#line 76 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
					nimln(76, "intsets.nim");					if ((NU)(i_199629) >= (NU)((*t).data->Sup.len)) raiseIndexError();					intsetrawinsert_199225((&(*t)), (&n), (*t).data->data[i_199629]);
				}
				LA6: ;

#line 1890 "c:\\nim\\lib\\system.nim"
				nimln(1890, "system.nim");				TMP1010 = addInt(res_199657, ((NI) 1));				res_199657 = (NI)(TMP1010);			} LA3: ;		}
	}

#line 77 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(77, "intsets.nim");	LOC8 = 0;	LOC8 = (*t).data;	unsureAsgnRef((void**) (&(*t).data), n);	n = LOC8;	popFrame();}


#line 79 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(Trunk199025*, intsetput_199661)(Intset199029* t, NI key) {
	Trunk199025* result;
	NI h;
	NI TMP1012;	nimfr("intSetPut", "intsets.nim")
{	result = 0;
#line 80 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(80, "intsets.nim");
#line 80 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	h = (NI)(key & (*t).max);	{
#line 81 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(81, "intsets.nim");		while (1) {
#line 349 "c:\\nim\\lib\\system.nim"
			nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();			if (!!(((*t).data->data[h] == NIM_NIL))) goto LA2;

#line 82 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(82, "intsets.nim");			{
#line 82 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();				if (!((*(*t).data->data[h]).key == key)) goto LA5;

#line 83 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
				nimln(83, "intsets.nim");
#line 83 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();				result = (*t).data->data[h];				goto BeforeRet;
			}
			LA5: ;

#line 84 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(84, "intsets.nim");			h = nexttry_199201(h, (*t).max);		} LA2: ;	}

#line 85 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(85, "intsets.nim");	{		NI TMP1011;		NIM_BOOL LOC9;
#line 85 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 85 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		TMP1011 = addInt((*t).max, ((NI) 1));		LOC9 = 0;		LOC9 = mustrehash_199042((NI)(TMP1011), (*t).counter);		if (!LOC9) goto LA10;

#line 85 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		intsetenlarge_199602(t);
	}
	LA10: ;

#line 86 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(86, "intsets.nim");	TMP1012 = addInt((*t).counter, ((NI) 1));	(*t).counter = (NI)(TMP1012);
#line 87 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(87, "intsets.nim");
#line 87 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	h = (NI)(key & (*t).max);	{
#line 88 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(88, "intsets.nim");		while (1) {
#line 349 "c:\\nim\\lib\\system.nim"
			nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();			if (!!(((*t).data->data[h] == NIM_NIL))) goto LA13;

#line 88 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(88, "intsets.nim");			h = nexttry_199201(h, (*t).max);		} LA13: ;	}

#line 89 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(89, "intsets.nim");	{
#line 89 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 89 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();		if (!!(((*t).data->data[h] == NIM_NIL))) goto LA16;

#line 89 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		failedassertimpl_90316(((NimStringDesc*) &TMP1013));
	}
	LA16: ;

#line 90 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(90, "intsets.nim");	result = (Trunk199025*) newObj((&NTI199023), sizeof(Trunk199025));
#line 91 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(91, "intsets.nim");	asgnRef((void**) (&(*result).next), (*t).head);
#line 92 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(92, "intsets.nim");	(*result).key = key;
#line 93 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(93, "intsets.nim");	unsureAsgnRef((void**) (&(*t).head), result);
#line 94 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(94, "intsets.nim");	if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();	asgnRef((void**) (&(*t).data->data[h]), result);	}BeforeRet: ;
	popFrame();	return result;}


#line 96 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(NIM_BOOL, contains_199811)(Intset199029* s, NI key) {
	NIM_BOOL result;
	Trunk199025* t;
	nimfr("contains", "intsets.nim")
	result = 0;
#line 98 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(98, "intsets.nim");
#line 98 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	t = intsetget_199206(s, (NI)((NU64)(key) >> (NU64)(((NI) 9))));
#line 99 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(99, "intsets.nim");	{		NI u;

#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
		if (!!((t == NIM_NIL))) goto LA3;

#line 100 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(100, "intsets.nim");
#line 100 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		u = (NI)(key & ((NI) 511));
#line 101 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(101, "intsets.nim");
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 101 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(101, "intsets.nim");
#line 101 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		if ((NU)((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
#line 101 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 101 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		result = !(((NI)((*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u)) & ((NI) 63))))))) == ((NI) 0)));	}
	goto LA1;
	LA3: ;
	{
#line 103 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(103, "intsets.nim");		result = NIM_FALSE;	}
	LA1: ;
	popFrame();	return result;}


#line 105 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(void, incl_199832)(Intset199029* s, NI key) {
	Trunk199025* t;
	NI u;
	nimfr("incl", "intsets.nim")

#line 107 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(107, "intsets.nim");
#line 107 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	t = intsetput_199661(s, (NI)((NU64)(key) >> (NU64)(((NI) 9))));
#line 108 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(108, "intsets.nim");
#line 108 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	u = (NI)(key & ((NI) 511));
#line 109 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(109, "intsets.nim");
#line 109 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	if ((NU)((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
#line 109 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 109 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	if ((NU)((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
#line 110 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(110, "intsets.nim");
#line 110 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	(*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] = (NI)((*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] | (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u)) & ((NI) 63)))))));	popFrame();}


#line 112 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(void, excl_199841)(Intset199029* s, NI key) {
	Trunk199025* t;
	nimfr("excl", "intsets.nim")

#line 114 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(114, "intsets.nim");
#line 114 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	t = intsetget_199206((&(*s)), (NI)((NU64)(key) >> (NU64)(((NI) 9))));
#line 115 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(115, "intsets.nim");	{		NI u;

#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
		if (!!((t == NIM_NIL))) goto LA3;

#line 116 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(116, "intsets.nim");
#line 116 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		u = (NI)(key & ((NI) 511));
#line 117 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(117, "intsets.nim");
#line 117 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		if ((NU)((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
#line 117 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 117 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		if ((NU)((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
#line 118 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(118, "intsets.nim");
#line 118 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 118 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		(*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] = (NI)((*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64) ~((NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u)) & ((NI) 63)))))))));	}
	LA3: ;
	popFrame();}


#line 120 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(NIM_BOOL, containsorincl_199862)(Intset199029* s, NI key) {
	NIM_BOOL result;
	Trunk199025* t;
	nimfr("containsOrIncl", "intsets.nim")
	result = 0;
#line 123 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(123, "intsets.nim");
#line 123 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	t = intsetget_199206((&(*s)), (NI)((NU64)(key) >> (NU64)(((NI) 9))));
#line 124 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(124, "intsets.nim");	{		NI u;

#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
		if (!!((t == NIM_NIL))) goto LA3;

#line 125 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(125, "intsets.nim");
#line 125 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		u = (NI)(key & ((NI) 511));
#line 126 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(126, "intsets.nim");
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 126 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(126, "intsets.nim");
#line 126 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		if ((NU)((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
#line 126 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 126 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		result = !(((NI)((*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u)) & ((NI) 63))))))) == ((NI) 0)));
#line 127 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(127, "intsets.nim");		{
#line 127 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			if (!!(result)) goto LA7;

#line 128 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(128, "intsets.nim");
#line 128 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			if ((NU)((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
#line 128 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 128 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			if ((NU)((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
#line 129 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(129, "intsets.nim");
#line 129 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			(*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] = (NI)((*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] | (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u)) & ((NI) 63)))))));		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
#line 131 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(131, "intsets.nim");		incl_199832(s, key);

#line 132 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(132, "intsets.nim");		result = NIM_FALSE;	}
	LA1: ;
	popFrame();	return result;}


#line 134 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(void, initintset_199885)(Intset199029* Result) {
	nimfr("initIntSet", "intsets.nim")

#line 136 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(136, "intsets.nim");	unsureAsgnRef((void**) (&(*Result).data), (Trunkseq199027*) newSeq((&NTI199027), ((NI) 8)));
#line 137 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(137, "intsets.nim");	(*Result).max = ((NI) 7);
#line 138 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(138, "intsets.nim");	(*Result).counter = ((NI) 0);
#line 139 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(139, "intsets.nim");	unsureAsgnRef((void**) (&(*Result).head), NIM_NIL);	popFrame();}


#line 141 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
static N_INLINE(NIM_BOOL, isnil_199898)(Intset199029* x) {
	NIM_BOOL result;
	nimfr("isNil", "intsets.nim")
	result = 0;
#line 141 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(141, "intsets.nim");
#line 141 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	result = (*x).head == 0;	popFrame();	return result;}


#line 143 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(void, assign_199910)(Intset199029* dest, Intset199029* src) {
	Trunk199025* it;
	nimfr("assign", "intsets.nim")

#line 146 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(146, "intsets.nim");	(*dest).counter = (*src).counter;
#line 147 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(147, "intsets.nim");	(*dest).max = (*src).max;
#line 148 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(148, "intsets.nim");
#line 148 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	unsureAsgnRef((void**) (&(*dest).data), (Trunkseq199027*) newSeq((&NTI199027), ((NI)chckRange(((*src).data ? (*src).data->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807))))));
#line 150 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(150, "intsets.nim");	it = (*src).head;	{
#line 151 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(151, "intsets.nim");		while (1) {			NI h;
			Trunk199025* n;

#line 349 "c:\\nim\\lib\\system.nim"
			nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
			if (!!((it == NIM_NIL))) goto LA2;

#line 153 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(153, "intsets.nim");
#line 153 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			h = (NI)((*it).key & (*dest).max);			{
#line 154 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
				nimln(154, "intsets.nim");				while (1) {
#line 349 "c:\\nim\\lib\\system.nim"
					nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
					if ((NU)(h) >= (NU)((*dest).data->Sup.len)) raiseIndexError();					if (!!(((*dest).data->data[h] == NIM_NIL))) goto LA4;

#line 154 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
					nimln(154, "intsets.nim");					h = nexttry_199201(h, (*dest).max);				} LA4: ;			}

#line 155 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(155, "intsets.nim");			{
#line 155 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 155 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
				if ((NU)(h) >= (NU)((*dest).data->Sup.len)) raiseIndexError();				if (!!(((*dest).data->data[h] == NIM_NIL))) goto LA7;

#line 155 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
				failedassertimpl_90316(((NimStringDesc*) &TMP1014));
			}
			LA7: ;
			n = 0;
#line 158 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(158, "intsets.nim");			n = (Trunk199025*) newObj((&NTI199023), sizeof(Trunk199025));
#line 159 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(159, "intsets.nim");			asgnRef((void**) (&(*n).next), (*dest).head);
#line 160 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(160, "intsets.nim");			(*n).key = (*it).key;
#line 161 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(161, "intsets.nim");			memcpy((void*)(*n).bits, (NIM_CONST void*)(*it).bits, sizeof(TY29819));
#line 162 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(162, "intsets.nim");			unsureAsgnRef((void**) (&(*dest).head), n);
#line 163 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(163, "intsets.nim");			if ((NU)(h) >= (NU)((*dest).data->Sup.len)) raiseIndexError();			asgnRef((void**) (&(*dest).data->data[h]), n);
#line 165 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(165, "intsets.nim");			it = (*it).next;		} LA2: ;	}
	popFrame();}


#line 179 "c:\\nim\\lib\\system\\sysstr.nim"
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {

#line 180 "c:\\nim\\lib\\system\\sysstr.nim"

#line 180 "c:\\nim\\lib\\system\\sysstr.nim"
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));

#line 181 "c:\\nim\\lib\\system\\sysstr.nim"
	(*dest).Sup.len += (*src).Sup.len;}


#line 192 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
N_NIMCALL(NimStringDesc*, HEX24_200072)(Intset199029* s) {
	NimStringDesc* result;
	nimfr("$", "intsets.nim")
	result = 0;
#line 186 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(186, "intsets.nim");	result = copyString(((NimStringDesc*) &TMP1015));	{		NI key_200077;
		Trunk199025* r_200083;
		key_200077 = 0;
#line 169 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
		nimln(169, "intsets.nim");		r_200083 = (*s).head;		{
#line 170 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
			nimln(170, "intsets.nim");			while (1) {				NI i_200085;

#line 349 "c:\\nim\\lib\\system.nim"
				nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
				if (!!((r_200083 == NIM_NIL))) goto LA3;

#line 171 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
				nimln(171, "intsets.nim");				i_200085 = ((NI) 0);				{
#line 172 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
					nimln(172, "intsets.nim");					while (1) {						NI w_200087;
						NI j_200089;
						NI TMP1018;
#line 172 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
						if (!(i_200085 <= ((NI) 7))) goto LA5;

#line 173 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
						nimln(173, "intsets.nim");						if ((NU)(i_200085) > (NU)(7)) raiseIndexError();						w_200087 = (*r_200083).bits[(i_200085)- 0];
#line 176 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
						nimln(176, "intsets.nim");						j_200089 = ((NI) 0);						{
#line 177 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
							nimln(177, "intsets.nim");							while (1) {								NI TMP1017;
#line 349 "c:\\nim\\lib\\system.nim"
								nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
								if (!!((w_200087 == ((NI) 0)))) goto LA7;

#line 178 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
								nimln(178, "intsets.nim");								{									NimStringDesc* LOC16;
#line 349 "c:\\nim\\lib\\system.nim"
									nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 178 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
									nimln(178, "intsets.nim");									if (!!((((NI) ((NI)(w_200087 & ((NI) 1)))) == ((NI) 0)))) goto LA10;

#line 179 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
									nimln(179, "intsets.nim");
#line 179 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 179 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 179 "c:\\nim\\lib\\pure\\collections\\intsets.nim"

#line 179 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
									key_200077 = (NI)((NI)((NU64)((*r_200083).key) << (NU64)(((NI) 9))) | (NI)((NU64)((NI)((NU64)(i_200085) << (NU64)(((NI) 6)))) + (NU64)(j_200089)));
#line 188 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
									nimln(188, "intsets.nim");									{
#line 357 "c:\\nim\\lib\\system.nim"
										nimln(357, "system.nim");
#line 188 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
										nimln(188, "intsets.nim");										if (!(((NI) 1) < (result ? result->Sup.len : 0))) goto LA14;

#line 188 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
										result = resizeString(result, 2);appendString(result, ((NimStringDesc*) &TMP1016));									}
									LA14: ;

#line 189 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
									nimln(189, "intsets.nim");
#line 189 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
									LOC16 = 0;									LOC16 = nimIntToStr(key_200077);									result = resizeString(result, LOC16->Sup.len + 0);appendString(result, LOC16);								}
								LA10: ;

#line 180 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
								nimln(180, "intsets.nim");								TMP1017 = addInt(j_200089, ((NI) 1));								j_200089 = (NI)(TMP1017);
#line 181 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
								nimln(181, "intsets.nim");
#line 181 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
								w_200087 = (NI)((NU64)(w_200087) >> (NU64)(((NI) 1)));							} LA7: ;						}

#line 182 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
						nimln(182, "intsets.nim");						TMP1018 = addInt(i_200085, ((NI) 1));						i_200085 = (NI)(TMP1018);					} LA5: ;				}

#line 183 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
				nimln(183, "intsets.nim");				r_200083 = (*r_200083).next;			} LA3: ;		}
	}

#line 190 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(190, "intsets.nim");	result = resizeString(result, 1);appendString(result, ((NimStringDesc*) &TMP1019));	popFrame();	return result;}


#line 196 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
static N_INLINE(NIM_BOOL, empty_200090)(Intset199029* s) {
	NIM_BOOL result;
	nimfr("empty", "intsets.nim")
	result = 0;
#line 200 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	nimln(200, "intsets.nim");
#line 200 "c:\\nim\\lib\\pure\\collections\\intsets.nim"
	result = ((*s).counter == ((NI) 0));	popFrame();	return result;}
NIM_EXTERNC N_NOINLINE(void, stdlib_intsetsInit000)(void) {
	nimfr("intsets", "intsets.nim")
	popFrame();}

NIM_EXTERNC N_NOINLINE(void, stdlib_intsetsDatInit000)(void) {
static TNimNode* TMP1007[3];
static TNimNode TMP982[4];NTI199025.size = sizeof(Trunk199025);
NTI199025.kind = 18;
NTI199025.base = 0;
TMP1007[0] = &TMP982[1];
TMP982[1].kind = 1;
TMP982[1].offset = offsetof(Trunk199025, next);
TMP982[1].typ = (&NTI199023);
TMP982[1].name = "next";
TMP1007[1] = &TMP982[2];
TMP982[2].kind = 1;
TMP982[2].offset = offsetof(Trunk199025, key);
TMP982[2].typ = (&NTI104);
TMP982[2].name = "key";
TMP1007[2] = &TMP982[3];
TMP982[3].kind = 1;
TMP982[3].offset = offsetof(Trunk199025, bits);
TMP982[3].typ = (&NTI29819);
TMP982[3].name = "bits";
TMP982[0].len = 3; TMP982[0].kind = 2; TMP982[0].sons = &TMP1007[0];
NTI199025.node = &TMP982[0];
NTI199023.size = sizeof(Trunk199025*);
NTI199023.kind = 22;
NTI199023.base = (&NTI199025);
NTI199023.marker = TMP1008;
NTI199027.size = sizeof(Trunkseq199027*);
NTI199027.kind = 24;
NTI199027.base = (&NTI199023);
NTI199027.flags = 2;
NTI199027.marker = TMP1009;
}

