/* Generated by Nim Compiler v0.13.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -g3 -O0  -I/home/fedorov_ag/Nim/lib -o /home/fedorov_ag/projects/SimplePaint/src/nimcache/stdlib_streams.o /home/fedorov_ag/projects/SimplePaint/src/nimcache/stdlib_streams.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <setjmp.h>
#include <string.h>
#include <stdio.h>
typedef struct Ioerror3628 Ioerror3628;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Systemerror3626 Systemerror3626;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47905 Cell47905;
typedef struct Cellseq47921 Cellseq47921;
typedef struct Gcheap50218 Gcheap50218;
typedef struct Gcstack50216 Gcstack50216;
typedef struct Cellset47917 Cellset47917;
typedef struct Pagedesc47913 Pagedesc47913;
typedef struct Memregion30088 Memregion30088;
typedef struct Smallchunk30040 Smallchunk30040;
typedef struct Llchunk30082 Llchunk30082;
typedef struct Bigchunk30042 Bigchunk30042;
typedef struct Intset30014 Intset30014;
typedef struct Trunk30010 Trunk30010;
typedef struct Avlnode30086 Avlnode30086;
typedef struct Gcstat50214 Gcstat50214;
typedef struct Streamobj139218 Streamobj139218;
typedef struct TSafePoint TSafePoint;
typedef struct Stringstreamobj140177 Stringstreamobj140177;
typedef struct Filestreamobj140276 Filestreamobj140276;
typedef struct Basechunk30038 Basechunk30038;
typedef struct Freecell30030 Freecell30030;
struct  TGenericSeq  {NI len;
NI reserved;
};
struct  NimStringDesc  {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimObject  {TNimType* m_type;};
struct  Exception  {  TNimObject Sup;Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Systemerror3626  {  Exception Sup;};
struct  Ioerror3628  {  Systemerror3626 Sup;};
struct  TNimNode  {NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell47905  {NI refcount;
TNimType* typ;
};
struct  Cellseq47921  {NI len;
NI cap;
Cell47905** d;
};
struct  Cellset47917  {NI counter;
NI max;
Pagedesc47913* head;
Pagedesc47913** data;
};
typedef Smallchunk30040* TY30103[512];
typedef Trunk30010* Trunkbuckets30012[256];
struct  Intset30014  {Trunkbuckets30012 data;
};
struct  Memregion30088  {NI minlargeobj;
NI maxlargeobj;
TY30103 freesmallchunks;
Llchunk30082* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30042* freechunkslist;
Intset30014 chunkstarts;
Avlnode30086* root;
Avlnode30086* deleted;
Avlnode30086* last;
Avlnode30086* freeavlnodes;
};
struct  Gcstat50214  {NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap50218  {Gcstack50216* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47921 zct;
Cellseq47921 decstack;
Cellset47917 cycleroots;
Cellseq47921 tempstack;
NI recgclock;
Memregion30088 region;
Gcstat50214 stat;
};
typedef N_NIMCALL_PTR(void, TY139219) (Streamobj139218* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY139223) (Streamobj139218* s);
typedef N_NIMCALL_PTR(void, TY139227) (Streamobj139218* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY139232) (Streamobj139218* s);
typedef N_NIMCALL_PTR(NI, TY139236) (Streamobj139218* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(NI, TY139242) (Streamobj139218* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY139248) (Streamobj139218* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY139254) (Streamobj139218* s);
struct  Streamobj139218  {  TNimObject Sup;TY139219 closeimpl;
TY139223 atendimpl;
TY139227 setpositionimpl;
TY139232 getpositionimpl;
TY139236 readdataimpl;
TY139242 peekdataimpl;
TY139248 writedataimpl;
TY139254 flushimpl;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY17811;
struct  TSafePoint  {TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY17811 raiseAction;
};
struct  Stringstreamobj140177  {  Streamobj139218 Sup;NimStringDesc* data;
NI pos;
};
struct  Filestreamobj140276  {  Streamobj139218 Sup;FILE* f;
};
struct  Gcstack50216  {Gcstack50216* prev;
Gcstack50216* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY30019[8];
struct  Pagedesc47913  {Pagedesc47913* next;
NI key;
TY30019 bits;
};
struct  Basechunk30038  {NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30040  {  Basechunk30038 Sup;Smallchunk30040* next;
Smallchunk30040* prev;
Freecell30030* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30082  {NI size;
NI acc;
Llchunk30082* next;
};
struct  Bigchunk30042  {  Basechunk30038 Sup;Bigchunk30042* next;
Bigchunk30042* prev;
NI align;
NF data;
};
struct  Trunk30010  {Trunk30010* next;
NI key;
TY30019 bits;
};
typedef Avlnode30086* TY30093[2];
struct  Avlnode30086  {TY30093 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell30030  {Freecell30030* next;
NI zerofield;
};

#line 37 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(Ioerror3628*, neweio_139202)(NimStringDesc* msg);
#line 471 "/home/fedorov_ag/Nim/lib/system/gc.nim"
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
#line 99 "/home/fedorov_ag/Nim/lib/system/sysstr.nim"
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
#line 244 "/home/fedorov_ag/Nim/lib/system/gc.nim"
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
#line 129 "/home/fedorov_ag/Nim/lib/system/gc.nim"
static N_INLINE(Cell47905*, usrtocell_51840)(void* usr);
#line 303 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 298 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
N_NOINLINE(void, stackoverflow_22201)(void);
#line 49 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void);
#line 208 "/home/fedorov_ag/Nim/lib/system/gc.nim"
static N_INLINE(void, rtladdzct_53401)(Cell47905* c);
#line 120 "/home/fedorov_ag/Nim/lib/system/gc.nim"
N_NOINLINE(void, addzct_51817)(Cellseq47921* s, Cell47905* c);
#line 62 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, flush_139260)(Streamobj139218* s);
#line 66 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, close_139270)(Streamobj139218* s);
#line 70 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, close_139280)(Streamobj139218* s, Streamobj139218* unused);
#line 74 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_BOOL, atend_139284)(Streamobj139218* s);
#line 79 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_BOOL, atend_139288)(Streamobj139218* s, Streamobj139218* unused);
#line 84 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, setposition_139293)(Streamobj139218* s, NI pos);
#line 88 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, setposition_139297)(Streamobj139218* s, Streamobj139218* unused, NI pos);
#line 92 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, getposition_139302)(Streamobj139218* s);
#line 96 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, getposition_139306)(Streamobj139218* s, Streamobj139218* unused);
#line 100 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, readdata_139311)(Streamobj139218* s, void* buffer, NI buflen);
#line 104 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NimStringDesc*, readall_139317)(Streamobj139218* s);
#line 64 "/home/fedorov_ag/Nim/lib/system/sysstr.nim"
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
#line 1175 "/home/fedorov_ag/Nim/lib/system.nim"
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
#line 18 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
N_NOINLINE(void, raiseIndexError)(void);
#line 319 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b);
#line 13 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
N_NOINLINE(void, raiseOverflow)(void);
#line 30 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
#line 12 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
N_NOINLINE(void, raiseRangeError)(NI64 val);
#line 188 "/home/fedorov_ag/Nim/lib/system/sysstr.nim"
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
#line 117 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, readdata_139336)(Streamobj139218* s, Streamobj139218* unused, void* buffer, NI buflen);
#line 122 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, peekdata_139343)(Streamobj139218* s, void* buffer, NI buflen);
#line 127 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, writedata_139349)(Streamobj139218* s, void* buffer, NI buflen);
#line 132 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, writedata_139354)(Streamobj139218* s, Streamobj139218* unused, void* buffer, NI buflen);
#line 148 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, write_139369)(Streamobj139218* s, NimStringDesc* x);
#line 156 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, writeln_139601)(Streamobj139218* s, NimStringDesc** args, NI argsLen0);
#line 161 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, writeline_139618)(Streamobj139218* s, NimStringDesc** args, NI argsLen0);
#line 177 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_CHAR, readchar_139654)(Streamobj139218* s);
#line 182 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_CHAR, peekchar_139659)(Streamobj139218* s);
#line 167 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, read_139669)(Streamobj139218* s, NIM_BOOL* result);
#line 263 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
#line 187 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_BOOL, readbool_139664)(Streamobj139218* s);
#line 172 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, peek_139702)(Streamobj139218* s, NIM_BOOL* result);
#line 191 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_BOOL, peekbool_139697)(Streamobj139218* s);
#line 167 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, read_139735)(Streamobj139218* s, NI8* result);
#line 195 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI8, readint8_139730)(Streamobj139218* s);
#line 172 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, peek_139768)(Streamobj139218* s, NI8* result);
#line 199 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI8, peekint8_139763)(Streamobj139218* s);
#line 167 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, read_139801)(Streamobj139218* s, NI16* result);
#line 203 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI16, readint16_139796)(Streamobj139218* s);
#line 172 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, peek_139834)(Streamobj139218* s, NI16* result);
#line 207 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI16, peekint16_139829)(Streamobj139218* s);
#line 167 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, read_139867)(Streamobj139218* s, NI32* result);
#line 211 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI32, readint32_139862)(Streamobj139218* s);
#line 172 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, peek_139900)(Streamobj139218* s, NI32* result);
#line 215 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI32, peekint32_139895)(Streamobj139218* s);
#line 167 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, read_139933)(Streamobj139218* s, NI64* result);
#line 219 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI64, readint64_139928)(Streamobj139218* s);
#line 172 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, peek_139966)(Streamobj139218* s, NI64* result);
#line 223 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI64, peekint64_139961)(Streamobj139218* s);
#line 167 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, read_139999)(Streamobj139218* s, NF32* result);
#line 227 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NF32, readfloat32_139994)(Streamobj139218* s);
#line 172 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, peek_140032)(Streamobj139218* s, NF32* result);
#line 231 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NF32, peekfloat32_140027)(Streamobj139218* s);
#line 167 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, read_140065)(Streamobj139218* s, NF* result);
#line 235 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NF, readfloat64_140060)(Streamobj139218* s);
#line 172 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, peek_140098)(Streamobj139218* s, NF* result);
#line 239 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NF, peekfloat64_140093)(Streamobj139218* s);
#line 243 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NimStringDesc*, readstr_140126)(Streamobj139218* s, NI length);
#line 250 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NimStringDesc*, peekstr_140135)(Streamobj139218* s, NI length);
#line 257 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_BOOL, readline_140144)(Streamobj139218* s, NimStringDesc** line);
#line 126 "/home/fedorov_ag/Nim/lib/system/sysstr.nim"
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
#line 277 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_BOOL, peekline_140154)(Streamobj139218* s, NimStringDesc** line);
#line 55 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
#line 60 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, popSafePoint)(void);
#line 52 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, setFrame)(TFrame* s);
#line 270 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
N_NIMCALL(void, reraiseException)(void);
#line 288 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NimStringDesc*, readline_140161)(Streamobj139218* s);
#line 90 "/home/fedorov_ag/Nim/lib/system/sysstr.nim"
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
#line 302 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NimStringDesc*, peekline_140169)(Streamobj139218* s);
#line 317 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_BOOL, ssatend_140182)(Streamobj139218* s_140184);
#line 56 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
#line 1953 "/home/fedorov_ag/Nim/lib/system.nim"
N_NIMCALL(NI, clamp_140193)(NI x, NI a, NI b);
#line 321 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, sssetposition_140187)(Streamobj139218* s_140189, NI pos);
#line 325 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, ssgetposition_140203)(Streamobj139218* s_140205);
#line 329 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, ssreaddata_140208)(Streamobj139218* s_140210, void* buffer, NI buflen);
#line 326 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b);
#line 336 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, sspeekdata_140229)(Streamobj139218* s_140231, void* buffer, NI buflen);
#line 342 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, sswritedata_140241)(Streamobj139218* s_140243, void* buffer, NI buflen);
#line 351 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, ssclose_140257)(Streamobj139218* s_140259);
#line 355 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(Stringstreamobj140177*, newstringstream_140261)(NimStringDesc* s);
#line 738 "/home/fedorov_ag/Nim/lib/system/gc.nim"
N_NIMCALL(void, nimGCvisit)(void* d, NI op);N_NIMCALL(void, TMP617)(void* p, NI op);

#line 376 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, fsclose_140280)(Streamobj139218* s);
#line 380 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, fsflush_140295)(Streamobj139218* s);
#line 381 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_BOOL, fsatend_140298)(Streamobj139218* s);
#line 205 "/home/fedorov_ag/Nim/lib/system/sysio.nim"
N_NIMCALL(NIM_BOOL, endoffile_15454)(FILE* f);
#line 382 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, fssetposition_140302)(Streamobj139218* s, NI pos);
#line 314 "/home/fedorov_ag/Nim/lib/system/sysio.nim"
N_NIMCALL(void, setfilepos_15581)(FILE* f, NI64 pos);
#line 383 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, fsgetposition_140306)(Streamobj139218* s);
#line 318 "/home/fedorov_ag/Nim/lib/system/sysio.nim"
N_NIMCALL(NI64, getfilepos_15585)(FILE* f);
#line 385 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, fsreaddata_140311)(Streamobj139218* s, void* buffer, NI buflen);
#line 290 "/home/fedorov_ag/Nim/lib/system/sysio.nim"
N_NIMCALL(NI, readbuffer_15554)(FILE* f, void* buffer, NI len);
#line 388 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, fspeekdata_140317)(Streamobj139218* s, void* buffer, NI buflen);
#line 393 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, fswritedata_140324)(Streamobj139218* s, void* buffer, NI buflen);
#line 306 "/home/fedorov_ag/Nim/lib/system/sysio.nim"
N_NIMCALL(NI, writebuffer_15576)(FILE* f, void* buffer, NI len);
#line 397 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(Filestreamobj140276*, newfilestream_140329)(FILE* f);N_NIMCALL(void, TMP620)(void* p, NI op);

#line 410 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(Filestreamobj140276*, newfilestream_140341)(NimStringDesc* filename, NU8 mode);
#line 264 "/home/fedorov_ag/Nim/lib/system/sysio.nim"
N_NIMCALL(NIM_BOOL, open_15403)(FILE** f, NimStringDesc* filename, NU8 mode, NI bufsize);N_NIMCALL(void, TMP958)(void* p, NI op);
STRING_LITERAL(TMP603, "\012", 1);
STRING_LITERAL(TMP605, "cannot read from stream", 23);
STRING_LITERAL(TMP607, "", 0);
STRING_LITERAL(TMP619, "cannot write to stream", 22);
extern TNimType NTI15435; /* ref IOError */
extern TNimType NTI3628; /* IOError */
extern TFrame* frameptr_19436;
extern Gcheap50218 gch_50259;
extern TSafePoint* exchandler_19437;
extern TNimType NTI3608; /* RootObj */
TNimType NTI139218; /* StreamObj */
TNimType NTI139219; /* proc (s: Stream){.gcsafe.} */
TNimType NTI139223; /* proc (s: Stream): bool{.gcsafe.} */
TNimType NTI139227; /* proc (s: Stream, pos: int){.gcsafe.} */
TNimType NTI139232; /* proc (s: Stream): int{.gcsafe.} */
TNimType NTI139236; /* proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe.} */
TNimType NTI139242; /* proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe.} */
TNimType NTI139248; /* proc (s: Stream, buffer: pointer, bufLen: int){.gcsafe.} */
TNimType NTI139254; /* proc (s: Stream){.gcsafe.} */
TNimType NTI140177; /* StringStreamObj */
extern TNimType NTI138; /* string */
extern TNimType NTI104; /* int */
TNimType NTI140175; /* StringStream */
TNimType NTI140276; /* FileStreamObj */
extern TNimType NTI15004; /* File */
TNimType NTI140274; /* FileStream */
TNimType NTI139216; /* Stream */


#line 303 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	LOC1 = 0;
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	{
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);	}
	goto LA2;
	LA4: ;
	{
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
#line 305 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	(*s).prev = frameptr_19436;
#line 306 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	frameptr_19436 = s;
#line 307 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	{
#line 307 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;

#line 307 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		stackoverflow_22201();
	}
	LA9: ;
}


#line 49 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 50 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	frameptr_19436 = (*frameptr_19436).prev;}


#line 129 "/home/fedorov_ag/Nim/lib/system/gc.nim"
static N_INLINE(Cell47905*, usrtocell_51840)(void* usr) {
	Cell47905* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
#line 131 "/home/fedorov_ag/Nim/lib/system/gc.nim"
	nimln(131, "gc.nim");
#line 131 "/home/fedorov_ag/Nim/lib/system/gc.nim"

#line 131 "/home/fedorov_ag/Nim/lib/system/gc.nim"
	result = ((Cell47905*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47905))))));	popFrame();	return result;}


#line 208 "/home/fedorov_ag/Nim/lib/system/gc.nim"
static N_INLINE(void, rtladdzct_53401)(Cell47905* c) {
	nimfr("rtlAddZCT", "gc.nim")

#line 212 "/home/fedorov_ag/Nim/lib/system/gc.nim"
	nimln(212, "gc.nim");	addzct_51817((&gch_50259.zct), c);
	popFrame();}


#line 244 "/home/fedorov_ag/Nim/lib/system/gc.nim"
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell47905* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")

#line 246 "/home/fedorov_ag/Nim/lib/system/gc.nim"
	nimln(246, "gc.nim");	c = usrtocell_51840(p);
#line 248 "/home/fedorov_ag/Nim/lib/system/gc.nim"
	nimln(248, "gc.nim");	{
#line 180 "/home/fedorov_ag/Nim/lib/system/gc.nim"
		nimln(180, "gc.nim");		(*c).refcount -= ((NI) 8);
#line 181 "/home/fedorov_ag/Nim/lib/system/gc.nim"
		nimln(181, "gc.nim");		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;

#line 249 "/home/fedorov_ag/Nim/lib/system/gc.nim"
		nimln(249, "gc.nim");		rtladdzct_53401(c);
	}
	LA3: ;
	popFrame();}


#line 37 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(Ioerror3628*, neweio_139202)(NimStringDesc* msg) {
	Ioerror3628* result;
	NimStringDesc* LOC1;	nimfr("newEIO", "streams.nim")
	result = 0;
#line 38 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(38, "streams.nim");	result = (Ioerror3628*) newObj((&NTI15435), sizeof(Ioerror3628));	(*result).Sup.Sup.Sup.m_type = (&NTI3628);
#line 39 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(39, "streams.nim");	LOC1 = 0;	LOC1 = (*result).Sup.Sup.message; (*result).Sup.Sup.message = copyStringRC1(msg);	if (LOC1) nimGCunrefNoCycle(LOC1);	popFrame();	return result;}


#line 62 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, flush_139260)(Streamobj139218* s) {
	nimfr("flush", "streams.nim")

#line 64 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(64, "streams.nim");	{
#line 64 "/home/fedorov_ag/Nim/lib/pure/streams.nim"

#line 64 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		if (!!((*s).flushimpl == 0)) goto LA3;

#line 64 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		(*s).flushimpl(s);
	}
	LA3: ;
	popFrame();}


#line 66 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, close_139270)(Streamobj139218* s) {
	nimfr("close", "streams.nim")

#line 68 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(68, "streams.nim");	{
#line 68 "/home/fedorov_ag/Nim/lib/pure/streams.nim"

#line 68 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		if (!!((*s).closeimpl == 0)) goto LA3;

#line 68 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		(*s).closeimpl(s);
	}
	LA3: ;
	popFrame();}


#line 70 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, close_139280)(Streamobj139218* s, Streamobj139218* unused) {
	nimfr("close", "streams.nim")

#line 72 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(72, "streams.nim");	(*s).closeimpl(s);
	popFrame();}


#line 74 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_BOOL, atend_139284)(Streamobj139218* s) {
	NIM_BOOL result;
	nimfr("atEnd", "streams.nim")
	result = 0;
#line 77 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(77, "streams.nim");	result = (*s).atendimpl(s);	popFrame();	return result;}


#line 79 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_BOOL, atend_139288)(Streamobj139218* s, Streamobj139218* unused) {
	NIM_BOOL result;
	nimfr("atEnd", "streams.nim")
	result = 0;
#line 82 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(82, "streams.nim");	result = (*s).atendimpl(s);	popFrame();	return result;}


#line 84 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, setposition_139293)(Streamobj139218* s, NI pos) {
	nimfr("setPosition", "streams.nim")

#line 86 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(86, "streams.nim");	(*s).setpositionimpl(s, pos);
	popFrame();}


#line 88 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, setposition_139297)(Streamobj139218* s, Streamobj139218* unused, NI pos) {
	nimfr("setPosition", "streams.nim")

#line 90 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(90, "streams.nim");	(*s).setpositionimpl(s, pos);
	popFrame();}


#line 92 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, getposition_139302)(Streamobj139218* s) {
	NI result;
	nimfr("getPosition", "streams.nim")
	result = 0;
#line 94 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(94, "streams.nim");	result = (*s).getpositionimpl(s);	popFrame();	return result;}


#line 96 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, getposition_139306)(Streamobj139218* s, Streamobj139218* unused) {
	NI result;
	nimfr("getPosition", "streams.nim")
	result = 0;
#line 98 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(98, "streams.nim");	result = (*s).getpositionimpl(s);	popFrame();	return result;}


#line 100 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, readdata_139311)(Streamobj139218* s, void* buffer, NI buflen) {
	NI result;
	nimfr("readData", "streams.nim")
	result = 0;
#line 102 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(102, "streams.nim");	result = (*s).readdataimpl(s, buffer, buflen);	popFrame();	return result;}


#line 319 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 320 "/home/fedorov_ag/Nim/lib/system/arithm.nim"

#line 320 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	result = (NI)((NU64)(a) + (NU64)(b));
#line 321 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	{		NIM_BOOL LOC3;
#line 321 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = 0;
#line 353 "/home/fedorov_ag/Nim/lib/system.nim"

#line 321 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ a));		if (LOC3) goto LA4;

#line 353 "/home/fedorov_ag/Nim/lib/system.nim"

#line 321 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ b));		LA4: ;
		if (!LOC3) goto LA5;

#line 322 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 323 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 30 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
#line 31 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
	{		NIM_BOOL LOC3;
#line 31 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
		LOC3 = 0;
#line 353 "/home/fedorov_ag/Nim/lib/system.nim"
		LOC3 = (a <= i);		if (!(LOC3)) goto LA4;

#line 31 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
		LOC3 = (i <= b);		LA4: ;
		if (!LOC3) goto LA5;

#line 32 "/home/fedorov_ag/Nim/lib/system/chcks.nim"

#line 32 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
		result = i;		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
#line 34 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;}


#line 104 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NimStringDesc*, readall_139317)(Streamobj139218* s) {
	NimStringDesc* result;
	NI r;
	nimfr("readAll", "streams.nim")
	result = 0;
#line 107 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(107, "streams.nim");
#line 107 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	result = mnewString(((NI) 1000));
#line 108 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(108, "streams.nim");	r = ((NI) 0);	{
#line 109 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(109, "streams.nim");		while (1) {			NI readbytes;
			NI TMP600;			NI TMP601;
#line 110 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
			nimln(110, "streams.nim");			if ((NU)(r) > (NU)(result->Sup.len)) raiseIndexError();			readbytes = readdata_139311(s, ((void*) ((&result->data[r]))), ((NI) 1000));
#line 111 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
			nimln(111, "streams.nim");			{				NI TMP599;
#line 111 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				if (!(readbytes < ((NI) 1000))) goto LA5;

#line 112 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				nimln(112, "streams.nim");
#line 112 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				TMP599 = addInt(r, readbytes);				result = setLengthStr(result, ((NI)chckRange((NI)(TMP599), ((NI) 0), ((NI) IL64(9223372036854775807)))));
#line 113 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				nimln(113, "streams.nim");				goto LA1;
			}
			LA5: ;

#line 114 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
			nimln(114, "streams.nim");			TMP600 = addInt(r, ((NI) 1000));			r = (NI)(TMP600);
#line 115 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
			nimln(115, "streams.nim");
#line 115 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
			TMP601 = addInt(r, ((NI) 1000));			result = setLengthStr(result, ((NI)chckRange((NI)(TMP601), ((NI) 0), ((NI) IL64(9223372036854775807)))));		}
	} LA1: ;	popFrame();	return result;}


#line 117 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, readdata_139336)(Streamobj139218* s, Streamobj139218* unused, void* buffer, NI buflen) {
	NI result;
	nimfr("readData", "streams.nim")
	result = 0;
#line 120 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(120, "streams.nim");	result = (*s).readdataimpl(s, buffer, buflen);	popFrame();	return result;}


#line 122 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, peekdata_139343)(Streamobj139218* s, void* buffer, NI buflen) {
	NI result;
	nimfr("peekData", "streams.nim")
	result = 0;
#line 125 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(125, "streams.nim");	result = (*s).peekdataimpl(s, buffer, buflen);	popFrame();	return result;}


#line 127 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, writedata_139349)(Streamobj139218* s, void* buffer, NI buflen) {
	nimfr("writeData", "streams.nim")

#line 130 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(130, "streams.nim");	(*s).writedataimpl(s, buffer, buflen);
	popFrame();}


#line 132 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, writedata_139354)(Streamobj139218* s, Streamobj139218* unused, void* buffer, NI buflen) {
	nimfr("writeData", "streams.nim")

#line 136 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(136, "streams.nim");	(*s).writedataimpl(s, buffer, buflen);
	popFrame();}


#line 148 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, write_139369)(Streamobj139218* s, NimStringDesc* x) {
	nimfr("write", "streams.nim")

#line 154 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(154, "streams.nim");	{
#line 357 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(357, "system.nim");
#line 154 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(154, "streams.nim");		if (!(((NI) 0) < (x ? x->Sup.len : 0))) goto LA3;

#line 154 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		if ((NU)(((NI) 0)) > (NU)(x->Sup.len)) raiseIndexError();
#line 154 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		writedata_139349(s, ((void*) ((&x->data[((NI) 0)]))), (x ? x->Sup.len : 0));
	}
	LA3: ;
	popFrame();}


#line 156 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, writeln_139601)(Streamobj139218* s, NimStringDesc** args, NI argsLen0) {
	nimfr("writeLn", "streams.nim")
	{		NimStringDesc* str_139613;
		NI i_139617;
		str_139613 = 0;
#line 1965 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(1965, "system.nim");		i_139617 = ((NI) 0);		{
#line 1966 "/home/fedorov_ag/Nim/lib/system.nim"
			nimln(1966, "system.nim");			while (1) {				NI TMP602;
#line 1966 "/home/fedorov_ag/Nim/lib/system.nim"

#line 1966 "/home/fedorov_ag/Nim/lib/system.nim"
				if (!(i_139617 < argsLen0)) goto LA3;

#line 1967 "/home/fedorov_ag/Nim/lib/system.nim"
				nimln(1967, "system.nim");				if ((NU)(i_139617) >= (NU)(argsLen0)) raiseIndexError();				str_139613 = args[i_139617];
#line 158 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				nimln(158, "streams.nim");				write_139369(s, str_139613);

#line 1968 "/home/fedorov_ag/Nim/lib/system.nim"
				nimln(1968, "system.nim");				TMP602 = addInt(i_139617, ((NI) 1));				i_139617 = (NI)(TMP602);			} LA3: ;		}
	}

#line 159 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(159, "streams.nim");	write_139369(s, ((NimStringDesc*) &TMP603));
	popFrame();}


#line 161 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, writeline_139618)(Streamobj139218* s, NimStringDesc** args, NI argsLen0) {
	nimfr("writeLine", "streams.nim")
	{		NimStringDesc* str_139630;
		NI i_139634;
		str_139630 = 0;
#line 1965 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(1965, "system.nim");		i_139634 = ((NI) 0);		{
#line 1966 "/home/fedorov_ag/Nim/lib/system.nim"
			nimln(1966, "system.nim");			while (1) {				NI TMP604;
#line 1966 "/home/fedorov_ag/Nim/lib/system.nim"

#line 1966 "/home/fedorov_ag/Nim/lib/system.nim"
				if (!(i_139634 < argsLen0)) goto LA3;

#line 1967 "/home/fedorov_ag/Nim/lib/system.nim"
				nimln(1967, "system.nim");				if ((NU)(i_139634) >= (NU)(argsLen0)) raiseIndexError();				str_139630 = args[i_139634];
#line 164 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				nimln(164, "streams.nim");				write_139369(s, str_139630);

#line 1968 "/home/fedorov_ag/Nim/lib/system.nim"
				nimln(1968, "system.nim");				TMP604 = addInt(i_139634, ((NI) 1));				i_139634 = (NI)(TMP604);			} LA3: ;		}
	}

#line 165 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(165, "streams.nim");	write_139369(s, ((NimStringDesc*) &TMP603));
	popFrame();}


#line 177 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_CHAR, readchar_139654)(Streamobj139218* s) {
	NIM_CHAR result;
	nimfr("readChar", "streams.nim")
	result = 0;
#line 180 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(180, "streams.nim");	{		NI LOC3;
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"

#line 180 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(180, "streams.nim");		LOC3 = 0;		LOC3 = readdata_139311(s, ((void*) ((&result))), ((NI) 1));		if (!!((LOC3 == ((NI) 1)))) goto LA4;

#line 180 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		result = 0;	}
	LA4: ;
	popFrame();	return result;}


#line 182 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_CHAR, peekchar_139659)(Streamobj139218* s) {
	NIM_CHAR result;
	nimfr("peekChar", "streams.nim")
	result = 0;
#line 185 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(185, "streams.nim");	{		NI LOC3;
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"

#line 185 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(185, "streams.nim");		LOC3 = 0;		LOC3 = peekdata_139343(s, ((void*) ((&result))), ((NI) 1));		if (!!((LOC3 == ((NI) 1)))) goto LA4;

#line 185 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		result = 0;	}
	LA4: ;
	popFrame();	return result;}


#line 167 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, read_139669)(Streamobj139218* s, NIM_BOOL* result) {
	nimfr("read", "streams.nim")

#line 169 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(169, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"

#line 169 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(169, "streams.nim");		LOC3 = 0;		LOC3 = readdata_139311(s, ((void*) (result)), ((NI) 1));		if (!!((LOC3 == ((NI) 1)))) goto LA4;

#line 170 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(170, "streams.nim");		LOC6 = 0;		LOC6 = neweio_139202(((NimStringDesc*) &TMP605));
#line 170 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 187 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_BOOL, readbool_139664)(Streamobj139218* s) {
	NIM_BOOL result;
	nimfr("readBool", "streams.nim")
	result = 0;
#line 189 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(189, "streams.nim");	read_139669(s, (&result));
	popFrame();	return result;}


#line 172 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, peek_139702)(Streamobj139218* s, NIM_BOOL* result) {
	nimfr("peek", "streams.nim")

#line 174 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(174, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"

#line 174 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(174, "streams.nim");		LOC3 = 0;		LOC3 = peekdata_139343(s, ((void*) (result)), ((NI) 1));		if (!!((LOC3 == ((NI) 1)))) goto LA4;

#line 175 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(175, "streams.nim");		LOC6 = 0;		LOC6 = neweio_139202(((NimStringDesc*) &TMP605));
#line 175 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 191 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_BOOL, peekbool_139697)(Streamobj139218* s) {
	NIM_BOOL result;
	nimfr("peekBool", "streams.nim")
	result = 0;
#line 193 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(193, "streams.nim");	peek_139702(s, (&result));
	popFrame();	return result;}


#line 167 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, read_139735)(Streamobj139218* s, NI8* result) {
	nimfr("read", "streams.nim")

#line 169 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(169, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"

#line 169 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(169, "streams.nim");		LOC3 = 0;		LOC3 = readdata_139311(s, ((void*) (result)), ((NI) 1));		if (!!((LOC3 == ((NI) 1)))) goto LA4;

#line 170 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(170, "streams.nim");		LOC6 = 0;		LOC6 = neweio_139202(((NimStringDesc*) &TMP605));
#line 170 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 195 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI8, readint8_139730)(Streamobj139218* s) {
	NI8 result;
	nimfr("readInt8", "streams.nim")
	result = 0;
#line 197 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(197, "streams.nim");	read_139735(s, (&result));
	popFrame();	return result;}


#line 172 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, peek_139768)(Streamobj139218* s, NI8* result) {
	nimfr("peek", "streams.nim")

#line 174 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(174, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"

#line 174 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(174, "streams.nim");		LOC3 = 0;		LOC3 = peekdata_139343(s, ((void*) (result)), ((NI) 1));		if (!!((LOC3 == ((NI) 1)))) goto LA4;

#line 175 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(175, "streams.nim");		LOC6 = 0;		LOC6 = neweio_139202(((NimStringDesc*) &TMP605));
#line 175 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 199 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI8, peekint8_139763)(Streamobj139218* s) {
	NI8 result;
	nimfr("peekInt8", "streams.nim")
	result = 0;
#line 201 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(201, "streams.nim");	peek_139768(s, (&result));
	popFrame();	return result;}


#line 167 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, read_139801)(Streamobj139218* s, NI16* result) {
	nimfr("read", "streams.nim")

#line 169 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(169, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"

#line 169 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(169, "streams.nim");		LOC3 = 0;		LOC3 = readdata_139311(s, ((void*) (result)), ((NI) 2));		if (!!((LOC3 == ((NI) 2)))) goto LA4;

#line 170 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(170, "streams.nim");		LOC6 = 0;		LOC6 = neweio_139202(((NimStringDesc*) &TMP605));
#line 170 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 203 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI16, readint16_139796)(Streamobj139218* s) {
	NI16 result;
	nimfr("readInt16", "streams.nim")
	result = 0;
#line 205 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(205, "streams.nim");	read_139801(s, (&result));
	popFrame();	return result;}


#line 172 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, peek_139834)(Streamobj139218* s, NI16* result) {
	nimfr("peek", "streams.nim")

#line 174 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(174, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"

#line 174 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(174, "streams.nim");		LOC3 = 0;		LOC3 = peekdata_139343(s, ((void*) (result)), ((NI) 2));		if (!!((LOC3 == ((NI) 2)))) goto LA4;

#line 175 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(175, "streams.nim");		LOC6 = 0;		LOC6 = neweio_139202(((NimStringDesc*) &TMP605));
#line 175 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 207 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI16, peekint16_139829)(Streamobj139218* s) {
	NI16 result;
	nimfr("peekInt16", "streams.nim")
	result = 0;
#line 209 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(209, "streams.nim");	peek_139834(s, (&result));
	popFrame();	return result;}


#line 167 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, read_139867)(Streamobj139218* s, NI32* result) {
	nimfr("read", "streams.nim")

#line 169 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(169, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"

#line 169 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(169, "streams.nim");		LOC3 = 0;		LOC3 = readdata_139311(s, ((void*) (result)), ((NI) 4));		if (!!((LOC3 == ((NI) 4)))) goto LA4;

#line 170 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(170, "streams.nim");		LOC6 = 0;		LOC6 = neweio_139202(((NimStringDesc*) &TMP605));
#line 170 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 211 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI32, readint32_139862)(Streamobj139218* s) {
	NI32 result;
	nimfr("readInt32", "streams.nim")
	result = 0;
#line 213 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(213, "streams.nim");	read_139867(s, (&result));
	popFrame();	return result;}


#line 172 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, peek_139900)(Streamobj139218* s, NI32* result) {
	nimfr("peek", "streams.nim")

#line 174 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(174, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"

#line 174 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(174, "streams.nim");		LOC3 = 0;		LOC3 = peekdata_139343(s, ((void*) (result)), ((NI) 4));		if (!!((LOC3 == ((NI) 4)))) goto LA4;

#line 175 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(175, "streams.nim");		LOC6 = 0;		LOC6 = neweio_139202(((NimStringDesc*) &TMP605));
#line 175 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 215 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI32, peekint32_139895)(Streamobj139218* s) {
	NI32 result;
	nimfr("peekInt32", "streams.nim")
	result = 0;
#line 217 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(217, "streams.nim");	peek_139900(s, (&result));
	popFrame();	return result;}


#line 167 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, read_139933)(Streamobj139218* s, NI64* result) {
	nimfr("read", "streams.nim")

#line 169 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(169, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"

#line 169 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(169, "streams.nim");		LOC3 = 0;		LOC3 = readdata_139311(s, ((void*) (result)), ((NI) 8));		if (!!((LOC3 == ((NI) 8)))) goto LA4;

#line 170 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(170, "streams.nim");		LOC6 = 0;		LOC6 = neweio_139202(((NimStringDesc*) &TMP605));
#line 170 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 219 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI64, readint64_139928)(Streamobj139218* s) {
	NI64 result;
	nimfr("readInt64", "streams.nim")
	result = 0;
#line 221 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(221, "streams.nim");	read_139933(s, (&result));
	popFrame();	return result;}


#line 172 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, peek_139966)(Streamobj139218* s, NI64* result) {
	nimfr("peek", "streams.nim")

#line 174 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(174, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"

#line 174 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(174, "streams.nim");		LOC3 = 0;		LOC3 = peekdata_139343(s, ((void*) (result)), ((NI) 8));		if (!!((LOC3 == ((NI) 8)))) goto LA4;

#line 175 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(175, "streams.nim");		LOC6 = 0;		LOC6 = neweio_139202(((NimStringDesc*) &TMP605));
#line 175 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 223 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI64, peekint64_139961)(Streamobj139218* s) {
	NI64 result;
	nimfr("peekInt64", "streams.nim")
	result = 0;
#line 225 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(225, "streams.nim");	peek_139966(s, (&result));
	popFrame();	return result;}


#line 167 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, read_139999)(Streamobj139218* s, NF32* result) {
	nimfr("read", "streams.nim")

#line 169 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(169, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"

#line 169 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(169, "streams.nim");		LOC3 = 0;		LOC3 = readdata_139311(s, ((void*) (result)), ((NI) 4));		if (!!((LOC3 == ((NI) 4)))) goto LA4;

#line 170 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(170, "streams.nim");		LOC6 = 0;		LOC6 = neweio_139202(((NimStringDesc*) &TMP605));
#line 170 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 227 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NF32, readfloat32_139994)(Streamobj139218* s) {
	NF32 result;
	nimfr("readFloat32", "streams.nim")
	result = 0;
#line 229 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(229, "streams.nim");	read_139999(s, (&result));
	popFrame();	return result;}


#line 172 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, peek_140032)(Streamobj139218* s, NF32* result) {
	nimfr("peek", "streams.nim")

#line 174 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(174, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"

#line 174 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(174, "streams.nim");		LOC3 = 0;		LOC3 = peekdata_139343(s, ((void*) (result)), ((NI) 4));		if (!!((LOC3 == ((NI) 4)))) goto LA4;

#line 175 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(175, "streams.nim");		LOC6 = 0;		LOC6 = neweio_139202(((NimStringDesc*) &TMP605));
#line 175 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 231 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NF32, peekfloat32_140027)(Streamobj139218* s) {
	NF32 result;
	nimfr("peekFloat32", "streams.nim")
	result = 0;
#line 233 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(233, "streams.nim");	peek_140032(s, (&result));
	popFrame();	return result;}


#line 167 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, read_140065)(Streamobj139218* s, NF* result) {
	nimfr("read", "streams.nim")

#line 169 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(169, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"

#line 169 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(169, "streams.nim");		LOC3 = 0;		LOC3 = readdata_139311(s, ((void*) (result)), ((NI) 8));		if (!!((LOC3 == ((NI) 8)))) goto LA4;

#line 170 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(170, "streams.nim");		LOC6 = 0;		LOC6 = neweio_139202(((NimStringDesc*) &TMP605));
#line 170 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 235 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NF, readfloat64_140060)(Streamobj139218* s) {
	NF result;
	nimfr("readFloat64", "streams.nim")
	result = 0;
#line 237 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(237, "streams.nim");	read_140065(s, (&result));
	popFrame();	return result;}


#line 172 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, peek_140098)(Streamobj139218* s, NF* result) {
	nimfr("peek", "streams.nim")

#line 174 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(174, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"

#line 174 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(174, "streams.nim");		LOC3 = 0;		LOC3 = peekdata_139343(s, ((void*) (result)), ((NI) 8));		if (!!((LOC3 == ((NI) 8)))) goto LA4;

#line 175 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(175, "streams.nim");		LOC6 = 0;		LOC6 = neweio_139202(((NimStringDesc*) &TMP605));
#line 175 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 239 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NF, peekfloat64_140093)(Streamobj139218* s) {
	NF result;
	nimfr("peekFloat64", "streams.nim")
	result = 0;
#line 241 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(241, "streams.nim");	peek_140098(s, (&result));
	popFrame();	return result;}


#line 243 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NimStringDesc*, readstr_140126)(Streamobj139218* s, NI length) {
	NimStringDesc* result;
	NI L;
	nimfr("readStr", "streams.nim")
	result = 0;
#line 246 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(246, "streams.nim");
#line 246 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	result = mnewString(((NI)chckRange(length, ((NI) 0), ((NI) IL64(9223372036854775807)))));
#line 247 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(247, "streams.nim");	if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();	L = readdata_139311(s, ((void*) ((&result->data[((NI) 0)]))), length);
#line 248 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(248, "streams.nim");	{
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		if (!!((L == length))) goto LA3;

#line 248 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(248, "streams.nim");		result = setLengthStr(result, ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));	}
	LA3: ;
	popFrame();	return result;}


#line 250 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NimStringDesc*, peekstr_140135)(Streamobj139218* s, NI length) {
	NimStringDesc* result;
	NI L;
	nimfr("peekStr", "streams.nim")
	result = 0;
#line 253 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(253, "streams.nim");
#line 253 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	result = mnewString(((NI)chckRange(length, ((NI) 0), ((NI) IL64(9223372036854775807)))));
#line 254 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(254, "streams.nim");	if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();	L = peekdata_139343(s, ((void*) ((&result->data[((NI) 0)]))), length);
#line 255 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(255, "streams.nim");	{
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		if (!!((L == length))) goto LA3;

#line 255 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(255, "streams.nim");		result = setLengthStr(result, ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));	}
	LA3: ;
	popFrame();	return result;}


#line 257 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_BOOL, readline_140144)(Streamobj139218* s, NimStringDesc** line) {
	NIM_BOOL result;
	nimfr("readLine", "streams.nim")
{	result = 0;
#line 264 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(264, "streams.nim");	(*line) = setLengthStr((*line), ((NI) 0));	{
#line 265 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(265, "streams.nim");		while (1) {			NIM_CHAR c;

#line 266 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
			nimln(266, "streams.nim");			c = readchar_139654(s);
#line 267 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
			nimln(267, "streams.nim");			{
#line 267 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				if (!((NU8)(c) == (NU8)(13))) goto LA5;

#line 268 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				nimln(268, "streams.nim");				c = readchar_139654(s);
#line 269 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				nimln(269, "streams.nim");				goto LA1;
			}
			goto LA3;
			LA5: ;
			{
#line 270 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				nimln(270, "streams.nim");				if (!((NU8)(c) == (NU8)(10))) goto LA8;

#line 270 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				goto LA1;
			}
			goto LA3;
			LA8: ;
			{
#line 271 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				nimln(271, "streams.nim");				if (!((NU8)(c) == (NU8)(0))) goto LA11;

#line 272 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				nimln(272, "streams.nim");				{
#line 357 "/home/fedorov_ag/Nim/lib/system.nim"
					nimln(357, "system.nim");
#line 272 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
					nimln(272, "streams.nim");					if (!(((NI) 0) < ((*line) ? (*line)->Sup.len : 0))) goto LA15;

#line 272 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
					goto LA1;
				}
				goto LA13;
				LA15: ;
				{
#line 273 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
					nimln(273, "streams.nim");
#line 273 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
					result = NIM_FALSE;					goto BeforeRet;
				}
				LA13: ;
			}
			goto LA3;
			LA11: ;
			LA3: ;

#line 274 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
			nimln(274, "streams.nim");			(*line) = addChar((*line), c);		}
	} LA1: ;
#line 275 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(275, "streams.nim");	result = NIM_TRUE;	}BeforeRet: ;
	popFrame();	return result;}


#line 55 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, pushSafePoint)(TSafePoint* s) {

#line 56 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	(*s).hasRaiseAction = NIM_FALSE;
#line 57 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	(*s).prev = exchandler_19437;
#line 58 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	exchandler_19437 = s;}


#line 60 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, popSafePoint)(void) {

#line 61 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	exchandler_19437 = (*exchandler_19437).prev;}


#line 52 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, setFrame)(TFrame* s) {

#line 53 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	frameptr_19436 = s;}


#line 277 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_BOOL, peekline_140154)(Streamobj139218* s, NimStringDesc** line) {
	NIM_BOOL volatile result;
	NI pos;
	TSafePoint TMP606;	nimfr("peekLine", "streams.nim")
	result = 0;
#line 284 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(284, "streams.nim");	pos = getposition_139302(s);
#line 285 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(285, "streams.nim");	pushSafePoint(&TMP606);	TMP606.status = setjmp(TMP606.context);	if (TMP606.status == 0) {
#line 286 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(286, "streams.nim");		result = readline_140144(s, line);		popSafePoint();	}
	else {		popSafePoint();		setFrame((TFrame*)&FR);	}
	{
#line 285 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(285, "streams.nim");		setposition_139293(s, pos);
	}
	if (TMP606.status != 0) reraiseException();	popFrame();	return result;}


#line 288 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NimStringDesc*, readline_140161)(Streamobj139218* s) {
	NimStringDesc* result;
	nimfr("readLine", "streams.nim")
	result = 0;
#line 291 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(291, "streams.nim");	result = copyString(((NimStringDesc*) &TMP607));	{
#line 292 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(292, "streams.nim");		while (1) {			NIM_CHAR c;

#line 293 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
			nimln(293, "streams.nim");			c = readchar_139654(s);
#line 294 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
			nimln(294, "streams.nim");			{
#line 294 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				if (!((NU8)(c) == (NU8)(13))) goto LA5;

#line 295 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				nimln(295, "streams.nim");				c = readchar_139654(s);
#line 296 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				nimln(296, "streams.nim");				goto LA1;
			}
			LA5: ;

#line 297 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
			nimln(297, "streams.nim");			{				NIM_BOOL LOC9;
#line 297 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				LOC9 = 0;
#line 297 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				LOC9 = ((NU8)(c) == (NU8)(10));				if (LOC9) goto LA10;

#line 297 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				LOC9 = ((NU8)(c) == (NU8)(0));				LA10: ;
				if (!LOC9) goto LA11;

#line 298 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				nimln(298, "streams.nim");				goto LA1;
			}
			goto LA7;
			LA11: ;
			{
#line 300 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
				nimln(300, "streams.nim");				result = addChar(result, c);			}
			LA7: ;
		}
	} LA1: ;	popFrame();	return result;}


#line 302 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NimStringDesc*, peekline_140169)(Streamobj139218* s) {
	NimStringDesc* volatile result;
	NI pos;
	TSafePoint TMP608;	nimfr("peekLine", "streams.nim")
	result = 0;
#line 305 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(305, "streams.nim");	pos = getposition_139302(s);
#line 306 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(306, "streams.nim");	pushSafePoint(&TMP608);	TMP608.status = setjmp(TMP608.context);	if (TMP608.status == 0) {
#line 307 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(307, "streams.nim");		result = readline_140161(s);		popSafePoint();	}
	else {		popSafePoint();		setFrame((TFrame*)&FR);	}
	{
#line 306 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(306, "streams.nim");		setposition_139293(s, pos);
	}
	if (TMP608.status != 0) reraiseException();	popFrame();	return result;}


#line 317 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_BOOL, ssatend_140182)(Streamobj139218* s_140184) {
	NIM_BOOL result;
	Stringstreamobj140177* s;
	nimfr("ssAtEnd", "streams.nim")
{	result = 0;
#line 318 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(318, "streams.nim");	if (s_140184) chckObj((*s_140184).Sup.m_type, (&NTI140177));	s = ((Stringstreamobj140177*) (s_140184));
#line 319 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(319, "streams.nim");
#line 319 "/home/fedorov_ag/Nim/lib/pure/streams.nim"

#line 353 "/home/fedorov_ag/Nim/lib/system.nim"
	nimln(353, "system.nim");
#line 319 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(319, "streams.nim");	result = (((*s).data ? (*s).data->Sup.len : 0) <= (*s).pos);	goto BeforeRet;
	}BeforeRet: ;
	popFrame();	return result;}


#line 321 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, sssetposition_140187)(Streamobj139218* s_140189, NI pos) {
	Stringstreamobj140177* s;
	nimfr("ssSetPosition", "streams.nim")

#line 322 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(322, "streams.nim");	if (s_140189) chckObj((*s_140189).Sup.m_type, (&NTI140177));	s = ((Stringstreamobj140177*) (s_140189));
#line 323 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(323, "streams.nim");
#line 323 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	(*s).pos = clamp_140193(pos, ((NI) 0), ((*s).data ? (*s).data->Sup.len : 0));	popFrame();}


#line 325 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, ssgetposition_140203)(Streamobj139218* s_140205) {
	NI result;
	Stringstreamobj140177* s;
	nimfr("ssGetPosition", "streams.nim")
{	result = 0;
#line 326 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(326, "streams.nim");	if (s_140205) chckObj((*s_140205).Sup.m_type, (&NTI140177));	s = ((Stringstreamobj140177*) (s_140205));
#line 327 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(327, "streams.nim");
#line 327 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	result = (*s).pos;	goto BeforeRet;
	}BeforeRet: ;
	popFrame();	return result;}


#line 326 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 327 "/home/fedorov_ag/Nim/lib/system/arithm.nim"

#line 327 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	result = (NI)((NU64)(a) - (NU64)(b));
#line 328 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	{		NIM_BOOL LOC3;
#line 328 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = 0;
#line 353 "/home/fedorov_ag/Nim/lib/system.nim"

#line 328 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ a));		if (LOC3) goto LA4;

#line 353 "/home/fedorov_ag/Nim/lib/system.nim"

#line 328 "/home/fedorov_ag/Nim/lib/system/arithm.nim"

#line 328 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));		LA4: ;
		if (!LOC3) goto LA5;

#line 329 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 330 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 329 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, ssreaddata_140208)(Streamobj139218* s_140210, void* buffer, NI buflen) {
	NI result;
	Stringstreamobj140177* s;
	NI TMP611;	nimfr("ssReadData", "streams.nim")
	result = 0;
#line 330 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(330, "streams.nim");	if (s_140210) chckObj((*s_140210).Sup.m_type, (&NTI140177));	s = ((Stringstreamobj140177*) (s_140210));
#line 331 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(331, "streams.nim");
#line 331 "/home/fedorov_ag/Nim/lib/pure/streams.nim"

#line 331 "/home/fedorov_ag/Nim/lib/pure/streams.nim"

#line 331 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	TMP611 = subInt(((*s).data ? (*s).data->Sup.len : 0), (*s).pos);	result = ((buflen <= (NI)(TMP611)) ? buflen : (NI)(TMP611));
#line 332 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(332, "streams.nim");	{		NI TMP612;
#line 357 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(357, "system.nim");		if (!(((NI) 0) < result)) goto LA3;

#line 333 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(333, "streams.nim");		if ((NU)((*s).pos) > (NU)((*s).data->Sup.len)) raiseIndexError();		memcpy(buffer, ((void*) ((&(*s).data->data[(*s).pos]))), ((NI)chckRange(result, ((NI) 0), ((NI) IL64(9223372036854775807)))));

#line 334 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(334, "streams.nim");		TMP612 = addInt((*s).pos, result);		(*s).pos = (NI)(TMP612);	}
	LA3: ;
	popFrame();	return result;}


#line 336 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, sspeekdata_140229)(Streamobj139218* s_140231, void* buffer, NI buflen) {
	NI result;
	Stringstreamobj140177* s;
	NI TMP613;	nimfr("ssPeekData", "streams.nim")
	result = 0;
#line 337 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(337, "streams.nim");	if (s_140231) chckObj((*s_140231).Sup.m_type, (&NTI140177));	s = ((Stringstreamobj140177*) (s_140231));
#line 338 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(338, "streams.nim");
#line 338 "/home/fedorov_ag/Nim/lib/pure/streams.nim"

#line 338 "/home/fedorov_ag/Nim/lib/pure/streams.nim"

#line 338 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	TMP613 = subInt(((*s).data ? (*s).data->Sup.len : 0), (*s).pos);	result = ((buflen <= (NI)(TMP613)) ? buflen : (NI)(TMP613));
#line 339 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(339, "streams.nim");	{
#line 357 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(357, "system.nim");		if (!(((NI) 0) < result)) goto LA3;

#line 340 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(340, "streams.nim");		if ((NU)((*s).pos) > (NU)((*s).data->Sup.len)) raiseIndexError();		memcpy(buffer, ((void*) ((&(*s).data->data[(*s).pos]))), ((NI)chckRange(result, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA3: ;
	popFrame();	return result;}


#line 342 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, sswritedata_140241)(Streamobj139218* s_140243, void* buffer, NI buflen) {
	Stringstreamobj140177* s;
	NI TMP616;	nimfr("ssWriteData", "streams.nim")
{
#line 343 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(343, "streams.nim");	if (s_140243) chckObj((*s_140243).Sup.m_type, (&NTI140177));	s = ((Stringstreamobj140177*) (s_140243));
#line 344 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(344, "streams.nim");	{
#line 344 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		if (!(buflen <= ((NI) 0))) goto LA3;

#line 345 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(345, "streams.nim");		goto BeforeRet;
	}
	LA3: ;

#line 346 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(346, "streams.nim");	{		NI TMP614;		NI TMP615;
#line 357 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(357, "system.nim");
#line 346 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(346, "streams.nim");
#line 346 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		TMP614 = addInt((*s).pos, buflen);		if (!(((*s).data ? (*s).data->Sup.len : 0) < (NI)(TMP614))) goto LA7;

#line 347 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(347, "streams.nim");
#line 347 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		TMP615 = addInt((*s).pos, buflen);		(*s).data = setLengthStr((*s).data, ((NI)chckRange((NI)(TMP615), ((NI) 0), ((NI) IL64(9223372036854775807)))));	}
	LA7: ;

#line 348 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(348, "streams.nim");	if ((NU)((*s).pos) > (NU)((*s).data->Sup.len)) raiseIndexError();	memcpy(((void*) ((&(*s).data->data[(*s).pos]))), buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));

#line 349 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(349, "streams.nim");	TMP616 = addInt((*s).pos, buflen);	(*s).pos = (NI)(TMP616);	}BeforeRet: ;
	popFrame();}


#line 351 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, ssclose_140257)(Streamobj139218* s_140259) {
	Stringstreamobj140177* s;
	NimStringDesc* LOC1;	nimfr("ssClose", "streams.nim")

#line 352 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(352, "streams.nim");	if (s_140259) chckObj((*s_140259).Sup.m_type, (&NTI140177));	s = ((Stringstreamobj140177*) (s_140259));
#line 353 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(353, "streams.nim");	LOC1 = 0;	LOC1 = (*s).data; (*s).data = copyStringRC1(NIM_NIL);	if (LOC1) nimGCunrefNoCycle(LOC1);	popFrame();}
N_NIMCALL(void, TMP617)(void* p, NI op) {
	Stringstreamobj140177* a;
	a = (Stringstreamobj140177*)p;
	nimGCvisit((void*)(*a).data, op);}


#line 355 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(Stringstreamobj140177*, newstringstream_140261)(NimStringDesc* s) {
	Stringstreamobj140177* result;
	NimStringDesc* LOC1;	nimfr("newStringStream", "streams.nim")
	result = 0;
#line 357 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(357, "streams.nim");	result = (Stringstreamobj140177*) newObj((&NTI140175), sizeof(Stringstreamobj140177));	(*result).Sup.Sup.m_type = (&NTI140177);
#line 358 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(358, "streams.nim");	LOC1 = 0;	LOC1 = (*result).data; (*result).data = copyStringRC1(s);	if (LOC1) nimGCunrefNoCycle(LOC1);
#line 359 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(359, "streams.nim");	(*result).pos = ((NI) 0);
#line 360 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(360, "streams.nim");	(*result).Sup.closeimpl = ssclose_140257;
#line 361 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(361, "streams.nim");	(*result).Sup.atendimpl = ssatend_140182;
#line 362 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(362, "streams.nim");	(*result).Sup.setpositionimpl = sssetposition_140187;
#line 363 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(363, "streams.nim");	(*result).Sup.getpositionimpl = ssgetposition_140203;
#line 364 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(364, "streams.nim");	(*result).Sup.readdataimpl = ssreaddata_140208;
#line 365 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(365, "streams.nim");	(*result).Sup.peekdataimpl = sspeekdata_140229;
#line 366 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(366, "streams.nim");	(*result).Sup.writedataimpl = sswritedata_140241;	popFrame();	return result;}


#line 376 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, fsclose_140280)(Streamobj139218* s) {
	nimfr("fsClose", "streams.nim")

#line 377 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(377, "streams.nim");	{
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		if (s) chckObj((*s).Sup.m_type, (&NTI140276));		if (!!(((*((Filestreamobj140276*) (s))).f == NIM_NIL))) goto LA3;

#line 378 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(378, "streams.nim");		if (s) chckObj((*s).Sup.m_type, (&NTI140276));		fclose((*((Filestreamobj140276*) (s))).f);

#line 379 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(379, "streams.nim");		if (s) chckObj((*s).Sup.m_type, (&NTI140276));		(*((Filestreamobj140276*) (s))).f = NIM_NIL;	}
	LA3: ;
	popFrame();}


#line 380 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, fsflush_140295)(Streamobj139218* s) {
	nimfr("fsFlush", "streams.nim")

#line 380 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(380, "streams.nim");	if (s) chckObj((*s).Sup.m_type, (&NTI140276));	fflush((*((Filestreamobj140276*) (s))).f);
	popFrame();}


#line 381 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NIM_BOOL, fsatend_140298)(Streamobj139218* s) {
	NIM_BOOL result;
	nimfr("fsAtEnd", "streams.nim")
{	result = 0;
#line 381 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(381, "streams.nim");
#line 381 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	if (s) chckObj((*s).Sup.m_type, (&NTI140276));	result = endoffile_15454((*((Filestreamobj140276*) (s))).f);	goto BeforeRet;
	}BeforeRet: ;
	popFrame();	return result;}


#line 382 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, fssetposition_140302)(Streamobj139218* s, NI pos) {
	nimfr("fsSetPosition", "streams.nim")

#line 382 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(382, "streams.nim");	if (s) chckObj((*s).Sup.m_type, (&NTI140276));	setfilepos_15581((*((Filestreamobj140276*) (s))).f, ((NI64) (pos)));
	popFrame();}


#line 383 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, fsgetposition_140306)(Streamobj139218* s) {
	NI result;
	NI64 LOC1;	nimfr("fsGetPosition", "streams.nim")
{	result = 0;
#line 383 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(383, "streams.nim");
#line 383 "/home/fedorov_ag/Nim/lib/pure/streams.nim"

#line 383 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	if (s) chckObj((*s).Sup.m_type, (&NTI140276));	LOC1 = 0;	LOC1 = getfilepos_15585((*((Filestreamobj140276*) (s))).f);	result = ((NI) (LOC1));	goto BeforeRet;
	}BeforeRet: ;
	popFrame();	return result;}


#line 385 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, fsreaddata_140311)(Streamobj139218* s, void* buffer, NI buflen) {
	NI result;
	nimfr("fsReadData", "streams.nim")
	result = 0;
#line 386 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(386, "streams.nim");	if (s) chckObj((*s).Sup.m_type, (&NTI140276));	result = readbuffer_15554((*((Filestreamobj140276*) (s))).f, buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));	popFrame();	return result;}


#line 388 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, fspeekdata_140317)(Streamobj139218* s, void* buffer, NI buflen) {
	NI volatile result;
	NI pos;
	TSafePoint TMP618;	nimfr("fsPeekData", "streams.nim")
	result = 0;
#line 389 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(389, "streams.nim");	pos = fsgetposition_140306(s);
#line 390 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(390, "streams.nim");	pushSafePoint(&TMP618);	TMP618.status = setjmp(TMP618.context);	if (TMP618.status == 0) {
#line 391 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(391, "streams.nim");		if (s) chckObj((*s).Sup.m_type, (&NTI140276));		result = readbuffer_15554((*((Filestreamobj140276*) (s))).f, buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));		popSafePoint();	}
	else {		popSafePoint();		setFrame((TFrame*)&FR);	}
	{
#line 390 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(390, "streams.nim");		fssetposition_140302(s, pos);
	}
	if (TMP618.status != 0) reraiseException();	popFrame();	return result;}


#line 393 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, fswritedata_140324)(Streamobj139218* s, void* buffer, NI buflen) {
	nimfr("fsWriteData", "streams.nim")

#line 394 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(394, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(349, "system.nim");
#line 349 "/home/fedorov_ag/Nim/lib/system.nim"

#line 394 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(394, "streams.nim");		if (s) chckObj((*s).Sup.m_type, (&NTI140276));		LOC3 = 0;		LOC3 = writebuffer_15576((*((Filestreamobj140276*) (s))).f, buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));		if (!!((LOC3 == buflen))) goto LA4;

#line 395 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		nimln(395, "streams.nim");		LOC6 = 0;		LOC6 = neweio_139202(((NimStringDesc*) &TMP619));
#line 395 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}
N_NIMCALL(void, TMP620)(void* p, NI op) {
	Filestreamobj140276* a;
	a = (Filestreamobj140276*)p;
}


#line 397 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(Filestreamobj140276*, newfilestream_140329)(FILE* f) {
	Filestreamobj140276* result;
	nimfr("newFileStream", "streams.nim")
	result = 0;
#line 399 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(399, "streams.nim");	result = (Filestreamobj140276*) newObj((&NTI140274), sizeof(Filestreamobj140276));	(*result).Sup.Sup.m_type = (&NTI140276);
#line 400 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(400, "streams.nim");	(*result).f = f;
#line 401 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(401, "streams.nim");	(*result).Sup.closeimpl = fsclose_140280;
#line 402 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(402, "streams.nim");	(*result).Sup.atendimpl = fsatend_140298;
#line 403 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(403, "streams.nim");	(*result).Sup.setpositionimpl = fssetposition_140302;
#line 404 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(404, "streams.nim");	(*result).Sup.getpositionimpl = fsgetposition_140306;
#line 405 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(405, "streams.nim");	(*result).Sup.readdataimpl = fsreaddata_140311;
#line 406 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(406, "streams.nim");	(*result).Sup.peekdataimpl = fspeekdata_140317;
#line 407 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(407, "streams.nim");	(*result).Sup.writedataimpl = fswritedata_140324;
#line 408 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(408, "streams.nim");	(*result).Sup.flushimpl = fsflush_140295;	popFrame();	return result;}


#line 410 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(Filestreamobj140276*, newfilestream_140341)(NimStringDesc* filename, NU8 mode) {
	Filestreamobj140276* result;
	FILE* f;
	nimfr("newFileStream", "streams.nim")
	result = 0;	f = 0;
#line 415 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
	nimln(415, "streams.nim");	{		NIM_BOOL LOC3;
#line 415 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		LOC3 = 0;		LOC3 = open_15403(&f, filename, mode, ((NI) -1));		if (!LOC3) goto LA4;

#line 415 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
		result = newfilestream_140329(f);	}
	LA4: ;
	popFrame();	return result;}
N_NIMCALL(void, TMP958)(void* p, NI op) {
	Streamobj139218* a;
	a = (Streamobj139218*)p;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void) {
	nimfr("streams", "streams.nim")
	popFrame();}

NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void) {
static TNimNode* TMP609[8];
static TNimNode* TMP610[2];
static TNimNode TMP597[13];NTI139218.size = sizeof(Streamobj139218);
NTI139218.kind = 17;
NTI139218.base = (&NTI3608);
NTI139218.flags = 1;
TMP609[0] = &TMP597[1];
NTI139219.size = sizeof(TY139219);
NTI139219.kind = 25;
NTI139219.base = 0;
NTI139219.flags = 3;
TMP597[1].kind = 1;
TMP597[1].offset = offsetof(Streamobj139218, closeimpl);
TMP597[1].typ = (&NTI139219);
TMP597[1].name = "closeImpl";
TMP609[1] = &TMP597[2];
NTI139223.size = sizeof(TY139223);
NTI139223.kind = 25;
NTI139223.base = 0;
NTI139223.flags = 3;
TMP597[2].kind = 1;
TMP597[2].offset = offsetof(Streamobj139218, atendimpl);
TMP597[2].typ = (&NTI139223);
TMP597[2].name = "atEndImpl";
TMP609[2] = &TMP597[3];
NTI139227.size = sizeof(TY139227);
NTI139227.kind = 25;
NTI139227.base = 0;
NTI139227.flags = 3;
TMP597[3].kind = 1;
TMP597[3].offset = offsetof(Streamobj139218, setpositionimpl);
TMP597[3].typ = (&NTI139227);
TMP597[3].name = "setPositionImpl";
TMP609[3] = &TMP597[4];
NTI139232.size = sizeof(TY139232);
NTI139232.kind = 25;
NTI139232.base = 0;
NTI139232.flags = 3;
TMP597[4].kind = 1;
TMP597[4].offset = offsetof(Streamobj139218, getpositionimpl);
TMP597[4].typ = (&NTI139232);
TMP597[4].name = "getPositionImpl";
TMP609[4] = &TMP597[5];
NTI139236.size = sizeof(TY139236);
NTI139236.kind = 25;
NTI139236.base = 0;
NTI139236.flags = 3;
TMP597[5].kind = 1;
TMP597[5].offset = offsetof(Streamobj139218, readdataimpl);
TMP597[5].typ = (&NTI139236);
TMP597[5].name = "readDataImpl";
TMP609[5] = &TMP597[6];
NTI139242.size = sizeof(TY139242);
NTI139242.kind = 25;
NTI139242.base = 0;
NTI139242.flags = 3;
TMP597[6].kind = 1;
TMP597[6].offset = offsetof(Streamobj139218, peekdataimpl);
TMP597[6].typ = (&NTI139242);
TMP597[6].name = "peekDataImpl";
TMP609[6] = &TMP597[7];
NTI139248.size = sizeof(TY139248);
NTI139248.kind = 25;
NTI139248.base = 0;
NTI139248.flags = 3;
TMP597[7].kind = 1;
TMP597[7].offset = offsetof(Streamobj139218, writedataimpl);
TMP597[7].typ = (&NTI139248);
TMP597[7].name = "writeDataImpl";
TMP609[7] = &TMP597[8];
NTI139254.size = sizeof(TY139254);
NTI139254.kind = 25;
NTI139254.base = 0;
NTI139254.flags = 3;
TMP597[8].kind = 1;
TMP597[8].offset = offsetof(Streamobj139218, flushimpl);
TMP597[8].typ = (&NTI139254);
TMP597[8].name = "flushImpl";
TMP597[0].len = 8; TMP597[0].kind = 2; TMP597[0].sons = &TMP609[0];
NTI139218.node = &TMP597[0];
NTI140177.size = sizeof(Stringstreamobj140177);
NTI140177.kind = 17;
NTI140177.base = (&NTI139218);
TMP610[0] = &TMP597[10];
TMP597[10].kind = 1;
TMP597[10].offset = offsetof(Stringstreamobj140177, data);
TMP597[10].typ = (&NTI138);
TMP597[10].name = "data";
TMP610[1] = &TMP597[11];
TMP597[11].kind = 1;
TMP597[11].offset = offsetof(Stringstreamobj140177, pos);
TMP597[11].typ = (&NTI104);
TMP597[11].name = "pos";
TMP597[9].len = 2; TMP597[9].kind = 2; TMP597[9].sons = &TMP610[0];
NTI140177.node = &TMP597[9];
NTI140175.size = sizeof(Stringstreamobj140177*);
NTI140175.kind = 22;
NTI140175.base = (&NTI140177);
NTI140175.marker = TMP617;
NTI140276.size = sizeof(Filestreamobj140276);
NTI140276.kind = 17;
NTI140276.base = (&NTI139218);
NTI140276.flags = 1;
TMP597[12].kind = 1;
TMP597[12].offset = offsetof(Filestreamobj140276, f);
TMP597[12].typ = (&NTI15004);
TMP597[12].name = "f";
NTI140276.node = &TMP597[12];
NTI140274.size = sizeof(Filestreamobj140276*);
NTI140274.kind = 22;
NTI140274.base = (&NTI140276);
NTI140274.marker = TMP620;
NTI139216.size = sizeof(Streamobj139218*);
NTI139216.kind = 22;
NTI139216.base = (&NTI139218);
NTI139216.marker = TMP958;
}

