/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -g3 -O0  -IC:\Nim\lib -o y:\nimcode\simplepaint\src\nimcache\stdlib_unicode.o y:\nimcode\simplepaint\src\nimcache\stdlib_unicode.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct TY171842 TY171842;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
struct  TGenericSeq  {NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  NimStringDesc  {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  TNimNode  {NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY171842 {  TGenericSeq Sup;  NI data[SEQ_DECL_SIZE];};
#line 659 "c:\\nim\\lib\\system.nim"
N_NIMCALL(TY171842*, newseq_171837)(NI len);
#line 64 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
#line 1175 "c:\\nim\\lib\\system.nim"
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
#line 18 "c:\\nim\\lib\\system\\chcks.nim"
N_NOINLINE(void, raiseIndexError)(void);
#line 30 "c:\\nim\\lib\\system\\chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
#line 12 "c:\\nim\\lib\\system\\chcks.nim"
N_NOINLINE(void, raiseRangeError)(NI64 val);
#line 303 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 298 "c:\\nim\\lib\\system\\excpt.nim"
N_NOINLINE(void, stackoverflow_22201)(void);
#line 49 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void);TNimType NTI166203; /* RuneImpl */
extern TFrame* frameptr_19436;


#line 30 "c:\\nim\\lib\\system\\chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
#line 31 "c:\\nim\\lib\\system\\chcks.nim"
	{		NIM_BOOL LOC3;
#line 31 "c:\\nim\\lib\\system\\chcks.nim"
		LOC3 = 0;
#line 353 "c:\\nim\\lib\\system.nim"
		LOC3 = (a <= i);		if (!(LOC3)) goto LA4;

#line 31 "c:\\nim\\lib\\system\\chcks.nim"
		LOC3 = (i <= b);		LA4: ;
		if (!LOC3) goto LA5;

#line 32 "c:\\nim\\lib\\system\\chcks.nim"

#line 32 "c:\\nim\\lib\\system\\chcks.nim"
		result = i;		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
#line 34 "c:\\nim\\lib\\system\\chcks.nim"
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;}


#line 303 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
	LOC1 = 0;
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
	{
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);	}
	goto LA2;
	LA4: ;
	{
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
#line 305 "c:\\nim\\lib\\system\\excpt.nim"
	(*s).prev = frameptr_19436;
#line 306 "c:\\nim\\lib\\system\\excpt.nim"
	frameptr_19436 = s;
#line 307 "c:\\nim\\lib\\system\\excpt.nim"
	{
#line 307 "c:\\nim\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;

#line 307 "c:\\nim\\lib\\system\\excpt.nim"
		stackoverflow_22201();
	}
	LA9: ;
}


#line 49 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 50 "c:\\nim\\lib\\system\\excpt.nim"
	frameptr_19436 = (*frameptr_19436).prev;}


#line 138 "c:\\nim\\lib\\pure\\unicode.nim"
N_NIMCALL(NimStringDesc*, nuctoUTF8)(NI c) {
	NimStringDesc* result;
	NI i;
	nimfr("toUTF8", "unicode.nim")
	result = 0;
#line 140 "c:\\nim\\lib\\pure\\unicode.nim"
	nimln(140, "unicode.nim");	i = c;
#line 141 "c:\\nim\\lib\\pure\\unicode.nim"
	nimln(141, "unicode.nim");	{
#line 141 "c:\\nim\\lib\\pure\\unicode.nim"
		if (!((NU64)(i) <= (NU64)(((NI) 127)))) goto LA3;

#line 142 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(142, "unicode.nim");
#line 142 "c:\\nim\\lib\\pure\\unicode.nim"
		result = mnewString(((NI) 1));
#line 143 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(143, "unicode.nim");		if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();
#line 143 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI)chckRange(i, ((NI) 0), ((NI) 255)))));	}
	goto LA1;
	LA3: ;
	{
#line 144 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(144, "unicode.nim");		if (!((NU64)(i) <= (NU64)(((NI) 2047)))) goto LA6;

#line 145 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(145, "unicode.nim");
#line 145 "c:\\nim\\lib\\pure\\unicode.nim"
		result = mnewString(((NI) 2));
#line 146 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(146, "unicode.nim");		if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();
#line 146 "c:\\nim\\lib\\pure\\unicode.nim"

#line 146 "c:\\nim\\lib\\pure\\unicode.nim"

#line 146 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI)chckRange((NI)((NI)((NU64)(i) >> (NU64)(((NI) 6))) | ((NI) 192)), ((NI) 0), ((NI) 255)))));
#line 147 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(147, "unicode.nim");		if ((NU)(((NI) 1)) > (NU)(result->Sup.len)) raiseIndexError();
#line 147 "c:\\nim\\lib\\pure\\unicode.nim"

#line 147 "c:\\nim\\lib\\pure\\unicode.nim"

#line 147 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)(i & ((NI) 63)))) | ((NI) 128)), ((NI) 0), ((NI) 255)))));	}
	goto LA1;
	LA6: ;
	{
#line 148 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(148, "unicode.nim");		if (!((NU64)(i) <= (NU64)(((NI) 65535)))) goto LA9;

#line 149 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(149, "unicode.nim");
#line 149 "c:\\nim\\lib\\pure\\unicode.nim"
		result = mnewString(((NI) 3));
#line 150 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(150, "unicode.nim");		if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();
#line 150 "c:\\nim\\lib\\pure\\unicode.nim"

#line 150 "c:\\nim\\lib\\pure\\unicode.nim"

#line 150 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI)chckRange((NI)((NI)((NU64)(i) >> (NU64)(((NI) 12))) | ((NI) 224)), ((NI) 0), ((NI) 255)))));
#line 151 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(151, "unicode.nim");		if ((NU)(((NI) 1)) > (NU)(result->Sup.len)) raiseIndexError();
#line 151 "c:\\nim\\lib\\pure\\unicode.nim"

#line 151 "c:\\nim\\lib\\pure\\unicode.nim"

#line 151 "c:\\nim\\lib\\pure\\unicode.nim"

#line 151 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 6))) & ((NI) 63)))) | ((NI) 128)), ((NI) 0), ((NI) 255)))));
#line 152 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(152, "unicode.nim");		if ((NU)(((NI) 2)) > (NU)(result->Sup.len)) raiseIndexError();
#line 152 "c:\\nim\\lib\\pure\\unicode.nim"

#line 152 "c:\\nim\\lib\\pure\\unicode.nim"

#line 152 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 2)] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)(i & ((NI) 63)))) | ((NI) 128)), ((NI) 0), ((NI) 255)))));	}
	goto LA1;
	LA9: ;
	{
#line 153 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(153, "unicode.nim");		if (!((NU64)(i) <= (NU64)(((NI) 2097151)))) goto LA12;

#line 154 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(154, "unicode.nim");
#line 154 "c:\\nim\\lib\\pure\\unicode.nim"
		result = mnewString(((NI) 4));
#line 155 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(155, "unicode.nim");		if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();
#line 155 "c:\\nim\\lib\\pure\\unicode.nim"

#line 155 "c:\\nim\\lib\\pure\\unicode.nim"

#line 155 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI)chckRange((NI)((NI)((NU64)(i) >> (NU64)(((NI) 18))) | ((NI) 240)), ((NI) 0), ((NI) 255)))));
#line 156 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(156, "unicode.nim");		if ((NU)(((NI) 1)) > (NU)(result->Sup.len)) raiseIndexError();
#line 156 "c:\\nim\\lib\\pure\\unicode.nim"

#line 156 "c:\\nim\\lib\\pure\\unicode.nim"

#line 156 "c:\\nim\\lib\\pure\\unicode.nim"

#line 156 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 12))) & ((NI) 63)))) | ((NI) 128)), ((NI) 0), ((NI) 255)))));
#line 157 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(157, "unicode.nim");		if ((NU)(((NI) 2)) > (NU)(result->Sup.len)) raiseIndexError();
#line 157 "c:\\nim\\lib\\pure\\unicode.nim"

#line 157 "c:\\nim\\lib\\pure\\unicode.nim"

#line 157 "c:\\nim\\lib\\pure\\unicode.nim"

#line 157 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 2)] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 6))) & ((NI) 63)))) | ((NI) 128)), ((NI) 0), ((NI) 255)))));
#line 158 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(158, "unicode.nim");		if ((NU)(((NI) 3)) > (NU)(result->Sup.len)) raiseIndexError();
#line 158 "c:\\nim\\lib\\pure\\unicode.nim"

#line 158 "c:\\nim\\lib\\pure\\unicode.nim"

#line 158 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 3)] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)(i & ((NI) 63)))) | ((NI) 128)), ((NI) 0), ((NI) 255)))));	}
	goto LA1;
	LA12: ;
	{
#line 159 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(159, "unicode.nim");		if (!((NU64)(i) <= (NU64)(((NI) 67108863)))) goto LA15;

#line 160 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(160, "unicode.nim");
#line 160 "c:\\nim\\lib\\pure\\unicode.nim"
		result = mnewString(((NI) 5));
#line 161 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(161, "unicode.nim");		if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();
#line 161 "c:\\nim\\lib\\pure\\unicode.nim"

#line 161 "c:\\nim\\lib\\pure\\unicode.nim"

#line 161 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI)chckRange((NI)((NI)((NU64)(i) >> (NU64)(((NI) 24))) | ((NI) 248)), ((NI) 0), ((NI) 255)))));
#line 162 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(162, "unicode.nim");		if ((NU)(((NI) 1)) > (NU)(result->Sup.len)) raiseIndexError();
#line 162 "c:\\nim\\lib\\pure\\unicode.nim"

#line 162 "c:\\nim\\lib\\pure\\unicode.nim"

#line 162 "c:\\nim\\lib\\pure\\unicode.nim"

#line 162 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 18))) & ((NI) 63)))) | ((NI) 128)), ((NI) 0), ((NI) 255)))));
#line 163 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(163, "unicode.nim");		if ((NU)(((NI) 2)) > (NU)(result->Sup.len)) raiseIndexError();
#line 163 "c:\\nim\\lib\\pure\\unicode.nim"

#line 163 "c:\\nim\\lib\\pure\\unicode.nim"

#line 163 "c:\\nim\\lib\\pure\\unicode.nim"

#line 163 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 2)] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 12))) & ((NI) 63)))) | ((NI) 128)), ((NI) 0), ((NI) 255)))));
#line 164 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(164, "unicode.nim");		if ((NU)(((NI) 3)) > (NU)(result->Sup.len)) raiseIndexError();
#line 164 "c:\\nim\\lib\\pure\\unicode.nim"

#line 164 "c:\\nim\\lib\\pure\\unicode.nim"

#line 164 "c:\\nim\\lib\\pure\\unicode.nim"

#line 164 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 3)] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 6))) & ((NI) 63)))) | ((NI) 128)), ((NI) 0), ((NI) 255)))));
#line 165 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(165, "unicode.nim");		if ((NU)(((NI) 4)) > (NU)(result->Sup.len)) raiseIndexError();
#line 165 "c:\\nim\\lib\\pure\\unicode.nim"

#line 165 "c:\\nim\\lib\\pure\\unicode.nim"

#line 165 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 4)] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)(i & ((NI) 63)))) | ((NI) 128)), ((NI) 0), ((NI) 255)))));	}
	goto LA1;
	LA15: ;
	{
#line 166 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(166, "unicode.nim");		if (!((NU64)(i) <= (NU64)(((NI) 2147483647)))) goto LA18;

#line 167 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(167, "unicode.nim");
#line 167 "c:\\nim\\lib\\pure\\unicode.nim"
		result = mnewString(((NI) 6));
#line 168 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(168, "unicode.nim");		if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();
#line 168 "c:\\nim\\lib\\pure\\unicode.nim"

#line 168 "c:\\nim\\lib\\pure\\unicode.nim"

#line 168 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI)chckRange((NI)((NI)((NU64)(i) >> (NU64)(((NI) 30))) | ((NI) 252)), ((NI) 0), ((NI) 255)))));
#line 169 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(169, "unicode.nim");		if ((NU)(((NI) 1)) > (NU)(result->Sup.len)) raiseIndexError();
#line 169 "c:\\nim\\lib\\pure\\unicode.nim"

#line 169 "c:\\nim\\lib\\pure\\unicode.nim"

#line 169 "c:\\nim\\lib\\pure\\unicode.nim"

#line 169 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 24))) & ((NI) 63)))) | ((NI) 128)), ((NI) 0), ((NI) 255)))));
#line 170 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(170, "unicode.nim");		if ((NU)(((NI) 2)) > (NU)(result->Sup.len)) raiseIndexError();
#line 170 "c:\\nim\\lib\\pure\\unicode.nim"

#line 170 "c:\\nim\\lib\\pure\\unicode.nim"

#line 170 "c:\\nim\\lib\\pure\\unicode.nim"

#line 170 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 2)] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 18))) & ((NI) 63)))) | ((NI) 128)), ((NI) 0), ((NI) 255)))));
#line 171 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(171, "unicode.nim");		if ((NU)(((NI) 3)) > (NU)(result->Sup.len)) raiseIndexError();
#line 171 "c:\\nim\\lib\\pure\\unicode.nim"

#line 171 "c:\\nim\\lib\\pure\\unicode.nim"

#line 171 "c:\\nim\\lib\\pure\\unicode.nim"

#line 171 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 3)] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 12))) & ((NI) 63)))) | ((NI) 128)), ((NI) 0), ((NI) 255)))));
#line 172 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(172, "unicode.nim");		if ((NU)(((NI) 4)) > (NU)(result->Sup.len)) raiseIndexError();
#line 172 "c:\\nim\\lib\\pure\\unicode.nim"

#line 172 "c:\\nim\\lib\\pure\\unicode.nim"

#line 172 "c:\\nim\\lib\\pure\\unicode.nim"

#line 172 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 4)] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 6))) & ((NI) 63)))) | ((NI) 128)), ((NI) 0), ((NI) 255)))));
#line 173 "c:\\nim\\lib\\pure\\unicode.nim"
		nimln(173, "unicode.nim");		if ((NU)(((NI) 5)) > (NU)(result->Sup.len)) raiseIndexError();
#line 173 "c:\\nim\\lib\\pure\\unicode.nim"

#line 173 "c:\\nim\\lib\\pure\\unicode.nim"

#line 173 "c:\\nim\\lib\\pure\\unicode.nim"
		result->data[((NI) 5)] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)(i & ((NI) 63)))) | ((NI) 128)), ((NI) 0), ((NI) 255)))));	}
	goto LA1;
	LA18: ;
	{	}
	LA1: ;
	popFrame();	return result;}
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit000)(void) {
	nimfr("unicode", "unicode.nim")
	popFrame();}

NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit000)(void) {
NTI166203.size = sizeof(NI);
NTI166203.kind = 31;
NTI166203.base = 0;
NTI166203.flags = 3;
}

