/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -g3 -O0  -IC:\Nim\lib -o y:\nimcode\simplepaint\src\nimcache\stdlib_hashes.o y:\nimcode\simplepaint\src\nimcache\stdlib_hashes.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Jsonnodeobj187633 Jsonnodeobj187633;
typedef struct TY187649 TY187649;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY187648 TY187648;
typedef struct TY187653 TY187653;
struct  TGenericSeq  {NI len;
NI reserved;
};
struct  NimStringDesc  {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY187649 {
NimStringDesc* Field0;
Jsonnodeobj187633* Field1;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  Jsonnodeobj187633  {NU8 kind;
union{
struct {NimStringDesc* str;
} S1;
struct {NI64 num;
} S2;
struct {NF fnum;
} S3;
struct {NIM_BOOL bval;
} S4;
struct {TY187648* fields;
} S6;
struct {TY187653* elems;
} S7;
} kindU;
};
struct  TNimNode  {NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY187648 {  TGenericSeq Sup;  TY187649 data[SEQ_DECL_SIZE];};struct TY187653 {  TGenericSeq Sup;  Jsonnodeobj187633* data[SEQ_DECL_SIZE];};
#line 50 "c:\\nim\\lib\\pure\\hashes.nim"
static N_INLINE(NI, HEX21HEX26_160004)(NI h, NI val);
#line 303 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 298 "c:\\nim\\lib\\system\\excpt.nim"
N_NOINLINE(void, stackoverflow_22201)(void);
#line 49 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void);
#line 57 "c:\\nim\\lib\\pure\\hashes.nim"
static N_INLINE(NI, HEX21HEX24_160027)(NI h);
#line 64 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hashdata_160049)(void* data, NI size);
#line 319 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b);
#line 13 "c:\\nim\\lib\\system\\arithm.nim"
N_NOINLINE(void, raiseOverflow)(void);
#line 326 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b);
#line 83 "c:\\nim\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_160401)(void* x);
#line 107 "c:\\nim\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_160801)(NI x);
#line 111 "c:\\nim\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_160805)(NI64 x);
#line 115 "c:\\nim\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_160809)(NIM_CHAR x);
#line 123 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hash_160827)(NimStringDesc* x);
#line 18 "c:\\nim\\lib\\system\\chcks.nim"
N_NOINLINE(void, raiseIndexError)(void);
#line 130 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hash_160859)(NimStringDesc* sbuf, NI spos, NI epos);
#line 140 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hashignorestyle_160892)(NimStringDesc* x);
#line 20 "c:\\nim\\lib\\pure\\etcpriv.nim"
static N_INLINE(NIM_BOOL, ismagicidentseparatorrune_159008)(NCSTRING cs, NI i);
#line 30 "c:\\nim\\lib\\system\\chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
#line 12 "c:\\nim\\lib\\system\\chcks.nim"
N_NOINLINE(void, raiseRangeError)(NI64 val);
#line 159 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hashignorestyle_160975)(NimStringDesc* sbuf, NI spos, NI epos);
#line 180 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hashignorecase_161059)(NimStringDesc* x);
#line 190 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hashignorecase_161130)(NimStringDesc* sbuf, NI spos, NI epos);
#line 204 "c:\\nim\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_161202)(NF x);
#line 760 "c:\\nim\\lib\\pure\\json.nim"
N_NIMCALL(NI, hash_188674)(Jsonnodeobj187633* n);
#line 216 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hash_188757)(TY187649 x);extern TFrame* frameptr_19436;
TNimType NTI160002; /* Hash */


#line 303 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
	LOC1 = 0;
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
	{
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);	}
	goto LA2;
	LA4: ;
	{
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
#line 305 "c:\\nim\\lib\\system\\excpt.nim"
	(*s).prev = frameptr_19436;
#line 306 "c:\\nim\\lib\\system\\excpt.nim"
	frameptr_19436 = s;
#line 307 "c:\\nim\\lib\\system\\excpt.nim"
	{
#line 307 "c:\\nim\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;

#line 307 "c:\\nim\\lib\\system\\excpt.nim"
		stackoverflow_22201();
	}
	LA9: ;
}


#line 49 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 50 "c:\\nim\\lib\\system\\excpt.nim"
	frameptr_19436 = (*frameptr_19436).prev;}


#line 50 "c:\\nim\\lib\\pure\\hashes.nim"
static N_INLINE(NI, HEX21HEX26_160004)(NI h, NI val) {
	NI result;
	nimfr("!&", "hashes.nim")
	result = 0;
#line 53 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(53, "hashes.nim");
#line 53 "c:\\nim\\lib\\pure\\hashes.nim"
	result = (NI)((NU64)(h) + (NU64)(val));
#line 54 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(54, "hashes.nim");
#line 54 "c:\\nim\\lib\\pure\\hashes.nim"

#line 54 "c:\\nim\\lib\\pure\\hashes.nim"
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(((NI) 10)))));
#line 55 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(55, "hashes.nim");
#line 55 "c:\\nim\\lib\\pure\\hashes.nim"

#line 55 "c:\\nim\\lib\\pure\\hashes.nim"
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(((NI) 6))));	popFrame();	return result;}


#line 57 "c:\\nim\\lib\\pure\\hashes.nim"
static N_INLINE(NI, HEX21HEX24_160027)(NI h) {
	NI result;
	nimfr("!$", "hashes.nim")
	result = 0;
#line 60 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(60, "hashes.nim");
#line 60 "c:\\nim\\lib\\pure\\hashes.nim"

#line 60 "c:\\nim\\lib\\pure\\hashes.nim"
	result = (NI)((NU64)(h) + (NU64)((NI)((NU64)(h) << (NU64)(((NI) 3)))));
#line 61 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(61, "hashes.nim");
#line 61 "c:\\nim\\lib\\pure\\hashes.nim"

#line 61 "c:\\nim\\lib\\pure\\hashes.nim"
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(((NI) 11))));
#line 62 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(62, "hashes.nim");
#line 62 "c:\\nim\\lib\\pure\\hashes.nim"

#line 62 "c:\\nim\\lib\\pure\\hashes.nim"
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(((NI) 15)))));	popFrame();	return result;}


#line 319 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 320 "c:\\nim\\lib\\system\\arithm.nim"

#line 320 "c:\\nim\\lib\\system\\arithm.nim"
	result = (NI)((NU64)(a) + (NU64)(b));
#line 321 "c:\\nim\\lib\\system\\arithm.nim"
	{		NIM_BOOL LOC3;
#line 321 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = 0;
#line 353 "c:\\nim\\lib\\system.nim"

#line 321 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ a));		if (LOC3) goto LA4;

#line 353 "c:\\nim\\lib\\system.nim"

#line 321 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ b));		LA4: ;
		if (!LOC3) goto LA5;

#line 322 "c:\\nim\\lib\\system\\arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 323 "c:\\nim\\lib\\system\\arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 326 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 327 "c:\\nim\\lib\\system\\arithm.nim"

#line 327 "c:\\nim\\lib\\system\\arithm.nim"
	result = (NI)((NU64)(a) - (NU64)(b));
#line 328 "c:\\nim\\lib\\system\\arithm.nim"
	{		NIM_BOOL LOC3;
#line 328 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = 0;
#line 353 "c:\\nim\\lib\\system.nim"

#line 328 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ a));		if (LOC3) goto LA4;

#line 353 "c:\\nim\\lib\\system.nim"

#line 328 "c:\\nim\\lib\\system\\arithm.nim"

#line 328 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));		LA4: ;
		if (!LOC3) goto LA5;

#line 329 "c:\\nim\\lib\\system\\arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 330 "c:\\nim\\lib\\system\\arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 64 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hashdata_160049)(void* data, NI size) {
	NI result;
	NI h;
	NCSTRING p;
	NI i;
	NI s;
	nimfr("hashData", "hashes.nim")
	result = 0;
#line 66 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(66, "hashes.nim");	h = ((NI) 0);
#line 71 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(71, "hashes.nim");	p = ((NCSTRING) (data));
#line 72 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(72, "hashes.nim");	i = ((NI) 0);
#line 73 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(73, "hashes.nim");	s = size;	{
#line 74 "c:\\nim\\lib\\pure\\hashes.nim"
		nimln(74, "hashes.nim");		while (1) {			NI TMP709;			NI TMP710;
#line 357 "c:\\nim\\lib\\system.nim"
			nimln(357, "system.nim");			if (!(((NI) 0) < s)) goto LA2;

#line 75 "c:\\nim\\lib\\pure\\hashes.nim"
			nimln(75, "hashes.nim");
#line 75 "c:\\nim\\lib\\pure\\hashes.nim"
			h = HEX21HEX26_160004(h, ((NI) (((NU8)(p[i])))));
#line 76 "c:\\nim\\lib\\pure\\hashes.nim"
			nimln(76, "hashes.nim");			TMP709 = addInt(i, ((NI) 1));			i = (NI)(TMP709);
#line 77 "c:\\nim\\lib\\pure\\hashes.nim"
			nimln(77, "hashes.nim");			TMP710 = subInt(s, ((NI) 1));			s = (NI)(TMP710);		} LA2: ;	}

#line 78 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(78, "hashes.nim");	result = HEX21HEX24_160027(h);	popFrame();	return result;}


#line 83 "c:\\nim\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_160401)(void* x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
#line 97 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(97, "hashes.nim");
#line 97 "c:\\nim\\lib\\pure\\hashes.nim"
	result = (NI)((NU64)(((NI) (x))) >> (NU64)(((NI) 3)));	popFrame();	return result;}


#line 107 "c:\\nim\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_160801)(NI x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
#line 109 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(109, "hashes.nim");	result = x;	popFrame();	return result;}


#line 111 "c:\\nim\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_160805)(NI64 x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
#line 113 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(113, "hashes.nim");
#line 113 "c:\\nim\\lib\\pure\\hashes.nim"
	result = ((NI) (((NI32)(NU32)(NU64)(x))));	popFrame();	return result;}


#line 115 "c:\\nim\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_160809)(NIM_CHAR x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
#line 117 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(117, "hashes.nim");
#line 117 "c:\\nim\\lib\\pure\\hashes.nim"
	result = ((NI) (((NU8)(x))));	popFrame();	return result;}


#line 123 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hash_160827)(NimStringDesc* x) {
	NI result;
	NI h;
	nimfr("hash", "hashes.nim")
	result = 0;
#line 125 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(125, "hashes.nim");	h = ((NI) 0);	{		NI i_160841;
		NI HEX3Atmp_160852;
		NI TMP711;		NI res_160855;
		i_160841 = 0;		HEX3Atmp_160852 = 0;
#line 126 "c:\\nim\\lib\\pure\\hashes.nim"
		nimln(126, "hashes.nim");
#line 126 "c:\\nim\\lib\\pure\\hashes.nim"

#line 126 "c:\\nim\\lib\\pure\\hashes.nim"
		TMP711 = subInt((x ? x->Sup.len : 0), ((NI) 1));		HEX3Atmp_160852 = (NI)(TMP711);
#line 1874 "c:\\nim\\lib\\system.nim"
		nimln(1874, "system.nim");		res_160855 = ((NI) 0);		{
#line 1875 "c:\\nim\\lib\\system.nim"
			nimln(1875, "system.nim");			while (1) {				NI TMP712;
#line 1875 "c:\\nim\\lib\\system.nim"
				if (!(res_160855 <= HEX3Atmp_160852)) goto LA3;

#line 1876 "c:\\nim\\lib\\system.nim"
				nimln(1876, "system.nim");				i_160841 = res_160855;
#line 127 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(127, "hashes.nim");
#line 127 "c:\\nim\\lib\\pure\\hashes.nim"
				if ((NU)(i_160841) > (NU)(x->Sup.len)) raiseIndexError();				h = HEX21HEX26_160004(h, ((NI) (((NU8)(x->data[i_160841])))));
#line 1895 "c:\\nim\\lib\\system.nim"
				nimln(1895, "system.nim");				TMP712 = addInt(res_160855, ((NI) 1));				res_160855 = (NI)(TMP712);			} LA3: ;		}
	}

#line 128 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(128, "hashes.nim");	result = HEX21HEX24_160027(h);	popFrame();	return result;}


#line 130 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hash_160859)(NimStringDesc* sbuf, NI spos, NI epos) {
	NI result;
	NI h;
	nimfr("hash", "hashes.nim")
	result = 0;
#line 135 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(135, "hashes.nim");	h = ((NI) 0);	{		NI i_160875;
		NI res_160888;
		i_160875 = 0;
#line 1874 "c:\\nim\\lib\\system.nim"
		nimln(1874, "system.nim");		res_160888 = spos;		{
#line 1875 "c:\\nim\\lib\\system.nim"
			nimln(1875, "system.nim");			while (1) {				NI TMP713;
#line 1875 "c:\\nim\\lib\\system.nim"
				if (!(res_160888 <= epos)) goto LA3;

#line 1876 "c:\\nim\\lib\\system.nim"
				nimln(1876, "system.nim");				i_160875 = res_160888;
#line 137 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(137, "hashes.nim");
#line 137 "c:\\nim\\lib\\pure\\hashes.nim"
				if ((NU)(i_160875) > (NU)(sbuf->Sup.len)) raiseIndexError();				h = HEX21HEX26_160004(h, ((NI) (((NU8)(sbuf->data[i_160875])))));
#line 1895 "c:\\nim\\lib\\system.nim"
				nimln(1895, "system.nim");				TMP713 = addInt(res_160888, ((NI) 1));				res_160888 = (NI)(TMP713);			} LA3: ;		}
	}

#line 138 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(138, "hashes.nim");	result = HEX21HEX24_160027(h);	popFrame();	return result;}


#line 20 "c:\\nim\\lib\\pure\\etcpriv.nim"
static N_INLINE(NIM_BOOL, ismagicidentseparatorrune_159008)(NCSTRING cs, NI i) {
	NIM_BOOL result;
	NIM_BOOL LOC1;	NIM_BOOL LOC2;	NI TMP715;	NI TMP716;	nimfr("isMagicIdentSeparatorRune", "etcpriv.nim")
	result = 0;
#line 21 "c:\\nim\\lib\\pure\\etcpriv.nim"
	nimln(21, "etcpriv.nim");
#line 22 "c:\\nim\\lib\\pure\\etcpriv.nim"
	nimln(22, "etcpriv.nim");	LOC1 = 0;
#line 21 "c:\\nim\\lib\\pure\\etcpriv.nim"
	nimln(21, "etcpriv.nim");	LOC2 = 0;
#line 21 "c:\\nim\\lib\\pure\\etcpriv.nim"
	LOC2 = ((NU8)(cs[i]) == (NU8)(226));	if (!(LOC2)) goto LA3;

#line 22 "c:\\nim\\lib\\pure\\etcpriv.nim"
	nimln(22, "etcpriv.nim");
#line 22 "c:\\nim\\lib\\pure\\etcpriv.nim"
	TMP715 = addInt(i, ((NI) 1));	LOC2 = ((NU8)(cs[(NI)(TMP715)]) == (NU8)(128));	LA3: ;
	LOC1 = LOC2;	if (!(LOC1)) goto LA4;

#line 23 "c:\\nim\\lib\\pure\\etcpriv.nim"
	nimln(23, "etcpriv.nim");
#line 23 "c:\\nim\\lib\\pure\\etcpriv.nim"
	TMP716 = addInt(i, ((NI) 2));	LOC1 = ((NU8)(cs[(NI)(TMP716)]) == (NU8)(147));	LA4: ;
	result = LOC1;	popFrame();	return result;}


#line 30 "c:\\nim\\lib\\system\\chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
#line 31 "c:\\nim\\lib\\system\\chcks.nim"
	{		NIM_BOOL LOC3;
#line 31 "c:\\nim\\lib\\system\\chcks.nim"
		LOC3 = 0;
#line 353 "c:\\nim\\lib\\system.nim"
		LOC3 = (a <= i);		if (!(LOC3)) goto LA4;

#line 31 "c:\\nim\\lib\\system\\chcks.nim"
		LOC3 = (i <= b);		LA4: ;
		if (!LOC3) goto LA5;

#line 32 "c:\\nim\\lib\\system\\chcks.nim"

#line 32 "c:\\nim\\lib\\system\\chcks.nim"
		result = i;		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
#line 34 "c:\\nim\\lib\\system\\chcks.nim"
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;}


#line 140 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hashignorestyle_160892)(NimStringDesc* x) {
	NI result;
	NI h;
	NI i;
	NI xlen;
	nimfr("hashIgnoreStyle", "hashes.nim")
	result = 0;
#line 142 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(142, "hashes.nim");	h = ((NI) 0);
#line 143 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(143, "hashes.nim");	i = ((NI) 0);
#line 144 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(144, "hashes.nim");
#line 144 "c:\\nim\\lib\\pure\\hashes.nim"
	xlen = (x ? x->Sup.len : 0);	{
#line 145 "c:\\nim\\lib\\pure\\hashes.nim"
		nimln(145, "hashes.nim");		while (1) {			NIM_CHAR c;

#line 145 "c:\\nim\\lib\\pure\\hashes.nim"
			if (!(i < xlen)) goto LA2;

#line 146 "c:\\nim\\lib\\pure\\hashes.nim"
			nimln(146, "hashes.nim");			if ((NU)(i) > (NU)(x->Sup.len)) raiseIndexError();			c = x->data[i];
#line 147 "c:\\nim\\lib\\pure\\hashes.nim"
			nimln(147, "hashes.nim");			{				NI TMP714;
#line 147 "c:\\nim\\lib\\pure\\hashes.nim"
				if (!((NU8)(c) == (NU8)(95))) goto LA5;

#line 148 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(148, "hashes.nim");				TMP714 = addInt(i, ((NI) 1));				i = (NI)(TMP714);			}
			goto LA3;
			LA5: ;
			{				NIM_BOOL LOC8;				NI TMP717;
#line 149 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(149, "hashes.nim");				LOC8 = 0;				LOC8 = ismagicidentseparatorrune_159008(x->data, i);				if (!LOC8) goto LA9;

#line 150 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(150, "hashes.nim");				TMP717 = addInt(i, ((NI) 3));				i = (NI)(TMP717);			}
			goto LA3;
			LA9: ;
			{				NI TMP719;
#line 152 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(152, "hashes.nim");				{					NI TMP718;
#line 1098 "c:\\nim\\lib\\system.nim"
					nimln(1098, "system.nim");					if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA14;

#line 153 "c:\\nim\\lib\\pure\\hashes.nim"
					nimln(153, "hashes.nim");
#line 153 "c:\\nim\\lib\\pure\\hashes.nim"

#line 153 "c:\\nim\\lib\\pure\\hashes.nim"

#line 153 "c:\\nim\\lib\\pure\\hashes.nim"
					TMP718 = addInt(((NI) (((NU8)(c)))), ((NI) 32));					c = ((NIM_CHAR) (((NI)chckRange((NI)(TMP718), ((NI) 0), ((NI) 255)))));				}
				LA14: ;

#line 154 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(154, "hashes.nim");
#line 154 "c:\\nim\\lib\\pure\\hashes.nim"
				h = HEX21HEX26_160004(h, ((NI) (((NU8)(c)))));
#line 155 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(155, "hashes.nim");				TMP719 = addInt(i, ((NI) 1));				i = (NI)(TMP719);			}
			LA3: ;
		} LA2: ;	}

#line 157 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(157, "hashes.nim");	result = HEX21HEX24_160027(h);	popFrame();	return result;}


#line 159 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hashignorestyle_160975)(NimStringDesc* sbuf, NI spos, NI epos) {
	NI result;
	NI h;
	NI i;
	nimfr("hashIgnoreStyle", "hashes.nim")
	result = 0;
#line 165 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(165, "hashes.nim");	h = ((NI) 0);
#line 166 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(166, "hashes.nim");	i = spos;	{
#line 167 "c:\\nim\\lib\\pure\\hashes.nim"
		nimln(167, "hashes.nim");		while (1) {			NIM_CHAR c;

#line 167 "c:\\nim\\lib\\pure\\hashes.nim"
			if (!(i <= epos)) goto LA2;

#line 168 "c:\\nim\\lib\\pure\\hashes.nim"
			nimln(168, "hashes.nim");			if ((NU)(i) > (NU)(sbuf->Sup.len)) raiseIndexError();			c = sbuf->data[i];
#line 169 "c:\\nim\\lib\\pure\\hashes.nim"
			nimln(169, "hashes.nim");			{				NI TMP720;
#line 169 "c:\\nim\\lib\\pure\\hashes.nim"
				if (!((NU8)(c) == (NU8)(95))) goto LA5;

#line 170 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(170, "hashes.nim");				TMP720 = addInt(i, ((NI) 1));				i = (NI)(TMP720);			}
			goto LA3;
			LA5: ;
			{				NIM_BOOL LOC8;				NI TMP721;
#line 171 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(171, "hashes.nim");				LOC8 = 0;				LOC8 = ismagicidentseparatorrune_159008(sbuf->data, i);				if (!LOC8) goto LA9;

#line 172 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(172, "hashes.nim");				TMP721 = addInt(i, ((NI) 3));				i = (NI)(TMP721);			}
			goto LA3;
			LA9: ;
			{				NI TMP723;
#line 174 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(174, "hashes.nim");				{					NI TMP722;
#line 1098 "c:\\nim\\lib\\system.nim"
					nimln(1098, "system.nim");					if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA14;

#line 175 "c:\\nim\\lib\\pure\\hashes.nim"
					nimln(175, "hashes.nim");
#line 175 "c:\\nim\\lib\\pure\\hashes.nim"

#line 175 "c:\\nim\\lib\\pure\\hashes.nim"

#line 175 "c:\\nim\\lib\\pure\\hashes.nim"
					TMP722 = addInt(((NI) (((NU8)(c)))), ((NI) 32));					c = ((NIM_CHAR) (((NI)chckRange((NI)(TMP722), ((NI) 0), ((NI) 255)))));				}
				LA14: ;

#line 176 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(176, "hashes.nim");
#line 176 "c:\\nim\\lib\\pure\\hashes.nim"
				h = HEX21HEX26_160004(h, ((NI) (((NU8)(c)))));
#line 177 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(177, "hashes.nim");				TMP723 = addInt(i, ((NI) 1));				i = (NI)(TMP723);			}
			LA3: ;
		} LA2: ;	}

#line 178 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(178, "hashes.nim");	result = HEX21HEX24_160027(h);	popFrame();	return result;}


#line 180 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hashignorecase_161059)(NimStringDesc* x) {
	NI result;
	NI h;
	nimfr("hashIgnoreCase", "hashes.nim")
	result = 0;
#line 182 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(182, "hashes.nim");	h = ((NI) 0);	{		NI i_161073;
		NI HEX3Atmp_161123;
		NI TMP724;		NI res_161126;
		i_161073 = 0;		HEX3Atmp_161123 = 0;
#line 183 "c:\\nim\\lib\\pure\\hashes.nim"
		nimln(183, "hashes.nim");
#line 183 "c:\\nim\\lib\\pure\\hashes.nim"

#line 183 "c:\\nim\\lib\\pure\\hashes.nim"
		TMP724 = subInt((x ? x->Sup.len : 0), ((NI) 1));		HEX3Atmp_161123 = (NI)(TMP724);
#line 1874 "c:\\nim\\lib\\system.nim"
		nimln(1874, "system.nim");		res_161126 = ((NI) 0);		{
#line 1875 "c:\\nim\\lib\\system.nim"
			nimln(1875, "system.nim");			while (1) {				NIM_CHAR c;
				NI TMP726;
#line 1875 "c:\\nim\\lib\\system.nim"
				if (!(res_161126 <= HEX3Atmp_161123)) goto LA3;

#line 1876 "c:\\nim\\lib\\system.nim"
				nimln(1876, "system.nim");				i_161073 = res_161126;
#line 184 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(184, "hashes.nim");				if ((NU)(i_161073) > (NU)(x->Sup.len)) raiseIndexError();				c = x->data[i_161073];
#line 185 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(185, "hashes.nim");				{					NI TMP725;
#line 1098 "c:\\nim\\lib\\system.nim"
					nimln(1098, "system.nim");					if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA6;

#line 186 "c:\\nim\\lib\\pure\\hashes.nim"
					nimln(186, "hashes.nim");
#line 186 "c:\\nim\\lib\\pure\\hashes.nim"

#line 186 "c:\\nim\\lib\\pure\\hashes.nim"

#line 186 "c:\\nim\\lib\\pure\\hashes.nim"
					TMP725 = addInt(((NI) (((NU8)(c)))), ((NI) 32));					c = ((NIM_CHAR) (((NI)chckRange((NI)(TMP725), ((NI) 0), ((NI) 255)))));				}
				LA6: ;

#line 187 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(187, "hashes.nim");
#line 187 "c:\\nim\\lib\\pure\\hashes.nim"
				h = HEX21HEX26_160004(h, ((NI) (((NU8)(c)))));
#line 1895 "c:\\nim\\lib\\system.nim"
				nimln(1895, "system.nim");				TMP726 = addInt(res_161126, ((NI) 1));				res_161126 = (NI)(TMP726);			} LA3: ;		}
	}

#line 188 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(188, "hashes.nim");	result = HEX21HEX24_160027(h);	popFrame();	return result;}


#line 190 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hashignorecase_161130)(NimStringDesc* sbuf, NI spos, NI epos) {
	NI result;
	NI h;
	nimfr("hashIgnoreCase", "hashes.nim")
	result = 0;
#line 196 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(196, "hashes.nim");	h = ((NI) 0);	{		NI i_161146;
		NI res_161198;
		i_161146 = 0;
#line 1874 "c:\\nim\\lib\\system.nim"
		nimln(1874, "system.nim");		res_161198 = spos;		{
#line 1875 "c:\\nim\\lib\\system.nim"
			nimln(1875, "system.nim");			while (1) {				NIM_CHAR c;
				NI TMP728;
#line 1875 "c:\\nim\\lib\\system.nim"
				if (!(res_161198 <= epos)) goto LA3;

#line 1876 "c:\\nim\\lib\\system.nim"
				nimln(1876, "system.nim");				i_161146 = res_161198;
#line 198 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(198, "hashes.nim");				if ((NU)(i_161146) > (NU)(sbuf->Sup.len)) raiseIndexError();				c = sbuf->data[i_161146];
#line 199 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(199, "hashes.nim");				{					NI TMP727;
#line 1098 "c:\\nim\\lib\\system.nim"
					nimln(1098, "system.nim");					if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA6;

#line 200 "c:\\nim\\lib\\pure\\hashes.nim"
					nimln(200, "hashes.nim");
#line 200 "c:\\nim\\lib\\pure\\hashes.nim"

#line 200 "c:\\nim\\lib\\pure\\hashes.nim"

#line 200 "c:\\nim\\lib\\pure\\hashes.nim"
					TMP727 = addInt(((NI) (((NU8)(c)))), ((NI) 32));					c = ((NIM_CHAR) (((NI)chckRange((NI)(TMP727), ((NI) 0), ((NI) 255)))));				}
				LA6: ;

#line 201 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(201, "hashes.nim");
#line 201 "c:\\nim\\lib\\pure\\hashes.nim"
				h = HEX21HEX26_160004(h, ((NI) (((NU8)(c)))));
#line 1895 "c:\\nim\\lib\\system.nim"
				nimln(1895, "system.nim");				TMP728 = addInt(res_161198, ((NI) 1));				res_161198 = (NI)(TMP728);			} LA3: ;		}
	}

#line 202 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(202, "hashes.nim");	result = HEX21HEX24_160027(h);	popFrame();	return result;}


#line 204 "c:\\nim\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_161202)(NF x) {
	NI result;
	NF y;
	nimfr("hash", "hashes.nim")
	result = 0;
#line 206 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(206, "hashes.nim");
#line 206 "c:\\nim\\lib\\pure\\hashes.nim"
	y = ((NF)(x) + (NF)(1.0000000000000000e+000));
#line 207 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(207, "hashes.nim");	result = (*((NI*) ((&y))));	popFrame();	return result;}


#line 216 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hash_188757)(TY187649 x) {
	NI result;
	NI LOC1;	NI LOC2;	nimfr("hash", "hashes.nim")
	result = 0;
#line 219 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(219, "hashes.nim");
#line 219 "c:\\nim\\lib\\pure\\hashes.nim"
	LOC1 = 0;	LOC1 = hash_160827(x.Field0);	result = HEX21HEX26_160004(result, LOC1);
#line 219 "c:\\nim\\lib\\pure\\hashes.nim"

#line 219 "c:\\nim\\lib\\pure\\hashes.nim"
	LOC2 = 0;	LOC2 = hash_188674(x.Field1);	result = HEX21HEX26_160004(result, LOC2);
#line 220 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(220, "hashes.nim");	result = HEX21HEX24_160027(result);	popFrame();	return result;}


#line 222 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hash_188723)(TY187649* x, NI xLen0) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;	{		TY187649 it_188755;
		NI i_188774;
		memset((void*)(&it_188755), 0, sizeof(it_188755));
#line 1965 "c:\\nim\\lib\\system.nim"
		nimln(1965, "system.nim");		i_188774 = ((NI) 0);		{
#line 1966 "c:\\nim\\lib\\system.nim"
			nimln(1966, "system.nim");			while (1) {				NI LOC4;				NI TMP902;
#line 1966 "c:\\nim\\lib\\system.nim"

#line 1966 "c:\\nim\\lib\\system.nim"
				if (!(i_188774 < xLen0)) goto LA3;

#line 1967 "c:\\nim\\lib\\system.nim"
				nimln(1967, "system.nim");				if ((NU)(i_188774) >= (NU)(xLen0)) raiseIndexError();				it_188755.Field0 = x[i_188774].Field0;				it_188755.Field1 = x[i_188774].Field1;
#line 224 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(224, "hashes.nim");
#line 224 "c:\\nim\\lib\\pure\\hashes.nim"
				LOC4 = 0;				LOC4 = hash_188757(it_188755);				result = HEX21HEX26_160004(result, LOC4);
#line 1968 "c:\\nim\\lib\\system.nim"
				nimln(1968, "system.nim");				TMP902 = addInt(i_188774, ((NI) 1));				i_188774 = (NI)(TMP902);			} LA3: ;		}
	}

#line 225 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(225, "hashes.nim");	result = HEX21HEX24_160027(result);	popFrame();	return result;}


#line 222 "c:\\nim\\lib\\pure\\hashes.nim"
N_NIMCALL(NI, hash_188682)(Jsonnodeobj187633** x, NI xLen0) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;	{		Jsonnodeobj187633* it_188714;
		NI i_188718;
		it_188714 = 0;
#line 1965 "c:\\nim\\lib\\system.nim"
		nimln(1965, "system.nim");		i_188718 = ((NI) 0);		{
#line 1966 "c:\\nim\\lib\\system.nim"
			nimln(1966, "system.nim");			while (1) {				NI LOC4;				NI TMP903;
#line 1966 "c:\\nim\\lib\\system.nim"

#line 1966 "c:\\nim\\lib\\system.nim"
				if (!(i_188718 < xLen0)) goto LA3;

#line 1967 "c:\\nim\\lib\\system.nim"
				nimln(1967, "system.nim");				if ((NU)(i_188718) >= (NU)(xLen0)) raiseIndexError();				it_188714 = x[i_188718];
#line 224 "c:\\nim\\lib\\pure\\hashes.nim"
				nimln(224, "hashes.nim");
#line 224 "c:\\nim\\lib\\pure\\hashes.nim"
				LOC4 = 0;				LOC4 = hash_188674(it_188714);				result = HEX21HEX26_160004(result, LOC4);
#line 1968 "c:\\nim\\lib\\system.nim"
				nimln(1968, "system.nim");				TMP903 = addInt(i_188718, ((NI) 1));				i_188718 = (NI)(TMP903);			} LA3: ;		}
	}

#line 225 "c:\\nim\\lib\\pure\\hashes.nim"
	nimln(225, "hashes.nim");	result = HEX21HEX24_160027(result);	popFrame();	return result;}
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void) {
	nimfr("hashes", "hashes.nim")
	popFrame();}

NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void) {
NTI160002.size = sizeof(NI);
NTI160002.kind = 31;
NTI160002.base = 0;
NTI160002.flags = 3;
}

