/* Generated by Nim Compiler v0.13.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -g3 -O0  -I/home/fedorov_ag/Nim/lib -o /home/fedorov_ag/projects/SimplePaint/src/nimcache/stdlib_lexbase.o /home/fedorov_ag/projects/SimplePaint/src/nimcache/stdlib_lexbase.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct Baselexer159007 Baselexer159007;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Streamobj139218 Streamobj139218;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef NU8 TY81210[32];
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimObject  {TNimType* m_type;};
struct  Baselexer159007  {  TNimObject Sup;NI bufpos;
NCSTRING buf;
NI buflen;
Streamobj139218* input;
NI linenumber;
NI sentinel;
NI linestart;
TY81210 refillchars;
};
struct  TGenericSeq  {NI len;
NI reserved;
};
struct  NimStringDesc  {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  TNimNode  {NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, TY139219) (Streamobj139218* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY139223) (Streamobj139218* s);
typedef N_NIMCALL_PTR(void, TY139227) (Streamobj139218* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY139232) (Streamobj139218* s);
typedef N_NIMCALL_PTR(NI, TY139236) (Streamobj139218* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(NI, TY139242) (Streamobj139218* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY139248) (Streamobj139218* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY139254) (Streamobj139218* s);
struct  Streamobj139218  {  TNimObject Sup;TY139219 closeimpl;
TY139223 atendimpl;
TY139227 setpositionimpl;
TY139232 getpositionimpl;
TY139236 readdataimpl;
TY139242 peekdataimpl;
TY139248 writedataimpl;
TY139254 flushimpl;
};

#line 47 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(void, close_159020)(Baselexer159007* L);
#line 855 "/home/fedorov_ag/Nim/lib/system/alloc.nim"
N_NOCONV(void, dealloc_7448)(void* p);
#line 66 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(void, close_139270)(Streamobj139218* s);
#line 303 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 298 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
N_NOINLINE(void, stackoverflow_22201)(void);
#line 49 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void);
#line 53 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(void, fillbuffer_159201)(Baselexer159007* L);
#line 3332 "/home/fedorov_ag/Nim/lib/system.nim"
N_NIMCALL(void, failedassertimpl_89316)(NimStringDesc* msg);
#line 326 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b);
#line 13 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
N_NOINLINE(void, raiseOverflow)(void);
#line 319 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b);
#line 372 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
N_NIMCALL(NI, mulInt)(NI a, NI b);
#line 30 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
#line 12 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
N_NOINLINE(void, raiseRangeError)(NI64 val);
#line 100 "/home/fedorov_ag/Nim/lib/pure/streams.nim"
N_NIMCALL(NI, readdata_139311)(Streamobj139218* s, void* buffer, NI buflen);
#line 338 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, divInt)(NI a, NI b);
#line 17 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
N_NOINLINE(void, raiseDivByZero)(void);
#line 858 "/home/fedorov_ag/Nim/lib/system/alloc.nim"
N_NOCONV(void*, realloc_7433)(void* p, NI newsize);
#line 104 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(NI, fillbaselexer_160409)(Baselexer159007* L, NI pos);
#line 113 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(NI, handlecr_160601)(Baselexer159007* L, NI pos);
#line 124 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(NI, handlelf_160810)(Baselexer159007* L, NI pos);
#line 133 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(NI, handlerefillchar_161010)(Baselexer159007* L, NI pos);
#line 138 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(void, skiputf8bom_161201)(Baselexer159007* L);
#line 143 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(void, open_161223)(Baselexer159007* L, Streamobj139218* input, NI buflen, TY81210 refillchars);
#line 273 "/home/fedorov_ag/Nim/lib/system/gc.nim"
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
#line 849 "/home/fedorov_ag/Nim/lib/system/alloc.nim"
N_NOCONV(void*, alloc_7401)(NI size);
#line 162 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(NI, getcolnumber_161802)(Baselexer159007* L, NI pos);
#line 166 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(NimStringDesc*, getcurrentline_161807)(Baselexer159007* L, NIM_BOOL marker);
#line 90 "/home/fedorov_ag/Nim/lib/system/sysstr.nim"
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
#line 126 "/home/fedorov_ag/Nim/lib/system/sysstr.nim"
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
#line 179 "/home/fedorov_ag/Nim/lib/system/sysstr.nim"
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
#line 168 "/home/fedorov_ag/Nim/lib/system/sysstr.nim"
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
#line 629 "/home/fedorov_ag/Nim/lib/pure/strutils.nim"
N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NIM_CHAR c, NI count);
#line 56 "/home/fedorov_ag/Nim/lib/system/sysstr.nim"
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);NIM_CONST TY81210 Newlines_159004 = {
0x00, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP721, "L.sentinel < L.bufLen ", 22);
STRING_LITERAL(TMP724, "\012  0 <= toCopy ", 15);
STRING_LITERAL(TMP733, "s < L.bufLen ", 13);
STRING_LITERAL(TMP738, "L.bufLen - oldBufLen == oldBufLen ", 34);
STRING_LITERAL(TMP744, "pos <= L.sentinel ", 18);
STRING_LITERAL(TMP746, "L.buf[pos] == \'\\x0D\' ", 21);
STRING_LITERAL(TMP748, "L.buf[pos] == \'\\x0A\' ", 21);
STRING_LITERAL(TMP750, "contains(L.refillChars, L.buf[pos]) ", 36);
STRING_LITERAL(TMP753, "\012  0 < bufLen ", 14);
STRING_LITERAL(TMP754, "\012  not (input == nil) ", 22);
STRING_LITERAL(TMP758, "", 0);
STRING_LITERAL(TMP760, "\012", 1);
STRING_LITERAL(TMP761, "^\012", 2);
extern TFrame* frameptr_19436;
extern TNimType NTI3608; /* RootObj */
TNimType NTI159007; /* BaseLexer */
extern TNimType NTI104; /* int */
extern TNimType NTI140; /* cstring */
extern TNimType NTI139216; /* Stream */
extern TNimType NTI81210; /* set[char] */


#line 303 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	LOC1 = 0;
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	{
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);	}
	goto LA2;
	LA4: ;
	{
#line 304 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
#line 305 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	(*s).prev = frameptr_19436;
#line 306 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	frameptr_19436 = s;
#line 307 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	{
#line 307 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;

#line 307 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
		stackoverflow_22201();
	}
	LA9: ;
}


#line 49 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 50 "/home/fedorov_ag/Nim/lib/system/excpt.nim"
	frameptr_19436 = (*frameptr_19436).prev;}


#line 47 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(void, close_159020)(Baselexer159007* L) {
	nimfr("close", "lexbase.nim")

#line 50 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(50, "lexbase.nim");	dealloc_7448(((void*) ((*L).buf)));

#line 51 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(51, "lexbase.nim");	close_139270((*L).input);
	popFrame();}


#line 326 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 327 "/home/fedorov_ag/Nim/lib/system/arithm.nim"

#line 327 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	result = (NI)((NU64)(a) - (NU64)(b));
#line 328 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	{		NIM_BOOL LOC3;
#line 328 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = 0;
#line 353 "/home/fedorov_ag/Nim/lib/system.nim"

#line 328 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ a));		if (LOC3) goto LA4;

#line 353 "/home/fedorov_ag/Nim/lib/system.nim"

#line 328 "/home/fedorov_ag/Nim/lib/system/arithm.nim"

#line 328 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));		LA4: ;
		if (!LOC3) goto LA5;

#line 329 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 330 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 319 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 320 "/home/fedorov_ag/Nim/lib/system/arithm.nim"

#line 320 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	result = (NI)((NU64)(a) + (NU64)(b));
#line 321 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	{		NIM_BOOL LOC3;
#line 321 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = 0;
#line 353 "/home/fedorov_ag/Nim/lib/system.nim"

#line 321 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ a));		if (LOC3) goto LA4;

#line 353 "/home/fedorov_ag/Nim/lib/system.nim"

#line 321 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ b));		LA4: ;
		if (!LOC3) goto LA5;

#line 322 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 323 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 30 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
#line 31 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
	{		NIM_BOOL LOC3;
#line 31 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
		LOC3 = 0;
#line 353 "/home/fedorov_ag/Nim/lib/system.nim"
		LOC3 = (a <= i);		if (!(LOC3)) goto LA4;

#line 31 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
		LOC3 = (i <= b);		LA4: ;
		if (!LOC3) goto LA5;

#line 32 "/home/fedorov_ag/Nim/lib/system/chcks.nim"

#line 32 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
		result = i;		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
#line 34 "/home/fedorov_ag/Nim/lib/system/chcks.nim"
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;}


#line 338 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 339 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	{
#line 339 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		if (!(b == ((NI) 0))) goto LA3;

#line 340 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		raiseDivByZero();
	}
	LA3: ;

#line 341 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	{		NIM_BOOL LOC7;
#line 341 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC7 = 0;
#line 341 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC7 = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));		if (!(LOC7)) goto LA8;

#line 341 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		LOC7 = (b == ((NI) -1));		LA8: ;
		if (!LOC7) goto LA9;

#line 342 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
		raiseOverflow();
	}
	LA9: ;

#line 343 "/home/fedorov_ag/Nim/lib/system/arithm.nim"

#line 343 "/home/fedorov_ag/Nim/lib/system/arithm.nim"

#line 343 "/home/fedorov_ag/Nim/lib/system/arithm.nim"
	result = (NI)(a / b);	goto BeforeRet;
	}BeforeRet: ;
	return result;}


#line 53 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(void, fillbuffer_159201)(Baselexer159007* L) {
	NI charsread;
	NI tocopy;
	NI s;
	NI oldbuflen;
	NI TMP722;	NI TMP723;	NI TMP727;	NI TMP728;	NI LOC13;	NI TMP729;	NI TMP730;	nimfr("fillBuffer", "lexbase.nim")
	charsread = 0;	tocopy = 0;	s = 0;	oldbuflen = 0;
#line 61 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(61, "lexbase.nim");	{
#line 61 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 61 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		if (!!(((*L).sentinel < (*L).buflen))) goto LA3;

#line 61 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		failedassertimpl_89316(((NimStringDesc*) &TMP721));
	}
	LA3: ;

#line 62 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(62, "lexbase.nim");
#line 62 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 62 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	TMP722 = subInt((*L).buflen, (*L).sentinel);	TMP723 = subInt((NI)(TMP722), ((NI) 1));	tocopy = (NI)(TMP723);
#line 63 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(63, "lexbase.nim");	{
#line 63 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 63 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		if (!!((((NI) 0) <= tocopy))) goto LA7;

#line 63 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		failedassertimpl_89316(((NimStringDesc*) &TMP724));
	}
	LA7: ;

#line 64 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(64, "lexbase.nim");	{		NI TMP725;		NI TMP726;
#line 357 "/home/fedorov_ag/Nim/lib/system.nim"
		nimln(357, "system.nim");		if (!(((NI) 0) < tocopy)) goto LA11;

#line 69 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		nimln(69, "lexbase.nim");
#line 69 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		TMP725 = addInt((*L).sentinel, ((NI) 1));
#line 69 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		TMP726 = mulInt(tocopy, ((NI) 1));		memmove(((void*) ((*L).buf)), ((void*) ((&(*L).buf[(NI)(TMP725)]))), ((NI)chckRange((NI)(TMP726), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA11: ;

#line 70 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(70, "lexbase.nim");
#line 71 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(71, "lexbase.nim");
#line 70 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(70, "lexbase.nim");
#line 71 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(71, "lexbase.nim");
#line 71 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	TMP727 = addInt((*L).sentinel, ((NI) 1));	TMP728 = mulInt((NI)(TMP727), ((NI) 1));	LOC13 = 0;	LOC13 = readdata_139311((*L).input, ((void*) ((&(*L).buf[tocopy]))), (NI)(TMP728));	TMP729 = divInt(LOC13, ((NI) 1));	charsread = (NI)(TMP729);
#line 72 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(72, "lexbase.nim");
#line 72 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	TMP730 = addInt(tocopy, charsread);	s = (NI)(TMP730);
#line 73 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(73, "lexbase.nim");	{		NI TMP731;
#line 73 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 73 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		TMP731 = addInt((*L).sentinel, ((NI) 1));		if (!(charsread < (NI)(TMP731))) goto LA16;

#line 74 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		nimln(74, "lexbase.nim");		(*L).buf[s] = 0;
#line 75 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		nimln(75, "lexbase.nim");		(*L).sentinel = s;	}
	goto LA14;
	LA16: ;
	{		NI TMP732;
#line 78 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		nimln(78, "lexbase.nim");		TMP732 = subInt(s, ((NI) 1));		s = (NI)(TMP732);		{
#line 79 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
			nimln(79, "lexbase.nim");			while (1) {
#line 80 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
				nimln(80, "lexbase.nim");				{
#line 80 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 80 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					if (!!((s < (*L).buflen))) goto LA23;

#line 80 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					failedassertimpl_89316(((NimStringDesc*) &TMP733));
				}
				LA23: ;
				{
#line 81 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					nimln(81, "lexbase.nim");					while (1) {						NIM_BOOL LOC27;						NI TMP734;
#line 81 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
						LOC27 = 0;
#line 353 "/home/fedorov_ag/Nim/lib/system.nim"
						nimln(353, "system.nim");						LOC27 = (((NI) 0) <= s);						if (!(LOC27)) goto LA28;

#line 1104 "/home/fedorov_ag/Nim/lib/system.nim"
						nimln(1104, "system.nim");
#line 1104 "/home/fedorov_ag/Nim/lib/system.nim"
						LOC27 = !((((*L).refillchars[(NU)(((NU8)((*L).buf[s])))>>3] &(1U<<((NU)(((NU8)((*L).buf[s])))&7U)))!=0));						LA28: ;
						if (!LOC27) goto LA26;

#line 81 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
						nimln(81, "lexbase.nim");						TMP734 = subInt(s, ((NI) 1));						s = (NI)(TMP734);					} LA26: ;				}

#line 82 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
				nimln(82, "lexbase.nim");				{
#line 353 "/home/fedorov_ag/Nim/lib/system.nim"
					nimln(353, "system.nim");					if (!(((NI) 0) <= s)) goto LA31;

#line 84 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					nimln(84, "lexbase.nim");					(*L).sentinel = s;
#line 85 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					nimln(85, "lexbase.nim");					goto LA19;
				}
				goto LA29;
				LA31: ;
				{					NI TMP735;					NI TMP736;					void* LOC34;					NI TMP739;					NI LOC39;					NI TMP740;					NI TMP743;
#line 89 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					nimln(89, "lexbase.nim");					oldbuflen = (*L).buflen;
#line 90 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					nimln(90, "lexbase.nim");
#line 90 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					TMP735 = mulInt((*L).buflen, ((NI) 2));					(*L).buflen = (NI)(TMP735);
#line 94 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					nimln(94, "lexbase.nim");
#line 94 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 94 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					TMP736 = mulInt((*L).buflen, ((NI) 1));					LOC34 = 0;					LOC34 = realloc_7433(((void*) ((*L).buf)), ((NI)chckRange((NI)(TMP736), ((NI) 0), ((NI) IL64(9223372036854775807)))));					(*L).buf = ((NCSTRING) (LOC34));
#line 95 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					nimln(95, "lexbase.nim");					{						NI TMP737;
#line 95 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 95 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 95 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
						TMP737 = subInt((*L).buflen, oldbuflen);						if (!!(((NI)(TMP737) == oldbuflen))) goto LA37;

#line 95 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
						failedassertimpl_89316(((NimStringDesc*) &TMP738));
					}
					LA37: ;

#line 96 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					nimln(96, "lexbase.nim");
#line 97 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					nimln(97, "lexbase.nim");
#line 96 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					nimln(96, "lexbase.nim");
#line 97 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					nimln(97, "lexbase.nim");					TMP739 = mulInt(oldbuflen, ((NI) 1));					LOC39 = 0;					LOC39 = readdata_139311((*L).input, ((void*) ((&(*L).buf[oldbuflen]))), (NI)(TMP739));					TMP740 = divInt(LOC39, ((NI) 1));					charsread = (NI)(TMP740);
#line 98 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					nimln(98, "lexbase.nim");					{						NI TMP741;						NI TMP742;
#line 98 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
						if (!(charsread < oldbuflen)) goto LA42;

#line 99 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
						nimln(99, "lexbase.nim");
#line 99 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
						TMP741 = addInt(oldbuflen, charsread);						(*L).buf[(NI)(TMP741)] = 0;
#line 100 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
						nimln(100, "lexbase.nim");
#line 100 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
						TMP742 = addInt(oldbuflen, charsread);						(*L).sentinel = (NI)(TMP742);
#line 101 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
						nimln(101, "lexbase.nim");						goto LA19;
					}
					LA42: ;

#line 102 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					nimln(102, "lexbase.nim");
#line 102 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
					TMP743 = subInt((*L).buflen, ((NI) 1));					s = (NI)(TMP743);				}
				LA29: ;
			}
		} LA19: ;	}
	LA14: ;
	popFrame();}


#line 104 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(NI, fillbaselexer_160409)(Baselexer159007* L, NI pos) {
	NI result;
	nimfr("fillBaseLexer", "lexbase.nim")
	result = 0;
#line 105 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(105, "lexbase.nim");	{
#line 105 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 105 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		if (!!((pos <= (*L).sentinel))) goto LA3;

#line 105 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		failedassertimpl_89316(((NimStringDesc*) &TMP744));
	}
	LA3: ;

#line 106 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(106, "lexbase.nim");	{		NI TMP745;
#line 106 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		if (!(pos < (*L).sentinel)) goto LA7;

#line 107 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		nimln(107, "lexbase.nim");
#line 107 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		TMP745 = addInt(pos, ((NI) 1));		result = (NI)(TMP745);	}
	goto LA5;
	LA7: ;
	{
#line 109 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		nimln(109, "lexbase.nim");		fillbuffer_159201(L);

#line 110 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		nimln(110, "lexbase.nim");		(*L).bufpos = ((NI) 0);
#line 111 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		nimln(111, "lexbase.nim");		result = ((NI) 0);	}
	LA5: ;
	popFrame();	return result;}


#line 113 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(NI, handlecr_160601)(Baselexer159007* L, NI pos) {
	NI result;
	NI TMP747;	nimfr("handleCR", "lexbase.nim")
	result = 0;
#line 117 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(117, "lexbase.nim");	{
#line 117 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 117 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		if (!!(((NU8)((*L).buf[pos]) == (NU8)(13)))) goto LA3;

#line 117 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		failedassertimpl_89316(((NimStringDesc*) &TMP746));
	}
	LA3: ;

#line 118 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(118, "lexbase.nim");	TMP747 = addInt((*L).linenumber, ((NI) 1));	(*L).linenumber = (NI)(TMP747);
#line 119 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(119, "lexbase.nim");	result = fillbaselexer_160409(L, pos);
#line 120 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(120, "lexbase.nim");	{
#line 120 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		if (!((NU8)((*L).buf[result]) == (NU8)(10))) goto LA7;

#line 121 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		nimln(121, "lexbase.nim");		result = fillbaselexer_160409(L, result);	}
	LA7: ;

#line 122 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(122, "lexbase.nim");	(*L).linestart = result;	popFrame();	return result;}


#line 124 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(NI, handlelf_160810)(Baselexer159007* L, NI pos) {
	NI result;
	NI TMP749;	nimfr("handleLF", "lexbase.nim")
	result = 0;
#line 128 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(128, "lexbase.nim");	{
#line 128 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 128 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		if (!!(((NU8)((*L).buf[pos]) == (NU8)(10)))) goto LA3;

#line 128 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		failedassertimpl_89316(((NimStringDesc*) &TMP748));
	}
	LA3: ;

#line 129 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(129, "lexbase.nim");	TMP749 = addInt((*L).linenumber, ((NI) 1));	(*L).linenumber = (NI)(TMP749);
#line 130 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(130, "lexbase.nim");	result = fillbaselexer_160409(L, pos);
#line 131 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(131, "lexbase.nim");	(*L).linestart = result;	popFrame();	return result;}


#line 133 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(NI, handlerefillchar_161010)(Baselexer159007* L, NI pos) {
	NI result;
	nimfr("handleRefillChar", "lexbase.nim")
	result = 0;
#line 135 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(135, "lexbase.nim");	{
#line 135 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 135 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		if (!!((((*L).refillchars[(NU)(((NU8)((*L).buf[pos])))>>3] &(1U<<((NU)(((NU8)((*L).buf[pos])))&7U)))!=0))) goto LA3;

#line 135 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		failedassertimpl_89316(((NimStringDesc*) &TMP750));
	}
	LA3: ;

#line 136 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(136, "lexbase.nim");	result = fillbaselexer_160409(L, pos);	popFrame();	return result;}


#line 138 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(void, skiputf8bom_161201)(Baselexer159007* L) {
	nimfr("skipUtf8Bom", "lexbase.nim")

#line 139 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(139, "lexbase.nim");	{		NIM_BOOL LOC3;		NIM_BOOL LOC4;		NI TMP751;		NI TMP752;
#line 139 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		LOC3 = 0;
#line 139 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		LOC4 = 0;
#line 139 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		LOC4 = ((NU8)((*L).buf[((NI) 0)]) == (NU8)(239));		if (!(LOC4)) goto LA5;

#line 139 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		LOC4 = ((NU8)((*L).buf[((NI) 1)]) == (NU8)(187));		LA5: ;
		LOC3 = LOC4;		if (!(LOC3)) goto LA6;

#line 139 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		LOC3 = ((NU8)((*L).buf[((NI) 2)]) == (NU8)(191));		LA6: ;
		if (!LOC3) goto LA7;

#line 140 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		nimln(140, "lexbase.nim");		TMP751 = addInt((*L).bufpos, ((NI) 3));		(*L).bufpos = (NI)(TMP751);
#line 141 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		nimln(141, "lexbase.nim");		TMP752 = addInt((*L).linestart, ((NI) 3));		(*L).linestart = (NI)(TMP752);	}
	LA7: ;
	popFrame();}


#line 143 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(void, open_161223)(Baselexer159007* L, Streamobj139218* input, NI buflen, TY81210 refillchars) {
	NI TMP755;	void* LOC9;	NI TMP756;	nimfr("open", "lexbase.nim")

#line 146 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(146, "lexbase.nim");	{
#line 146 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 146 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		if (!!((((NI) 0) < buflen))) goto LA3;

#line 146 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		failedassertimpl_89316(((NimStringDesc*) &TMP753));
	}
	LA3: ;

#line 147 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(147, "lexbase.nim");	{
#line 147 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 147 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 147 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		if (!!(!((input == NIM_NIL)))) goto LA7;

#line 147 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		failedassertimpl_89316(((NimStringDesc*) &TMP754));
	}
	LA7: ;

#line 148 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(148, "lexbase.nim");	unsureAsgnRef((void**) (&(*L).input), input);
#line 149 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(149, "lexbase.nim");	(*L).bufpos = ((NI) 0);
#line 150 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(150, "lexbase.nim");	(*L).buflen = buflen;
#line 151 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(151, "lexbase.nim");	memcpy((void*)(*L).refillchars, (NIM_CONST void*)refillchars, 32);
#line 155 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(155, "lexbase.nim");
#line 155 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 155 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	TMP755 = mulInt(buflen, ((NI) 1));	LOC9 = 0;	LOC9 = alloc_7401(((NI)chckRange((NI)(TMP755), ((NI) 0), ((NI) IL64(9223372036854775807)))));	(*L).buf = ((NCSTRING) (LOC9));
#line 156 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(156, "lexbase.nim");
#line 156 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	TMP756 = subInt(buflen, ((NI) 1));	(*L).sentinel = (NI)(TMP756);
#line 157 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(157, "lexbase.nim");	(*L).linestart = ((NI) 0);
#line 158 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(158, "lexbase.nim");	(*L).linenumber = ((NI) 1);
#line 159 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(159, "lexbase.nim");	fillbuffer_159201(L);

#line 160 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(160, "lexbase.nim");	skiputf8bom_161201(L);
	popFrame();}


#line 162 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(NI, getcolnumber_161802)(Baselexer159007* L, NI pos) {
	NI result;
	NI TMP757;	nimfr("getColNumber", "lexbase.nim")
	result = 0;
#line 164 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(164, "lexbase.nim");
#line 164 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 164 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	TMP757 = subInt(pos, (*L).linestart);	if ((NI)(TMP757) == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();	result = ((NI)(TMP757) > 0? ((NI)(TMP757)) : -((NI)(TMP757)));	popFrame();	return result;}


#line 179 "/home/fedorov_ag/Nim/lib/system/sysstr.nim"
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {

#line 180 "/home/fedorov_ag/Nim/lib/system/sysstr.nim"

#line 180 "/home/fedorov_ag/Nim/lib/system/sysstr.nim"
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));

#line 181 "/home/fedorov_ag/Nim/lib/system/sysstr.nim"
	(*dest).Sup.len += (*src).Sup.len;}


#line 166 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
N_NIMCALL(NimStringDesc*, getcurrentline_161807)(Baselexer159007* L, NIM_BOOL marker) {
	NimStringDesc* result;
	NI i;
	nimfr("getCurrentLine", "lexbase.nim")
	result = 0;	i = 0;
#line 169 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(169, "lexbase.nim");	result = copyString(((NimStringDesc*) &TMP758));
#line 170 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(170, "lexbase.nim");	i = (*L).linestart;	{
#line 171 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		nimln(171, "lexbase.nim");		while (1) {			NI TMP759;
#line 171 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"

#line 1098 "/home/fedorov_ag/Nim/lib/system.nim"
			nimln(1098, "system.nim");			if (!!((((NU8)((*L).buf[i])) == ((NU8)(13)) || ((NU8)((*L).buf[i])) == ((NU8)(10)) || ((NU8)((*L).buf[i])) == ((NU8)(0))))) goto LA2;

#line 172 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
			nimln(172, "lexbase.nim");			result = addChar(result, (*L).buf[i]);
#line 173 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
			nimln(173, "lexbase.nim");			TMP759 = addInt(i, ((NI) 1));			i = (NI)(TMP759);		} LA2: ;	}

#line 174 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(174, "lexbase.nim");	result = resizeString(result, 1);appendString(result, ((NimStringDesc*) &TMP760));
#line 175 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
	nimln(175, "lexbase.nim");	{		NimStringDesc* LOC7;		NI LOC8;		NimStringDesc* LOC9;		if (!marker) goto LA5;

#line 176 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		nimln(176, "lexbase.nim");
#line 176 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		LOC7 = 0;
#line 654 "/home/fedorov_ag/Nim/lib/pure/strutils.nim"
		nimln(654, "strutils.nim");
#line 176 "/home/fedorov_ag/Nim/lib/pure/lexbase.nim"
		nimln(176, "lexbase.nim");		LOC8 = 0;		LOC8 = getcolnumber_161802(L, (*L).bufpos);		LOC9 = 0;		LOC9 = nsuRepeatChar(32, ((NI)chckRange(LOC8, ((NI) 0), ((NI) IL64(9223372036854775807)))));		LOC7 = rawNewString(LOC9->Sup.len + 2);appendString(LOC7, LOC9);appendString(LOC7, ((NimStringDesc*) &TMP761));		result = resizeString(result, LOC7->Sup.len + 0);appendString(result, LOC7);	}
	LA5: ;
	popFrame();	return result;}
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseInit000)(void) {
	nimfr("lexbase", "lexbase.nim")
	popFrame();}

NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseDatInit000)(void) {
static TNimNode* TMP957[8];
static TNimNode TMP719[9];NTI159007.size = sizeof(Baselexer159007);
NTI159007.kind = 17;
NTI159007.base = (&NTI3608);
TMP957[0] = &TMP719[1];
TMP719[1].kind = 1;
TMP719[1].offset = offsetof(Baselexer159007, bufpos);
TMP719[1].typ = (&NTI104);
TMP719[1].name = "bufpos";
TMP957[1] = &TMP719[2];
TMP719[2].kind = 1;
TMP719[2].offset = offsetof(Baselexer159007, buf);
TMP719[2].typ = (&NTI140);
TMP719[2].name = "buf";
TMP957[2] = &TMP719[3];
TMP719[3].kind = 1;
TMP719[3].offset = offsetof(Baselexer159007, buflen);
TMP719[3].typ = (&NTI104);
TMP719[3].name = "bufLen";
TMP957[3] = &TMP719[4];
TMP719[4].kind = 1;
TMP719[4].offset = offsetof(Baselexer159007, input);
TMP719[4].typ = (&NTI139216);
TMP719[4].name = "input";
TMP957[4] = &TMP719[5];
TMP719[5].kind = 1;
TMP719[5].offset = offsetof(Baselexer159007, linenumber);
TMP719[5].typ = (&NTI104);
TMP719[5].name = "lineNumber";
TMP957[5] = &TMP719[6];
TMP719[6].kind = 1;
TMP719[6].offset = offsetof(Baselexer159007, sentinel);
TMP719[6].typ = (&NTI104);
TMP719[6].name = "sentinel";
TMP957[6] = &TMP719[7];
TMP719[7].kind = 1;
TMP719[7].offset = offsetof(Baselexer159007, linestart);
TMP719[7].typ = (&NTI104);
TMP719[7].name = "lineStart";
TMP957[7] = &TMP719[8];
TMP719[8].kind = 1;
TMP719[8].offset = offsetof(Baselexer159007, refillchars);
TMP719[8].typ = (&NTI81210);
TMP719[8].name = "refillChars";
TMP719[0].len = 8; TMP719[0].kind = 2; TMP719[0].sons = &TMP957[0];
NTI159007.node = &TMP719[0];
}

