/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -g3 -O0  -IC:\Nim\lib -o y:\nimcode\simplepaint\src\nimcache\stdlib_winlean.o y:\nimcode\simplepaint\src\nimcache\stdlib_winlean.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct Guid111611 Guid111611;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct Filetime109255 Filetime109255;
typedef NI8 TY111625[8];
struct  Guid111611  {NI32 D1;
NI16 D2;
NI16 D3;
TY111625 D4;
};
typedef NI8 TY111688[8];
struct  TGenericSeq  {NI len;
NI reserved;
};
struct  NimStringDesc  {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(void, TY110610) (Filetime109255* lpsystemtimeasfiletime);
struct  Filetime109255  {NI32 dwlowdatetime;
NI32 dwhighdatetime;
};
typedef N_STDCALL_PTR(NI16*, TY110434) (void);

#line 106 "c:\\nim\\lib\\system\\dyncalls.nim"
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
#line 24 "c:\\nim\\lib\\system\\dyncalls.nim"
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
#line 109 "c:\\nim\\lib\\system\\dyncalls.nim"
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
#line 303 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 298 "c:\\nim\\lib\\system\\excpt.nim"
N_NOINLINE(void, stackoverflow_22201)(void);
#line 49 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void);NIM_CONST TY111688 TMP154 = {((NI8) -114),
((NI8) -23),
((NI8) 118),
((NI8) -27),
((NI8) -116),
((NI8) 116),
((NI8) 6),
((NI8) 62)}
;
NIM_CONST TY111688 TMP155 = {((NI8) -107),
((NI8) -54),
((NI8) 0),
((NI8) -128),
((NI8) 95),
((NI8) 72),
((NI8) -95),
((NI8) -110)}
;
STRING_LITERAL(TMP250, "kernel32", 8);
STRING_LITERAL(TMP251, "kernel32", 8);
Guid111611 Wsaidconnectex_111690;
Guid111611 Wsaidacceptex_111694;
Guid111611 Wsaidgetacceptexsockaddrs_111698;
static void* TMP249;
TY110610 Dl_110609;
extern TFrame* frameptr_19436;
TY110434 Dl_110433;


#line 303 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
	LOC1 = 0;
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
	{
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);	}
	goto LA2;
	LA4: ;
	{
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
#line 305 "c:\\nim\\lib\\system\\excpt.nim"
	(*s).prev = frameptr_19436;
#line 306 "c:\\nim\\lib\\system\\excpt.nim"
	frameptr_19436 = s;
#line 307 "c:\\nim\\lib\\system\\excpt.nim"
	{
#line 307 "c:\\nim\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;

#line 307 "c:\\nim\\lib\\system\\excpt.nim"
		stackoverflow_22201();
	}
	LA9: ;
}


#line 49 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 50 "c:\\nim\\lib\\system\\excpt.nim"
	frameptr_19436 = (*frameptr_19436).prev;}


#line 358 "c:\\nim\\lib\\windows\\winlean.nim"
N_NIMCALL(NI64, rdfiletime_110601)(Filetime109255 f) {
	NI64 result;
	nimfr("rdFileTime", "winlean.nim")
	result = 0;
#line 359 "c:\\nim\\lib\\windows\\winlean.nim"
	nimln(359, "winlean.nim");
#line 359 "c:\\nim\\lib\\windows\\winlean.nim"

#line 359 "c:\\nim\\lib\\windows\\winlean.nim"

#line 359 "c:\\nim\\lib\\windows\\winlean.nim"

#line 359 "c:\\nim\\lib\\windows\\winlean.nim"
	result = (NI64)(((NI64)(NU64)(NU32)(f.dwlowdatetime)) | (NI64)((NU64)(((NI64)(NU64)(NU32)(f.dwhighdatetime))) << (NU64)(IL64(32))));	popFrame();	return result;}
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit000)(void) {
	Guid111611 LOC1;	Guid111611 LOC2;	Guid111611 LOC3;	nimfr("winlean", "winlean.nim")

#line 771 "c:\\nim\\lib\\windows\\winlean.nim"
	nimln(771, "winlean.nim");	memset((void*)(&LOC1), 0, sizeof(LOC1));	LOC1.D1 = ((NI32) 631375801);	LOC1.D2 = ((NI16) -8717);	LOC1.D3 = ((NI16) 18016);	memcpy((void*)LOC1.D4, (NIM_CONST void*)TMP154, sizeof(TY111625));	Wsaidconnectex_111690 = LOC1;
#line 773 "c:\\nim\\lib\\windows\\winlean.nim"
	nimln(773, "winlean.nim");	memset((void*)(&LOC2), 0, sizeof(LOC2));	LOC2.D1 = ((NI32) -1254720015);	LOC2.D2 = ((NI16) -13396);	LOC2.D3 = ((NI16) 4559);	memcpy((void*)LOC2.D4, (NIM_CONST void*)TMP155, sizeof(TY111625));	Wsaidacceptex_111694 = LOC2;
#line 775 "c:\\nim\\lib\\windows\\winlean.nim"
	nimln(775, "winlean.nim");	memset((void*)(&LOC3), 0, sizeof(LOC3));	LOC3.D1 = ((NI32) -1254720014);	LOC3.D2 = ((NI16) -13396);	LOC3.D3 = ((NI16) 4559);	memcpy((void*)LOC3.D4, (NIM_CONST void*)TMP155, sizeof(TY111625));	Wsaidgetacceptexsockaddrs_111698 = LOC3;	popFrame();}

NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit000)(void) {
if (!((TMP249 = nimLoadLibrary((NimStringDesc*) &TMP250)))) nimLoadLibraryError((NimStringDesc*) &TMP251);	Dl_110609 = (TY110610) nimGetProcAddr(TMP249, "GetSystemTimeAsFileTime");	Dl_110433 = (TY110434) nimGetProcAddr(TMP249, "GetCommandLineW");}

