/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -g3 -O0  -IC:\Nim\lib -o y:\nimcode\simplepaint\src\nimcache\stdlib_parseutils.o y:\nimcode\simplepaint\src\nimcache\stdlib_parseutils.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Overflowerror3640 Overflowerror3640;
typedef struct Arithmeticerror3636 Arithmeticerror3636;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47704 Cell47704;
typedef struct Cellseq47720 Cellseq47720;
typedef struct Gcheap50018 Gcheap50018;
typedef struct Gcstack50016 Gcstack50016;
typedef struct Cellset47716 Cellset47716;
typedef struct Pagedesc47712 Pagedesc47712;
typedef struct Memregion29888 Memregion29888;
typedef struct Smallchunk29840 Smallchunk29840;
typedef struct Llchunk29882 Llchunk29882;
typedef struct Bigchunk29842 Bigchunk29842;
typedef struct Intset29814 Intset29814;
typedef struct Trunk29810 Trunk29810;
typedef struct Avlnode29886 Avlnode29886;
typedef struct Gcstat50014 Gcstat50014;
typedef struct Basechunk29838 Basechunk29838;
typedef struct Freecell29830 Freecell29830;
struct  TGenericSeq  {NI len;
NI reserved;
};
struct  NimStringDesc  {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimObject  {TNimType* m_type;};
struct  Exception  {  TNimObject Sup;Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Arithmeticerror3636  {  Exception Sup;};
struct  Overflowerror3640  {  Arithmeticerror3636 Sup;};
struct  TNimNode  {NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell47704  {NI refcount;
TNimType* typ;
};
struct  Cellseq47720  {NI len;
NI cap;
Cell47704** d;
};
struct  Cellset47716  {NI counter;
NI max;
Pagedesc47712* head;
Pagedesc47712** data;
};
typedef Smallchunk29840* TY29903[512];
typedef Trunk29810* Trunkbuckets29812[256];
struct  Intset29814  {Trunkbuckets29812 data;
};
struct  Memregion29888  {NI minlargeobj;
NI maxlargeobj;
TY29903 freesmallchunks;
Llchunk29882* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29842* freechunkslist;
Intset29814 chunkstarts;
Avlnode29886* root;
Avlnode29886* deleted;
Avlnode29886* last;
Avlnode29886* freeavlnodes;
};
struct  Gcstat50014  {NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap50018  {Gcstack50016* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47720 zct;
Cellseq47720 decstack;
Cellset47716 cycleroots;
Cellseq47720 tempstack;
NI recgclock;
Memregion29888 region;
Gcstat50014 stat;
};
struct  Gcstack50016  {Gcstack50016* prev;
Gcstack50016* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY29819[8];
struct  Pagedesc47712  {Pagedesc47712* next;
NI key;
TY29819 bits;
};
struct  Basechunk29838  {NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29840  {  Basechunk29838 Sup;Smallchunk29840* next;
Smallchunk29840* prev;
Freecell29830* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29882  {NI size;
NI acc;
Llchunk29882* next;
};
struct  Bigchunk29842  {  Basechunk29838 Sup;Bigchunk29842* next;
Bigchunk29842* prev;
NI align;
NF data;
};
struct  Trunk29810  {Trunk29810* next;
NI key;
TY29819 bits;
};
typedef Avlnode29886* TY29893[2];
struct  Avlnode29886  {TY29893 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell29830  {Freecell29830* next;
NI zerofield;
};

#line 213 "c:\\nim\\lib\\pure\\parseutils.nim"
N_NIMCALL(NI, npuParseBiggestInt)(NimStringDesc* s, NI64* number, NI start);
#line 195 "c:\\nim\\lib\\pure\\parseutils.nim"
N_NIMCALL(NI, rawparseint_99927)(NimStringDesc* s, NI64* b, NI start);
#line 18 "c:\\nim\\lib\\system\\chcks.nim"
N_NOINLINE(void, raiseIndexError)(void);
#line 319 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b);
#line 13 "c:\\nim\\lib\\system\\arithm.nim"
N_NOINLINE(void, raiseOverflow)(void);
#line 106 "c:\\nim\\lib\\system\\arithm.nim"
N_NIMCALL(NI64, mulInt64)(NI64 a, NI64 b);
#line 326 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b);
#line 80 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI64, subInt64)(NI64 a, NI64 b);
#line 303 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 298 "c:\\nim\\lib\\system\\excpt.nim"
N_NOINLINE(void, stackoverflow_22201)(void);
#line 49 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void);
#line 468 "c:\\nim\\lib\\system\\gc.nim"
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
#line 99 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
#line 244 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
#line 129 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(Cell47704*, usrtocell_51640)(void* usr);
#line 208 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, rtladdzct_53201)(Cell47704* c);
#line 120 "c:\\nim\\lib\\system\\gc.nim"
N_NOINLINE(void, addzct_51617)(Cellseq47720* s, Cell47704* c);
#line 263 "c:\\nim\\lib\\system\\excpt.nim"
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
#line 319 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(NI, nimParseBiggestFloat)(NimStringDesc* s, NF* number, NI start);
#line 237 "c:\\nim\\lib\\pure\\parseutils.nim"
N_NIMCALL(NI, nimParseBiggestFloat)(NimStringDesc* s, NF* number, NI start);STRING_LITERAL(TMP359, "overflow", 8);
extern TFrame* frameptr_19436;
extern TNimType NTI24269; /* ref OverflowError */
extern TNimType NTI3640; /* OverflowError */
extern Gcheap50018 gch_50059;


#line 319 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 320 "c:\\nim\\lib\\system\\arithm.nim"

#line 320 "c:\\nim\\lib\\system\\arithm.nim"
	result = (NI)((NU64)(a) + (NU64)(b));
#line 321 "c:\\nim\\lib\\system\\arithm.nim"
	{		NIM_BOOL LOC3;
#line 321 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = 0;
#line 353 "c:\\nim\\lib\\system.nim"

#line 321 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ a));		if (LOC3) goto LA4;

#line 353 "c:\\nim\\lib\\system.nim"

#line 321 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ b));		LA4: ;
		if (!LOC3) goto LA5;

#line 322 "c:\\nim\\lib\\system\\arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 323 "c:\\nim\\lib\\system\\arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 326 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 327 "c:\\nim\\lib\\system\\arithm.nim"

#line 327 "c:\\nim\\lib\\system\\arithm.nim"
	result = (NI)((NU64)(a) - (NU64)(b));
#line 328 "c:\\nim\\lib\\system\\arithm.nim"
	{		NIM_BOOL LOC3;
#line 328 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = 0;
#line 353 "c:\\nim\\lib\\system.nim"

#line 328 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ a));		if (LOC3) goto LA4;

#line 353 "c:\\nim\\lib\\system.nim"

#line 328 "c:\\nim\\lib\\system\\arithm.nim"

#line 328 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));		LA4: ;
		if (!LOC3) goto LA5;

#line 329 "c:\\nim\\lib\\system\\arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 330 "c:\\nim\\lib\\system\\arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 80 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI64, subInt64)(NI64 a, NI64 b) {
	NI64 result;
{	result = 0;
#line 81 "c:\\nim\\lib\\system\\arithm.nim"

#line 81 "c:\\nim\\lib\\system\\arithm.nim"
	result = (NI64)((NU64)(a) - (NU64)(b));
#line 82 "c:\\nim\\lib\\system\\arithm.nim"
	{		NIM_BOOL LOC3;
#line 82 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = 0;
#line 353 "c:\\nim\\lib\\system.nim"

#line 82 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (IL64(0) <= (NI64)(result ^ a));		if (LOC3) goto LA4;

#line 353 "c:\\nim\\lib\\system.nim"

#line 82 "c:\\nim\\lib\\system\\arithm.nim"

#line 82 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (IL64(0) <= (NI64)(result ^ (NI64)((NU64) ~(b))));		LA4: ;
		if (!LOC3) goto LA5;

#line 83 "c:\\nim\\lib\\system\\arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 84 "c:\\nim\\lib\\system\\arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 303 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
	LOC1 = 0;
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
	{
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);	}
	goto LA2;
	LA4: ;
	{
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
#line 305 "c:\\nim\\lib\\system\\excpt.nim"
	(*s).prev = frameptr_19436;
#line 306 "c:\\nim\\lib\\system\\excpt.nim"
	frameptr_19436 = s;
#line 307 "c:\\nim\\lib\\system\\excpt.nim"
	{
#line 307 "c:\\nim\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;

#line 307 "c:\\nim\\lib\\system\\excpt.nim"
		stackoverflow_22201();
	}
	LA9: ;
}


#line 49 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 50 "c:\\nim\\lib\\system\\excpt.nim"
	frameptr_19436 = (*frameptr_19436).prev;}


#line 195 "c:\\nim\\lib\\pure\\parseutils.nim"
N_NIMCALL(NI, rawparseint_99927)(NimStringDesc* s, NI64* b, NI start) {
	NI result;
	NI64 sign;
	NI i;
	nimfr("rawParseInt", "parseutils.nim")
	result = 0;
#line 197 "c:\\nim\\lib\\pure\\parseutils.nim"
	nimln(197, "parseutils.nim");	sign = IL64(-1);
#line 198 "c:\\nim\\lib\\pure\\parseutils.nim"
	nimln(198, "parseutils.nim");	i = start;
#line 199 "c:\\nim\\lib\\pure\\parseutils.nim"
	nimln(199, "parseutils.nim");	{		NI TMP350;
#line 199 "c:\\nim\\lib\\pure\\parseutils.nim"
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();		if (!((NU8)(s->data[i]) == (NU8)(43))) goto LA3;

#line 199 "c:\\nim\\lib\\pure\\parseutils.nim"
		TMP350 = addInt(i, ((NI) 1));		i = (NI)(TMP350);	}
	goto LA1;
	LA3: ;
	{		NI TMP351;
#line 200 "c:\\nim\\lib\\pure\\parseutils.nim"
		nimln(200, "parseutils.nim");		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();		if (!((NU8)(s->data[i]) == (NU8)(45))) goto LA6;

#line 201 "c:\\nim\\lib\\pure\\parseutils.nim"
		nimln(201, "parseutils.nim");		TMP351 = addInt(i, ((NI) 1));		i = (NI)(TMP351);
#line 202 "c:\\nim\\lib\\pure\\parseutils.nim"
		nimln(202, "parseutils.nim");		sign = IL64(1);	}
	goto LA1;
	LA6: ;
	LA1: ;

#line 203 "c:\\nim\\lib\\pure\\parseutils.nim"
	nimln(203, "parseutils.nim");	{		NI64 TMP357;		NI TMP358;
#line 1098 "c:\\nim\\lib\\system.nim"
		nimln(1098, "system.nim");		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();		if (!(((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)))) goto LA10;

#line 204 "c:\\nim\\lib\\pure\\parseutils.nim"
		nimln(204, "parseutils.nim");		(*b) = IL64(0);		{
#line 205 "c:\\nim\\lib\\pure\\parseutils.nim"
			nimln(205, "parseutils.nim");			while (1) {				NI64 TMP352;				NI TMP353;				NI64 TMP354;				NI TMP355;
#line 1098 "c:\\nim\\lib\\system.nim"
				nimln(1098, "system.nim");				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();				if (!(((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)))) goto LA13;

#line 206 "c:\\nim\\lib\\pure\\parseutils.nim"
				nimln(206, "parseutils.nim");
#line 206 "c:\\nim\\lib\\pure\\parseutils.nim"

#line 206 "c:\\nim\\lib\\pure\\parseutils.nim"
				TMP352 = mulInt64((*b), IL64(10));
#line 206 "c:\\nim\\lib\\pure\\parseutils.nim"

#line 206 "c:\\nim\\lib\\pure\\parseutils.nim"
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();				TMP353 = subInt(((NI) (((NU8)(s->data[i])))), ((NI) 48));				TMP354 = subInt64((NI64)(TMP352), ((NI64) ((NI)(TMP353))));				(*b) = (NI64)(TMP354);
#line 207 "c:\\nim\\lib\\pure\\parseutils.nim"
				nimln(207, "parseutils.nim");				TMP355 = addInt(i, ((NI) 1));				i = (NI)(TMP355);				{
#line 208 "c:\\nim\\lib\\pure\\parseutils.nim"
					nimln(208, "parseutils.nim");					while (1) {						NI TMP356;
#line 208 "c:\\nim\\lib\\pure\\parseutils.nim"
						if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();						if (!((NU8)(s->data[i]) == (NU8)(95))) goto LA15;

#line 208 "c:\\nim\\lib\\pure\\parseutils.nim"
						TMP356 = addInt(i, ((NI) 1));						i = (NI)(TMP356);					} LA15: ;				}
			} LA13: ;		}

#line 209 "c:\\nim\\lib\\pure\\parseutils.nim"
		nimln(209, "parseutils.nim");
#line 209 "c:\\nim\\lib\\pure\\parseutils.nim"
		TMP357 = mulInt64((*b), sign);		(*b) = (NI64)(TMP357);
#line 210 "c:\\nim\\lib\\pure\\parseutils.nim"
		nimln(210, "parseutils.nim");
#line 210 "c:\\nim\\lib\\pure\\parseutils.nim"
		TMP358 = subInt(i, start);		result = (NI)(TMP358);	}
	LA10: ;
	popFrame();	return result;}


#line 213 "c:\\nim\\lib\\pure\\parseutils.nim"
N_NIMCALL(NI, npuParseBiggestInt)(NimStringDesc* s, NI64* number, NI start) {
	NI result;
	NI64 res;
	nimfr("parseBiggestInt", "parseutils.nim")
	result = 0;	res = 0;
#line 221 "c:\\nim\\lib\\pure\\parseutils.nim"
	nimln(221, "parseutils.nim");	result = rawparseint_99927(s, (&res), start);
#line 222 "c:\\nim\\lib\\pure\\parseutils.nim"
	nimln(222, "parseutils.nim");	(*number) = res;	popFrame();	return result;}


#line 129 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(Cell47704*, usrtocell_51640)(void* usr) {
	Cell47704* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
#line 131 "c:\\nim\\lib\\system\\gc.nim"
	nimln(131, "gc.nim");
#line 131 "c:\\nim\\lib\\system\\gc.nim"

#line 131 "c:\\nim\\lib\\system\\gc.nim"
	result = ((Cell47704*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47704))))));	popFrame();	return result;}


#line 208 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, rtladdzct_53201)(Cell47704* c) {
	nimfr("rtlAddZCT", "gc.nim")

#line 212 "c:\\nim\\lib\\system\\gc.nim"
	nimln(212, "gc.nim");	addzct_51617((&gch_50059.zct), c);
	popFrame();}


#line 244 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell47704* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")

#line 246 "c:\\nim\\lib\\system\\gc.nim"
	nimln(246, "gc.nim");	c = usrtocell_51640(p);
#line 248 "c:\\nim\\lib\\system\\gc.nim"
	nimln(248, "gc.nim");	{
#line 180 "c:\\nim\\lib\\system\\gc.nim"
		nimln(180, "gc.nim");		(*c).refcount -= ((NI) 8);
#line 181 "c:\\nim\\lib\\system\\gc.nim"
		nimln(181, "gc.nim");		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;

#line 249 "c:\\nim\\lib\\system\\gc.nim"
		nimln(249, "gc.nim");		rtladdzct_53201(c);
	}
	LA3: ;
	popFrame();}


#line 224 "c:\\nim\\lib\\pure\\parseutils.nim"
N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start) {
	NI result;
	NI64 res;
	nimfr("parseInt", "parseutils.nim")
	result = 0;	res = 0;
#line 230 "c:\\nim\\lib\\pure\\parseutils.nim"
	nimln(230, "parseutils.nim");	result = npuParseBiggestInt(s, (&res), start);
#line 231 "c:\\nim\\lib\\pure\\parseutils.nim"
	nimln(231, "parseutils.nim");	{		NIM_BOOL LOC3;		NIM_BOOL LOC5;		Overflowerror3640* e_100041;
		NimStringDesc* LOC9;
#line 231 "c:\\nim\\lib\\pure\\parseutils.nim"
		LOC3 = 0;		LOC3 = NIM_FALSE;		if (!(LOC3)) goto LA4;

#line 232 "c:\\nim\\lib\\pure\\parseutils.nim"
		nimln(232, "parseutils.nim");		LOC5 = 0;
#line 232 "c:\\nim\\lib\\pure\\parseutils.nim"
		LOC5 = (res < (IL64(-9223372036854775807) - IL64(1)));		if (LOC5) goto LA6;

#line 357 "c:\\nim\\lib\\system.nim"
		nimln(357, "system.nim");		LOC5 = (IL64(9223372036854775807) < res);		LA6: ;
		LOC3 = LOC5;		LA4: ;
		if (!LOC3) goto LA7;
		e_100041 = 0;
#line 2507 "c:\\nim\\lib\\system.nim"
		nimln(2507, "system.nim");		e_100041 = (Overflowerror3640*) newObj((&NTI24269), sizeof(Overflowerror3640));		(*e_100041).Sup.Sup.Sup.m_type = (&NTI3640);
#line 2508 "c:\\nim\\lib\\system.nim"
		nimln(2508, "system.nim");		LOC9 = 0;		LOC9 = (*e_100041).Sup.Sup.message; (*e_100041).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP359));		if (LOC9) nimGCunrefNoCycle(LOC9);
#line 233 "c:\\nim\\lib\\pure\\parseutils.nim"
		nimln(233, "parseutils.nim");		raiseException((Exception*)e_100041, "OverflowError");	}
	goto LA1;
	LA7: ;
	{
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
		if (!!((result == ((NI) 0)))) goto LA11;

#line 235 "c:\\nim\\lib\\pure\\parseutils.nim"
		nimln(235, "parseutils.nim");		(*number) = ((NI) (res));	}
	goto LA1;
	LA11: ;
	LA1: ;
	popFrame();	return result;}


#line 243 "c:\\nim\\lib\\pure\\parseutils.nim"
N_NIMCALL(NI, npuParseFloat)(NimStringDesc* s, NF* number, NI start) {
	NI result;
	NF bf;
	nimfr("parseFloat", "parseutils.nim")
	result = 0;	bf = 0;
#line 249 "c:\\nim\\lib\\pure\\parseutils.nim"
	nimln(249, "parseutils.nim");
#line 249 "c:\\nim\\lib\\pure\\parseutils.nim"
	result = nimParseBiggestFloat(s, (&bf), start);
#line 250 "c:\\nim\\lib\\pure\\parseutils.nim"
	nimln(250, "parseutils.nim");	{
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
		if (!!((result == ((NI) 0)))) goto LA3;

#line 251 "c:\\nim\\lib\\pure\\parseutils.nim"
		nimln(251, "parseutils.nim");		(*number) = bf;	}
	LA3: ;
	popFrame();	return result;}
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void) {
	nimfr("parseutils", "parseutils.nim")
	popFrame();}

NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void) {
}

