/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -g3 -O0  -IC:\Nim\lib -o y:\nimcode\simplepaint\src\nimcache\stdlib_streams.o y:\nimcode\simplepaint\src\nimcache\stdlib_streams.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <setjmp.h>
#include <string.h>
#include <stdio.h>
typedef struct Ioerror3628 Ioerror3628;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Systemerror3626 Systemerror3626;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47704 Cell47704;
typedef struct Cellseq47720 Cellseq47720;
typedef struct Gcheap50018 Gcheap50018;
typedef struct Gcstack50016 Gcstack50016;
typedef struct Cellset47716 Cellset47716;
typedef struct Pagedesc47712 Pagedesc47712;
typedef struct Memregion29888 Memregion29888;
typedef struct Smallchunk29840 Smallchunk29840;
typedef struct Llchunk29882 Llchunk29882;
typedef struct Bigchunk29842 Bigchunk29842;
typedef struct Intset29814 Intset29814;
typedef struct Trunk29810 Trunk29810;
typedef struct Avlnode29886 Avlnode29886;
typedef struct Gcstat50014 Gcstat50014;
typedef struct Streamobj142218 Streamobj142218;
typedef struct TSafePoint TSafePoint;
typedef struct Stringstreamobj142949 Stringstreamobj142949;
typedef struct Filestreamobj143048 Filestreamobj143048;
typedef struct Basechunk29838 Basechunk29838;
typedef struct Freecell29830 Freecell29830;
struct  TGenericSeq  {NI len;
NI reserved;
};
struct  NimStringDesc  {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimObject  {TNimType* m_type;};
struct  Exception  {  TNimObject Sup;Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Systemerror3626  {  Exception Sup;};
struct  Ioerror3628  {  Systemerror3626 Sup;};
struct  TNimNode  {NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell47704  {NI refcount;
TNimType* typ;
};
struct  Cellseq47720  {NI len;
NI cap;
Cell47704** d;
};
struct  Cellset47716  {NI counter;
NI max;
Pagedesc47712* head;
Pagedesc47712** data;
};
typedef Smallchunk29840* TY29903[512];
typedef Trunk29810* Trunkbuckets29812[256];
struct  Intset29814  {Trunkbuckets29812 data;
};
struct  Memregion29888  {NI minlargeobj;
NI maxlargeobj;
TY29903 freesmallchunks;
Llchunk29882* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29842* freechunkslist;
Intset29814 chunkstarts;
Avlnode29886* root;
Avlnode29886* deleted;
Avlnode29886* last;
Avlnode29886* freeavlnodes;
};
struct  Gcstat50014  {NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap50018  {Gcstack50016* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47720 zct;
Cellseq47720 decstack;
Cellset47716 cycleroots;
Cellseq47720 tempstack;
NI recgclock;
Memregion29888 region;
Gcstat50014 stat;
};
typedef N_NIMCALL_PTR(void, TY142219) (Streamobj142218* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY142223) (Streamobj142218* s);
typedef N_NIMCALL_PTR(void, TY142227) (Streamobj142218* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY142232) (Streamobj142218* s);
typedef N_NIMCALL_PTR(NI, TY142236) (Streamobj142218* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(NI, TY142242) (Streamobj142218* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY142248) (Streamobj142218* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY142254) (Streamobj142218* s);
struct  Streamobj142218  {  TNimObject Sup;TY142219 closeimpl;
TY142223 atendimpl;
TY142227 setpositionimpl;
TY142232 getpositionimpl;
TY142236 readdataimpl;
TY142242 peekdataimpl;
TY142248 writedataimpl;
TY142254 flushimpl;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY17811;
struct  TSafePoint  {TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY17811 raiseAction;
};
struct  Stringstreamobj142949  {  Streamobj142218 Sup;NimStringDesc* data;
NI pos;
};
struct  Filestreamobj143048  {  Streamobj142218 Sup;FILE* f;
};
struct  Gcstack50016  {Gcstack50016* prev;
Gcstack50016* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY29819[8];
struct  Pagedesc47712  {Pagedesc47712* next;
NI key;
TY29819 bits;
};
struct  Basechunk29838  {NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29840  {  Basechunk29838 Sup;Smallchunk29840* next;
Smallchunk29840* prev;
Freecell29830* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29882  {NI size;
NI acc;
Llchunk29882* next;
};
struct  Bigchunk29842  {  Basechunk29838 Sup;Bigchunk29842* next;
Bigchunk29842* prev;
NI align;
NF data;
};
struct  Trunk29810  {Trunk29810* next;
NI key;
TY29819 bits;
};
typedef Avlnode29886* TY29893[2];
struct  Avlnode29886  {TY29893 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell29830  {Freecell29830* next;
NI zerofield;
};

#line 37 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(Ioerror3628*, neweio_142202)(NimStringDesc* msg);
#line 468 "c:\\nim\\lib\\system\\gc.nim"
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
#line 99 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
#line 244 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
#line 129 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(Cell47704*, usrtocell_51640)(void* usr);
#line 303 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 298 "c:\\nim\\lib\\system\\excpt.nim"
N_NOINLINE(void, stackoverflow_22201)(void);
#line 49 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void);
#line 208 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, rtladdzct_53201)(Cell47704* c);
#line 120 "c:\\nim\\lib\\system\\gc.nim"
N_NOINLINE(void, addzct_51617)(Cellseq47720* s, Cell47704* c);
#line 62 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, flush_142260)(Streamobj142218* s);
#line 66 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, close_142270)(Streamobj142218* s);
#line 70 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, close_142280)(Streamobj142218* s, Streamobj142218* unused);
#line 74 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_BOOL, atend_142284)(Streamobj142218* s);
#line 79 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_BOOL, atend_142288)(Streamobj142218* s, Streamobj142218* unused);
#line 84 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, setposition_142293)(Streamobj142218* s, NI pos);
#line 88 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, setposition_142297)(Streamobj142218* s, Streamobj142218* unused, NI pos);
#line 92 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, getposition_142302)(Streamobj142218* s);
#line 96 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, getposition_142306)(Streamobj142218* s, Streamobj142218* unused);
#line 100 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, readdata_142311)(Streamobj142218* s, void* buffer, NI buflen);
#line 104 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NimStringDesc*, readall_142317)(Streamobj142218* s);
#line 64 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
#line 1175 "c:\\nim\\lib\\system.nim"
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
#line 18 "c:\\nim\\lib\\system\\chcks.nim"
N_NOINLINE(void, raiseIndexError)(void);
#line 319 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b);
#line 13 "c:\\nim\\lib\\system\\arithm.nim"
N_NOINLINE(void, raiseOverflow)(void);
#line 30 "c:\\nim\\lib\\system\\chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
#line 12 "c:\\nim\\lib\\system\\chcks.nim"
N_NOINLINE(void, raiseRangeError)(NI64 val);
#line 188 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
#line 117 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, readdata_142336)(Streamobj142218* s, Streamobj142218* unused, void* buffer, NI buflen);
#line 122 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, peekdata_142343)(Streamobj142218* s, void* buffer, NI buflen);
#line 127 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, writedata_142349)(Streamobj142218* s, void* buffer, NI buflen);
#line 132 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, writedata_142354)(Streamobj142218* s, Streamobj142218* unused, void* buffer, NI buflen);
#line 148 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, write_142369)(Streamobj142218* s, NimStringDesc* x);
#line 153 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, writeln_142373)(Streamobj142218* s, NimStringDesc** args, NI argsLen0);
#line 158 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, writeline_142390)(Streamobj142218* s, NimStringDesc** args, NI argsLen0);
#line 174 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_CHAR, readchar_142426)(Streamobj142218* s);
#line 179 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_CHAR, peekchar_142431)(Streamobj142218* s);
#line 164 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, read_142441)(Streamobj142218* s, NIM_BOOL* result);
#line 263 "c:\\nim\\lib\\system\\excpt.nim"
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
#line 184 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_BOOL, readbool_142436)(Streamobj142218* s);
#line 169 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, peek_142474)(Streamobj142218* s, NIM_BOOL* result);
#line 188 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_BOOL, peekbool_142469)(Streamobj142218* s);
#line 164 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, read_142507)(Streamobj142218* s, NI8* result);
#line 192 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI8, readint8_142502)(Streamobj142218* s);
#line 169 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, peek_142540)(Streamobj142218* s, NI8* result);
#line 196 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI8, peekint8_142535)(Streamobj142218* s);
#line 164 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, read_142573)(Streamobj142218* s, NI16* result);
#line 200 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI16, readint16_142568)(Streamobj142218* s);
#line 169 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, peek_142606)(Streamobj142218* s, NI16* result);
#line 204 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI16, peekint16_142601)(Streamobj142218* s);
#line 164 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, read_142639)(Streamobj142218* s, NI32* result);
#line 208 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI32, readint32_142634)(Streamobj142218* s);
#line 169 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, peek_142672)(Streamobj142218* s, NI32* result);
#line 212 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI32, peekint32_142667)(Streamobj142218* s);
#line 164 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, read_142705)(Streamobj142218* s, NI64* result);
#line 216 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI64, readint64_142700)(Streamobj142218* s);
#line 169 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, peek_142738)(Streamobj142218* s, NI64* result);
#line 220 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI64, peekint64_142733)(Streamobj142218* s);
#line 164 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, read_142771)(Streamobj142218* s, NF32* result);
#line 224 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NF32, readfloat32_142766)(Streamobj142218* s);
#line 169 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, peek_142804)(Streamobj142218* s, NF32* result);
#line 228 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NF32, peekfloat32_142799)(Streamobj142218* s);
#line 164 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, read_142837)(Streamobj142218* s, NF* result);
#line 232 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NF, readfloat64_142832)(Streamobj142218* s);
#line 169 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, peek_142870)(Streamobj142218* s, NF* result);
#line 236 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NF, peekfloat64_142865)(Streamobj142218* s);
#line 240 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NimStringDesc*, readstr_142898)(Streamobj142218* s, NI length);
#line 247 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NimStringDesc*, peekstr_142907)(Streamobj142218* s, NI length);
#line 254 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_BOOL, readline_142916)(Streamobj142218* s, NimStringDesc** line);
#line 126 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
#line 274 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_BOOL, peekline_142926)(Streamobj142218* s, NimStringDesc** line);
#line 55 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
#line 60 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popSafePoint)(void);
#line 52 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, setFrame)(TFrame* s);
#line 270 "c:\\nim\\lib\\system\\excpt.nim"
N_NIMCALL(void, reraiseException)(void);
#line 285 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NimStringDesc*, readline_142933)(Streamobj142218* s);
#line 90 "c:\\nim\\lib\\system\\sysstr.nim"
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
#line 299 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NimStringDesc*, peekline_142941)(Streamobj142218* s);
#line 314 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_BOOL, ssatend_142954)(Streamobj142218* s_142956);
#line 56 "c:\\nim\\lib\\system\\chcks.nim"
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
#line 1953 "c:\\nim\\lib\\system.nim"
N_NIMCALL(NI, clamp_142965)(NI x, NI a, NI b);
#line 318 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, sssetposition_142959)(Streamobj142218* s_142961, NI pos);
#line 322 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, ssgetposition_142975)(Streamobj142218* s_142977);
#line 326 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, ssreaddata_142980)(Streamobj142218* s_142982, void* buffer, NI buflen);
#line 326 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b);
#line 333 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, sspeekdata_143001)(Streamobj142218* s_143003, void* buffer, NI buflen);
#line 339 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, sswritedata_143013)(Streamobj142218* s_143015, void* buffer, NI buflen);
#line 348 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, ssclose_143029)(Streamobj142218* s_143031);
#line 352 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(Stringstreamobj142949*, newstringstream_143033)(NimStringDesc* s);
#line 735 "c:\\nim\\lib\\system\\gc.nim"
N_NIMCALL(void, nimGCvisit)(void* d, NI op);N_NIMCALL(void, TMP627)(void* p, NI op);

#line 373 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, fsclose_143052)(Streamobj142218* s);
#line 377 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, fsflush_143067)(Streamobj142218* s);
#line 378 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_BOOL, fsatend_143070)(Streamobj142218* s);
#line 205 "c:\\nim\\lib\\system\\sysio.nim"
N_NIMCALL(NIM_BOOL, endoffile_15454)(FILE* f);
#line 379 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, fssetposition_143074)(Streamobj142218* s, NI pos);
#line 314 "c:\\nim\\lib\\system\\sysio.nim"
N_NIMCALL(void, setfilepos_15581)(FILE* f, NI64 pos);
#line 380 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, fsgetposition_143078)(Streamobj142218* s);
#line 318 "c:\\nim\\lib\\system\\sysio.nim"
N_NIMCALL(NI64, getfilepos_15585)(FILE* f);
#line 382 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, fsreaddata_143083)(Streamobj142218* s, void* buffer, NI buflen);
#line 290 "c:\\nim\\lib\\system\\sysio.nim"
N_NIMCALL(NI, readbuffer_15554)(FILE* f, void* buffer, NI len);
#line 385 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, fspeekdata_143089)(Streamobj142218* s, void* buffer, NI buflen);
#line 390 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, fswritedata_143096)(Streamobj142218* s, void* buffer, NI buflen);
#line 306 "c:\\nim\\lib\\system\\sysio.nim"
N_NIMCALL(NI, writebuffer_15576)(FILE* f, void* buffer, NI len);
#line 394 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(Filestreamobj143048*, newfilestream_143101)(FILE* f);N_NIMCALL(void, TMP630)(void* p, NI op);

#line 407 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(Filestreamobj143048*, newfilestream_143113)(NimStringDesc* filename, NU8 mode);
#line 264 "c:\\nim\\lib\\system\\sysio.nim"
N_NIMCALL(NIM_BOOL, open_15403)(FILE** f, NimStringDesc* filename, NU8 mode, NI bufsize);N_NIMCALL(void, TMP968)(void* p, NI op);
STRING_LITERAL(TMP613, "\015\012", 2);
STRING_LITERAL(TMP615, "cannot read from stream", 23);
STRING_LITERAL(TMP617, "", 0);
STRING_LITERAL(TMP629, "cannot write to stream", 22);
extern TNimType NTI15435; /* ref IOError */
extern TNimType NTI3628; /* IOError */
extern TFrame* frameptr_19436;
extern Gcheap50018 gch_50059;
extern TSafePoint* exchandler_19437;
extern TNimType NTI3608; /* RootObj */
TNimType NTI142218; /* StreamObj */
TNimType NTI142219; /* proc (s: Stream){.gcsafe.} */
TNimType NTI142223; /* proc (s: Stream): bool{.gcsafe.} */
TNimType NTI142227; /* proc (s: Stream, pos: int){.gcsafe.} */
TNimType NTI142232; /* proc (s: Stream): int{.gcsafe.} */
TNimType NTI142236; /* proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe.} */
TNimType NTI142242; /* proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe.} */
TNimType NTI142248; /* proc (s: Stream, buffer: pointer, bufLen: int){.gcsafe.} */
TNimType NTI142254; /* proc (s: Stream){.gcsafe.} */
TNimType NTI142949; /* StringStreamObj */
extern TNimType NTI138; /* string */
extern TNimType NTI104; /* int */
TNimType NTI142947; /* StringStream */
TNimType NTI143048; /* FileStreamObj */
extern TNimType NTI15004; /* File */
TNimType NTI143046; /* FileStream */
TNimType NTI142216; /* Stream */


#line 303 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
	LOC1 = 0;
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
	{
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);	}
	goto LA2;
	LA4: ;
	{
#line 304 "c:\\nim\\lib\\system\\excpt.nim"
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
#line 305 "c:\\nim\\lib\\system\\excpt.nim"
	(*s).prev = frameptr_19436;
#line 306 "c:\\nim\\lib\\system\\excpt.nim"
	frameptr_19436 = s;
#line 307 "c:\\nim\\lib\\system\\excpt.nim"
	{
#line 307 "c:\\nim\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;

#line 307 "c:\\nim\\lib\\system\\excpt.nim"
		stackoverflow_22201();
	}
	LA9: ;
}


#line 49 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 50 "c:\\nim\\lib\\system\\excpt.nim"
	frameptr_19436 = (*frameptr_19436).prev;}


#line 129 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(Cell47704*, usrtocell_51640)(void* usr) {
	Cell47704* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
#line 131 "c:\\nim\\lib\\system\\gc.nim"
	nimln(131, "gc.nim");
#line 131 "c:\\nim\\lib\\system\\gc.nim"

#line 131 "c:\\nim\\lib\\system\\gc.nim"
	result = ((Cell47704*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47704))))));	popFrame();	return result;}


#line 208 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, rtladdzct_53201)(Cell47704* c) {
	nimfr("rtlAddZCT", "gc.nim")

#line 212 "c:\\nim\\lib\\system\\gc.nim"
	nimln(212, "gc.nim");	addzct_51617((&gch_50059.zct), c);
	popFrame();}


#line 244 "c:\\nim\\lib\\system\\gc.nim"
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell47704* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")

#line 246 "c:\\nim\\lib\\system\\gc.nim"
	nimln(246, "gc.nim");	c = usrtocell_51640(p);
#line 248 "c:\\nim\\lib\\system\\gc.nim"
	nimln(248, "gc.nim");	{
#line 180 "c:\\nim\\lib\\system\\gc.nim"
		nimln(180, "gc.nim");		(*c).refcount -= ((NI) 8);
#line 181 "c:\\nim\\lib\\system\\gc.nim"
		nimln(181, "gc.nim");		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;

#line 249 "c:\\nim\\lib\\system\\gc.nim"
		nimln(249, "gc.nim");		rtladdzct_53201(c);
	}
	LA3: ;
	popFrame();}


#line 37 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(Ioerror3628*, neweio_142202)(NimStringDesc* msg) {
	Ioerror3628* result;
	NimStringDesc* LOC1;	nimfr("newEIO", "streams.nim")
	result = 0;
#line 38 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(38, "streams.nim");	result = (Ioerror3628*) newObj((&NTI15435), sizeof(Ioerror3628));	(*result).Sup.Sup.Sup.m_type = (&NTI3628);
#line 39 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(39, "streams.nim");	LOC1 = 0;	LOC1 = (*result).Sup.Sup.message; (*result).Sup.Sup.message = copyStringRC1(msg);	if (LOC1) nimGCunrefNoCycle(LOC1);	popFrame();	return result;}


#line 62 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, flush_142260)(Streamobj142218* s) {
	nimfr("flush", "streams.nim")

#line 64 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(64, "streams.nim");	{
#line 64 "c:\\nim\\lib\\pure\\streams.nim"

#line 64 "c:\\nim\\lib\\pure\\streams.nim"
		if (!!((*s).flushimpl == 0)) goto LA3;

#line 64 "c:\\nim\\lib\\pure\\streams.nim"
		(*s).flushimpl(s);
	}
	LA3: ;
	popFrame();}


#line 66 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, close_142270)(Streamobj142218* s) {
	nimfr("close", "streams.nim")

#line 68 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(68, "streams.nim");	{
#line 68 "c:\\nim\\lib\\pure\\streams.nim"

#line 68 "c:\\nim\\lib\\pure\\streams.nim"
		if (!!((*s).closeimpl == 0)) goto LA3;

#line 68 "c:\\nim\\lib\\pure\\streams.nim"
		(*s).closeimpl(s);
	}
	LA3: ;
	popFrame();}


#line 70 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, close_142280)(Streamobj142218* s, Streamobj142218* unused) {
	nimfr("close", "streams.nim")

#line 72 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(72, "streams.nim");	(*s).closeimpl(s);
	popFrame();}


#line 74 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_BOOL, atend_142284)(Streamobj142218* s) {
	NIM_BOOL result;
	nimfr("atEnd", "streams.nim")
	result = 0;
#line 77 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(77, "streams.nim");	result = (*s).atendimpl(s);	popFrame();	return result;}


#line 79 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_BOOL, atend_142288)(Streamobj142218* s, Streamobj142218* unused) {
	NIM_BOOL result;
	nimfr("atEnd", "streams.nim")
	result = 0;
#line 82 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(82, "streams.nim");	result = (*s).atendimpl(s);	popFrame();	return result;}


#line 84 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, setposition_142293)(Streamobj142218* s, NI pos) {
	nimfr("setPosition", "streams.nim")

#line 86 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(86, "streams.nim");	(*s).setpositionimpl(s, pos);
	popFrame();}


#line 88 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, setposition_142297)(Streamobj142218* s, Streamobj142218* unused, NI pos) {
	nimfr("setPosition", "streams.nim")

#line 90 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(90, "streams.nim");	(*s).setpositionimpl(s, pos);
	popFrame();}


#line 92 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, getposition_142302)(Streamobj142218* s) {
	NI result;
	nimfr("getPosition", "streams.nim")
	result = 0;
#line 94 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(94, "streams.nim");	result = (*s).getpositionimpl(s);	popFrame();	return result;}


#line 96 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, getposition_142306)(Streamobj142218* s, Streamobj142218* unused) {
	NI result;
	nimfr("getPosition", "streams.nim")
	result = 0;
#line 98 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(98, "streams.nim");	result = (*s).getpositionimpl(s);	popFrame();	return result;}


#line 100 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, readdata_142311)(Streamobj142218* s, void* buffer, NI buflen) {
	NI result;
	nimfr("readData", "streams.nim")
	result = 0;
#line 102 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(102, "streams.nim");	result = (*s).readdataimpl(s, buffer, buflen);	popFrame();	return result;}


#line 319 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 320 "c:\\nim\\lib\\system\\arithm.nim"

#line 320 "c:\\nim\\lib\\system\\arithm.nim"
	result = (NI)((NU64)(a) + (NU64)(b));
#line 321 "c:\\nim\\lib\\system\\arithm.nim"
	{		NIM_BOOL LOC3;
#line 321 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = 0;
#line 353 "c:\\nim\\lib\\system.nim"

#line 321 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ a));		if (LOC3) goto LA4;

#line 353 "c:\\nim\\lib\\system.nim"

#line 321 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ b));		LA4: ;
		if (!LOC3) goto LA5;

#line 322 "c:\\nim\\lib\\system\\arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 323 "c:\\nim\\lib\\system\\arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 30 "c:\\nim\\lib\\system\\chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
#line 31 "c:\\nim\\lib\\system\\chcks.nim"
	{		NIM_BOOL LOC3;
#line 31 "c:\\nim\\lib\\system\\chcks.nim"
		LOC3 = 0;
#line 353 "c:\\nim\\lib\\system.nim"
		LOC3 = (a <= i);		if (!(LOC3)) goto LA4;

#line 31 "c:\\nim\\lib\\system\\chcks.nim"
		LOC3 = (i <= b);		LA4: ;
		if (!LOC3) goto LA5;

#line 32 "c:\\nim\\lib\\system\\chcks.nim"

#line 32 "c:\\nim\\lib\\system\\chcks.nim"
		result = i;		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
#line 34 "c:\\nim\\lib\\system\\chcks.nim"
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;}


#line 104 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NimStringDesc*, readall_142317)(Streamobj142218* s) {
	NimStringDesc* result;
	NI r;
	nimfr("readAll", "streams.nim")
	result = 0;
#line 107 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(107, "streams.nim");
#line 107 "c:\\nim\\lib\\pure\\streams.nim"
	result = mnewString(((NI) 1000));
#line 108 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(108, "streams.nim");	r = ((NI) 0);	{
#line 109 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(109, "streams.nim");		while (1) {			NI readbytes;
			NI TMP610;			NI TMP611;
#line 110 "c:\\nim\\lib\\pure\\streams.nim"
			nimln(110, "streams.nim");			if ((NU)(r) > (NU)(result->Sup.len)) raiseIndexError();			readbytes = readdata_142311(s, ((void*) ((&result->data[r]))), ((NI) 1000));
#line 111 "c:\\nim\\lib\\pure\\streams.nim"
			nimln(111, "streams.nim");			{				NI TMP609;
#line 111 "c:\\nim\\lib\\pure\\streams.nim"
				if (!(readbytes < ((NI) 1000))) goto LA5;

#line 112 "c:\\nim\\lib\\pure\\streams.nim"
				nimln(112, "streams.nim");
#line 112 "c:\\nim\\lib\\pure\\streams.nim"
				TMP609 = addInt(r, readbytes);				result = setLengthStr(result, ((NI)chckRange((NI)(TMP609), ((NI) 0), ((NI) IL64(9223372036854775807)))));
#line 113 "c:\\nim\\lib\\pure\\streams.nim"
				nimln(113, "streams.nim");				goto LA1;
			}
			LA5: ;

#line 114 "c:\\nim\\lib\\pure\\streams.nim"
			nimln(114, "streams.nim");			TMP610 = addInt(r, ((NI) 1000));			r = (NI)(TMP610);
#line 115 "c:\\nim\\lib\\pure\\streams.nim"
			nimln(115, "streams.nim");
#line 115 "c:\\nim\\lib\\pure\\streams.nim"
			TMP611 = addInt(r, ((NI) 1000));			result = setLengthStr(result, ((NI)chckRange((NI)(TMP611), ((NI) 0), ((NI) IL64(9223372036854775807)))));		}
	} LA1: ;	popFrame();	return result;}


#line 117 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, readdata_142336)(Streamobj142218* s, Streamobj142218* unused, void* buffer, NI buflen) {
	NI result;
	nimfr("readData", "streams.nim")
	result = 0;
#line 120 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(120, "streams.nim");	result = (*s).readdataimpl(s, buffer, buflen);	popFrame();	return result;}


#line 122 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, peekdata_142343)(Streamobj142218* s, void* buffer, NI buflen) {
	NI result;
	nimfr("peekData", "streams.nim")
	result = 0;
#line 125 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(125, "streams.nim");	result = (*s).peekdataimpl(s, buffer, buflen);	popFrame();	return result;}


#line 127 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, writedata_142349)(Streamobj142218* s, void* buffer, NI buflen) {
	nimfr("writeData", "streams.nim")

#line 130 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(130, "streams.nim");	(*s).writedataimpl(s, buffer, buflen);
	popFrame();}


#line 132 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, writedata_142354)(Streamobj142218* s, Streamobj142218* unused, void* buffer, NI buflen) {
	nimfr("writeData", "streams.nim")

#line 136 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(136, "streams.nim");	(*s).writedataimpl(s, buffer, buflen);
	popFrame();}


#line 148 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, write_142369)(Streamobj142218* s, NimStringDesc* x) {
	nimfr("write", "streams.nim")

#line 151 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(151, "streams.nim");
#line 151 "c:\\nim\\lib\\pure\\streams.nim"
	writedata_142349(s, ((void*) (x->data)), (x ? x->Sup.len : 0));
	popFrame();}


#line 153 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, writeln_142373)(Streamobj142218* s, NimStringDesc** args, NI argsLen0) {
	nimfr("writeLn", "streams.nim")
	{		NimStringDesc* str_142385;
		NI i_142389;
		str_142385 = 0;
#line 1965 "c:\\nim\\lib\\system.nim"
		nimln(1965, "system.nim");		i_142389 = ((NI) 0);		{
#line 1966 "c:\\nim\\lib\\system.nim"
			nimln(1966, "system.nim");			while (1) {				NI TMP612;
#line 1966 "c:\\nim\\lib\\system.nim"

#line 1966 "c:\\nim\\lib\\system.nim"
				if (!(i_142389 < argsLen0)) goto LA3;

#line 1967 "c:\\nim\\lib\\system.nim"
				nimln(1967, "system.nim");				if ((NU)(i_142389) >= (NU)(argsLen0)) raiseIndexError();				str_142385 = args[i_142389];
#line 155 "c:\\nim\\lib\\pure\\streams.nim"
				nimln(155, "streams.nim");				write_142369(s, str_142385);

#line 1968 "c:\\nim\\lib\\system.nim"
				nimln(1968, "system.nim");				TMP612 = addInt(i_142389, ((NI) 1));				i_142389 = (NI)(TMP612);			} LA3: ;		}
	}

#line 156 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(156, "streams.nim");	write_142369(s, ((NimStringDesc*) &TMP613));
	popFrame();}


#line 158 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, writeline_142390)(Streamobj142218* s, NimStringDesc** args, NI argsLen0) {
	nimfr("writeLine", "streams.nim")
	{		NimStringDesc* str_142402;
		NI i_142406;
		str_142402 = 0;
#line 1965 "c:\\nim\\lib\\system.nim"
		nimln(1965, "system.nim");		i_142406 = ((NI) 0);		{
#line 1966 "c:\\nim\\lib\\system.nim"
			nimln(1966, "system.nim");			while (1) {				NI TMP614;
#line 1966 "c:\\nim\\lib\\system.nim"

#line 1966 "c:\\nim\\lib\\system.nim"
				if (!(i_142406 < argsLen0)) goto LA3;

#line 1967 "c:\\nim\\lib\\system.nim"
				nimln(1967, "system.nim");				if ((NU)(i_142406) >= (NU)(argsLen0)) raiseIndexError();				str_142402 = args[i_142406];
#line 161 "c:\\nim\\lib\\pure\\streams.nim"
				nimln(161, "streams.nim");				write_142369(s, str_142402);

#line 1968 "c:\\nim\\lib\\system.nim"
				nimln(1968, "system.nim");				TMP614 = addInt(i_142406, ((NI) 1));				i_142406 = (NI)(TMP614);			} LA3: ;		}
	}

#line 162 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(162, "streams.nim");	write_142369(s, ((NimStringDesc*) &TMP613));
	popFrame();}


#line 174 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_CHAR, readchar_142426)(Streamobj142218* s) {
	NIM_CHAR result;
	nimfr("readChar", "streams.nim")
	result = 0;
#line 177 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(177, "streams.nim");	{		NI LOC3;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 177 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(177, "streams.nim");		LOC3 = 0;		LOC3 = readdata_142311(s, ((void*) ((&result))), ((NI) 1));		if (!!((LOC3 == ((NI) 1)))) goto LA4;

#line 177 "c:\\nim\\lib\\pure\\streams.nim"
		result = 0;	}
	LA4: ;
	popFrame();	return result;}


#line 179 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_CHAR, peekchar_142431)(Streamobj142218* s) {
	NIM_CHAR result;
	nimfr("peekChar", "streams.nim")
	result = 0;
#line 182 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(182, "streams.nim");	{		NI LOC3;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 182 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(182, "streams.nim");		LOC3 = 0;		LOC3 = peekdata_142343(s, ((void*) ((&result))), ((NI) 1));		if (!!((LOC3 == ((NI) 1)))) goto LA4;

#line 182 "c:\\nim\\lib\\pure\\streams.nim"
		result = 0;	}
	LA4: ;
	popFrame();	return result;}


#line 164 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, read_142441)(Streamobj142218* s, NIM_BOOL* result) {
	nimfr("read", "streams.nim")

#line 166 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(166, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 166 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(166, "streams.nim");		LOC3 = 0;		LOC3 = readdata_142311(s, ((void*) (result)), ((NI) 1));		if (!!((LOC3 == ((NI) 1)))) goto LA4;

#line 167 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(167, "streams.nim");		LOC6 = 0;		LOC6 = neweio_142202(((NimStringDesc*) &TMP615));
#line 167 "c:\\nim\\lib\\pure\\streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 184 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_BOOL, readbool_142436)(Streamobj142218* s) {
	NIM_BOOL result;
	nimfr("readBool", "streams.nim")
	result = 0;
#line 186 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(186, "streams.nim");	read_142441(s, (&result));
	popFrame();	return result;}


#line 169 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, peek_142474)(Streamobj142218* s, NIM_BOOL* result) {
	nimfr("peek", "streams.nim")

#line 171 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(171, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 171 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(171, "streams.nim");		LOC3 = 0;		LOC3 = peekdata_142343(s, ((void*) (result)), ((NI) 1));		if (!!((LOC3 == ((NI) 1)))) goto LA4;

#line 172 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(172, "streams.nim");		LOC6 = 0;		LOC6 = neweio_142202(((NimStringDesc*) &TMP615));
#line 172 "c:\\nim\\lib\\pure\\streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 188 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_BOOL, peekbool_142469)(Streamobj142218* s) {
	NIM_BOOL result;
	nimfr("peekBool", "streams.nim")
	result = 0;
#line 190 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(190, "streams.nim");	peek_142474(s, (&result));
	popFrame();	return result;}


#line 164 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, read_142507)(Streamobj142218* s, NI8* result) {
	nimfr("read", "streams.nim")

#line 166 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(166, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 166 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(166, "streams.nim");		LOC3 = 0;		LOC3 = readdata_142311(s, ((void*) (result)), ((NI) 1));		if (!!((LOC3 == ((NI) 1)))) goto LA4;

#line 167 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(167, "streams.nim");		LOC6 = 0;		LOC6 = neweio_142202(((NimStringDesc*) &TMP615));
#line 167 "c:\\nim\\lib\\pure\\streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 192 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI8, readint8_142502)(Streamobj142218* s) {
	NI8 result;
	nimfr("readInt8", "streams.nim")
	result = 0;
#line 194 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(194, "streams.nim");	read_142507(s, (&result));
	popFrame();	return result;}


#line 169 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, peek_142540)(Streamobj142218* s, NI8* result) {
	nimfr("peek", "streams.nim")

#line 171 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(171, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 171 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(171, "streams.nim");		LOC3 = 0;		LOC3 = peekdata_142343(s, ((void*) (result)), ((NI) 1));		if (!!((LOC3 == ((NI) 1)))) goto LA4;

#line 172 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(172, "streams.nim");		LOC6 = 0;		LOC6 = neweio_142202(((NimStringDesc*) &TMP615));
#line 172 "c:\\nim\\lib\\pure\\streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 196 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI8, peekint8_142535)(Streamobj142218* s) {
	NI8 result;
	nimfr("peekInt8", "streams.nim")
	result = 0;
#line 198 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(198, "streams.nim");	peek_142540(s, (&result));
	popFrame();	return result;}


#line 164 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, read_142573)(Streamobj142218* s, NI16* result) {
	nimfr("read", "streams.nim")

#line 166 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(166, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 166 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(166, "streams.nim");		LOC3 = 0;		LOC3 = readdata_142311(s, ((void*) (result)), ((NI) 2));		if (!!((LOC3 == ((NI) 2)))) goto LA4;

#line 167 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(167, "streams.nim");		LOC6 = 0;		LOC6 = neweio_142202(((NimStringDesc*) &TMP615));
#line 167 "c:\\nim\\lib\\pure\\streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 200 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI16, readint16_142568)(Streamobj142218* s) {
	NI16 result;
	nimfr("readInt16", "streams.nim")
	result = 0;
#line 202 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(202, "streams.nim");	read_142573(s, (&result));
	popFrame();	return result;}


#line 169 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, peek_142606)(Streamobj142218* s, NI16* result) {
	nimfr("peek", "streams.nim")

#line 171 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(171, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 171 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(171, "streams.nim");		LOC3 = 0;		LOC3 = peekdata_142343(s, ((void*) (result)), ((NI) 2));		if (!!((LOC3 == ((NI) 2)))) goto LA4;

#line 172 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(172, "streams.nim");		LOC6 = 0;		LOC6 = neweio_142202(((NimStringDesc*) &TMP615));
#line 172 "c:\\nim\\lib\\pure\\streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 204 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI16, peekint16_142601)(Streamobj142218* s) {
	NI16 result;
	nimfr("peekInt16", "streams.nim")
	result = 0;
#line 206 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(206, "streams.nim");	peek_142606(s, (&result));
	popFrame();	return result;}


#line 164 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, read_142639)(Streamobj142218* s, NI32* result) {
	nimfr("read", "streams.nim")

#line 166 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(166, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 166 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(166, "streams.nim");		LOC3 = 0;		LOC3 = readdata_142311(s, ((void*) (result)), ((NI) 4));		if (!!((LOC3 == ((NI) 4)))) goto LA4;

#line 167 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(167, "streams.nim");		LOC6 = 0;		LOC6 = neweio_142202(((NimStringDesc*) &TMP615));
#line 167 "c:\\nim\\lib\\pure\\streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 208 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI32, readint32_142634)(Streamobj142218* s) {
	NI32 result;
	nimfr("readInt32", "streams.nim")
	result = 0;
#line 210 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(210, "streams.nim");	read_142639(s, (&result));
	popFrame();	return result;}


#line 169 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, peek_142672)(Streamobj142218* s, NI32* result) {
	nimfr("peek", "streams.nim")

#line 171 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(171, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 171 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(171, "streams.nim");		LOC3 = 0;		LOC3 = peekdata_142343(s, ((void*) (result)), ((NI) 4));		if (!!((LOC3 == ((NI) 4)))) goto LA4;

#line 172 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(172, "streams.nim");		LOC6 = 0;		LOC6 = neweio_142202(((NimStringDesc*) &TMP615));
#line 172 "c:\\nim\\lib\\pure\\streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 212 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI32, peekint32_142667)(Streamobj142218* s) {
	NI32 result;
	nimfr("peekInt32", "streams.nim")
	result = 0;
#line 214 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(214, "streams.nim");	peek_142672(s, (&result));
	popFrame();	return result;}


#line 164 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, read_142705)(Streamobj142218* s, NI64* result) {
	nimfr("read", "streams.nim")

#line 166 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(166, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 166 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(166, "streams.nim");		LOC3 = 0;		LOC3 = readdata_142311(s, ((void*) (result)), ((NI) 8));		if (!!((LOC3 == ((NI) 8)))) goto LA4;

#line 167 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(167, "streams.nim");		LOC6 = 0;		LOC6 = neweio_142202(((NimStringDesc*) &TMP615));
#line 167 "c:\\nim\\lib\\pure\\streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 216 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI64, readint64_142700)(Streamobj142218* s) {
	NI64 result;
	nimfr("readInt64", "streams.nim")
	result = 0;
#line 218 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(218, "streams.nim");	read_142705(s, (&result));
	popFrame();	return result;}


#line 169 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, peek_142738)(Streamobj142218* s, NI64* result) {
	nimfr("peek", "streams.nim")

#line 171 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(171, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 171 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(171, "streams.nim");		LOC3 = 0;		LOC3 = peekdata_142343(s, ((void*) (result)), ((NI) 8));		if (!!((LOC3 == ((NI) 8)))) goto LA4;

#line 172 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(172, "streams.nim");		LOC6 = 0;		LOC6 = neweio_142202(((NimStringDesc*) &TMP615));
#line 172 "c:\\nim\\lib\\pure\\streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 220 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI64, peekint64_142733)(Streamobj142218* s) {
	NI64 result;
	nimfr("peekInt64", "streams.nim")
	result = 0;
#line 222 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(222, "streams.nim");	peek_142738(s, (&result));
	popFrame();	return result;}


#line 164 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, read_142771)(Streamobj142218* s, NF32* result) {
	nimfr("read", "streams.nim")

#line 166 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(166, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 166 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(166, "streams.nim");		LOC3 = 0;		LOC3 = readdata_142311(s, ((void*) (result)), ((NI) 4));		if (!!((LOC3 == ((NI) 4)))) goto LA4;

#line 167 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(167, "streams.nim");		LOC6 = 0;		LOC6 = neweio_142202(((NimStringDesc*) &TMP615));
#line 167 "c:\\nim\\lib\\pure\\streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 224 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NF32, readfloat32_142766)(Streamobj142218* s) {
	NF32 result;
	nimfr("readFloat32", "streams.nim")
	result = 0;
#line 226 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(226, "streams.nim");	read_142771(s, (&result));
	popFrame();	return result;}


#line 169 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, peek_142804)(Streamobj142218* s, NF32* result) {
	nimfr("peek", "streams.nim")

#line 171 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(171, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 171 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(171, "streams.nim");		LOC3 = 0;		LOC3 = peekdata_142343(s, ((void*) (result)), ((NI) 4));		if (!!((LOC3 == ((NI) 4)))) goto LA4;

#line 172 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(172, "streams.nim");		LOC6 = 0;		LOC6 = neweio_142202(((NimStringDesc*) &TMP615));
#line 172 "c:\\nim\\lib\\pure\\streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 228 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NF32, peekfloat32_142799)(Streamobj142218* s) {
	NF32 result;
	nimfr("peekFloat32", "streams.nim")
	result = 0;
#line 230 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(230, "streams.nim");	peek_142804(s, (&result));
	popFrame();	return result;}


#line 164 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, read_142837)(Streamobj142218* s, NF* result) {
	nimfr("read", "streams.nim")

#line 166 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(166, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 166 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(166, "streams.nim");		LOC3 = 0;		LOC3 = readdata_142311(s, ((void*) (result)), ((NI) 8));		if (!!((LOC3 == ((NI) 8)))) goto LA4;

#line 167 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(167, "streams.nim");		LOC6 = 0;		LOC6 = neweio_142202(((NimStringDesc*) &TMP615));
#line 167 "c:\\nim\\lib\\pure\\streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 232 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NF, readfloat64_142832)(Streamobj142218* s) {
	NF result;
	nimfr("readFloat64", "streams.nim")
	result = 0;
#line 234 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(234, "streams.nim");	read_142837(s, (&result));
	popFrame();	return result;}


#line 169 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, peek_142870)(Streamobj142218* s, NF* result) {
	nimfr("peek", "streams.nim")

#line 171 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(171, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 171 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(171, "streams.nim");		LOC3 = 0;		LOC3 = peekdata_142343(s, ((void*) (result)), ((NI) 8));		if (!!((LOC3 == ((NI) 8)))) goto LA4;

#line 172 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(172, "streams.nim");		LOC6 = 0;		LOC6 = neweio_142202(((NimStringDesc*) &TMP615));
#line 172 "c:\\nim\\lib\\pure\\streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}


#line 236 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NF, peekfloat64_142865)(Streamobj142218* s) {
	NF result;
	nimfr("peekFloat64", "streams.nim")
	result = 0;
#line 238 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(238, "streams.nim");	peek_142870(s, (&result));
	popFrame();	return result;}


#line 240 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NimStringDesc*, readstr_142898)(Streamobj142218* s, NI length) {
	NimStringDesc* result;
	NI L;
	nimfr("readStr", "streams.nim")
	result = 0;
#line 243 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(243, "streams.nim");
#line 243 "c:\\nim\\lib\\pure\\streams.nim"
	result = mnewString(((NI)chckRange(length, ((NI) 0), ((NI) IL64(9223372036854775807)))));
#line 244 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(244, "streams.nim");	if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();	L = readdata_142311(s, ((void*) ((&result->data[((NI) 0)]))), length);
#line 245 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(245, "streams.nim");	{
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
		if (!!((L == length))) goto LA3;

#line 245 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(245, "streams.nim");		result = setLengthStr(result, ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));	}
	LA3: ;
	popFrame();	return result;}


#line 247 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NimStringDesc*, peekstr_142907)(Streamobj142218* s, NI length) {
	NimStringDesc* result;
	NI L;
	nimfr("peekStr", "streams.nim")
	result = 0;
#line 250 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(250, "streams.nim");
#line 250 "c:\\nim\\lib\\pure\\streams.nim"
	result = mnewString(((NI)chckRange(length, ((NI) 0), ((NI) IL64(9223372036854775807)))));
#line 251 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(251, "streams.nim");	if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();	L = peekdata_142343(s, ((void*) ((&result->data[((NI) 0)]))), length);
#line 252 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(252, "streams.nim");	{
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
		if (!!((L == length))) goto LA3;

#line 252 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(252, "streams.nim");		result = setLengthStr(result, ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));	}
	LA3: ;
	popFrame();	return result;}


#line 254 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_BOOL, readline_142916)(Streamobj142218* s, NimStringDesc** line) {
	NIM_BOOL result;
	nimfr("readLine", "streams.nim")
{	result = 0;
#line 261 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(261, "streams.nim");	(*line) = setLengthStr((*line), ((NI) 0));	{
#line 262 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(262, "streams.nim");		while (1) {			NIM_CHAR c;

#line 263 "c:\\nim\\lib\\pure\\streams.nim"
			nimln(263, "streams.nim");			c = readchar_142426(s);
#line 264 "c:\\nim\\lib\\pure\\streams.nim"
			nimln(264, "streams.nim");			{
#line 264 "c:\\nim\\lib\\pure\\streams.nim"
				if (!((NU8)(c) == (NU8)(13))) goto LA5;

#line 265 "c:\\nim\\lib\\pure\\streams.nim"
				nimln(265, "streams.nim");				c = readchar_142426(s);
#line 266 "c:\\nim\\lib\\pure\\streams.nim"
				nimln(266, "streams.nim");				goto LA1;
			}
			goto LA3;
			LA5: ;
			{
#line 267 "c:\\nim\\lib\\pure\\streams.nim"
				nimln(267, "streams.nim");				if (!((NU8)(c) == (NU8)(10))) goto LA8;

#line 267 "c:\\nim\\lib\\pure\\streams.nim"
				goto LA1;
			}
			goto LA3;
			LA8: ;
			{
#line 268 "c:\\nim\\lib\\pure\\streams.nim"
				nimln(268, "streams.nim");				if (!((NU8)(c) == (NU8)(0))) goto LA11;

#line 269 "c:\\nim\\lib\\pure\\streams.nim"
				nimln(269, "streams.nim");				{
#line 357 "c:\\nim\\lib\\system.nim"
					nimln(357, "system.nim");
#line 269 "c:\\nim\\lib\\pure\\streams.nim"
					nimln(269, "streams.nim");					if (!(((NI) 0) < ((*line) ? (*line)->Sup.len : 0))) goto LA15;

#line 269 "c:\\nim\\lib\\pure\\streams.nim"
					goto LA1;
				}
				goto LA13;
				LA15: ;
				{
#line 270 "c:\\nim\\lib\\pure\\streams.nim"
					nimln(270, "streams.nim");
#line 270 "c:\\nim\\lib\\pure\\streams.nim"
					result = NIM_FALSE;					goto BeforeRet;
				}
				LA13: ;
			}
			goto LA3;
			LA11: ;
			LA3: ;

#line 271 "c:\\nim\\lib\\pure\\streams.nim"
			nimln(271, "streams.nim");			(*line) = addChar((*line), c);		}
	} LA1: ;
#line 272 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(272, "streams.nim");	result = NIM_TRUE;	}BeforeRet: ;
	popFrame();	return result;}


#line 55 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, pushSafePoint)(TSafePoint* s) {

#line 56 "c:\\nim\\lib\\system\\excpt.nim"
	(*s).hasRaiseAction = NIM_FALSE;
#line 57 "c:\\nim\\lib\\system\\excpt.nim"
	(*s).prev = exchandler_19437;
#line 58 "c:\\nim\\lib\\system\\excpt.nim"
	exchandler_19437 = s;}


#line 60 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popSafePoint)(void) {

#line 61 "c:\\nim\\lib\\system\\excpt.nim"
	exchandler_19437 = (*exchandler_19437).prev;}


#line 52 "c:\\nim\\lib\\system\\excpt.nim"
static N_INLINE(void, setFrame)(TFrame* s) {

#line 53 "c:\\nim\\lib\\system\\excpt.nim"
	frameptr_19436 = s;}


#line 274 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_BOOL, peekline_142926)(Streamobj142218* s, NimStringDesc** line) {
	NIM_BOOL volatile result;
	NI pos;
	TSafePoint TMP616;	nimfr("peekLine", "streams.nim")
	result = 0;
#line 281 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(281, "streams.nim");	pos = getposition_142302(s);
#line 282 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(282, "streams.nim");	pushSafePoint(&TMP616);	TMP616.status = setjmp(TMP616.context);	if (TMP616.status == 0) {
#line 283 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(283, "streams.nim");		result = readline_142916(s, line);		popSafePoint();	}
	else {		popSafePoint();		setFrame((TFrame*)&FR);	}
	{
#line 282 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(282, "streams.nim");		setposition_142293(s, pos);
	}
	if (TMP616.status != 0) reraiseException();	popFrame();	return result;}


#line 285 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NimStringDesc*, readline_142933)(Streamobj142218* s) {
	NimStringDesc* result;
	nimfr("readLine", "streams.nim")
	result = 0;
#line 288 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(288, "streams.nim");	result = copyString(((NimStringDesc*) &TMP617));	{
#line 289 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(289, "streams.nim");		while (1) {			NIM_CHAR c;

#line 290 "c:\\nim\\lib\\pure\\streams.nim"
			nimln(290, "streams.nim");			c = readchar_142426(s);
#line 291 "c:\\nim\\lib\\pure\\streams.nim"
			nimln(291, "streams.nim");			{
#line 291 "c:\\nim\\lib\\pure\\streams.nim"
				if (!((NU8)(c) == (NU8)(13))) goto LA5;

#line 292 "c:\\nim\\lib\\pure\\streams.nim"
				nimln(292, "streams.nim");				c = readchar_142426(s);
#line 293 "c:\\nim\\lib\\pure\\streams.nim"
				nimln(293, "streams.nim");				goto LA1;
			}
			LA5: ;

#line 294 "c:\\nim\\lib\\pure\\streams.nim"
			nimln(294, "streams.nim");			{				NIM_BOOL LOC9;
#line 294 "c:\\nim\\lib\\pure\\streams.nim"
				LOC9 = 0;
#line 294 "c:\\nim\\lib\\pure\\streams.nim"
				LOC9 = ((NU8)(c) == (NU8)(10));				if (LOC9) goto LA10;

#line 294 "c:\\nim\\lib\\pure\\streams.nim"
				LOC9 = ((NU8)(c) == (NU8)(0));				LA10: ;
				if (!LOC9) goto LA11;

#line 295 "c:\\nim\\lib\\pure\\streams.nim"
				nimln(295, "streams.nim");				goto LA1;
			}
			goto LA7;
			LA11: ;
			{
#line 297 "c:\\nim\\lib\\pure\\streams.nim"
				nimln(297, "streams.nim");				result = addChar(result, c);			}
			LA7: ;
		}
	} LA1: ;	popFrame();	return result;}


#line 299 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NimStringDesc*, peekline_142941)(Streamobj142218* s) {
	NimStringDesc* volatile result;
	NI pos;
	TSafePoint TMP618;	nimfr("peekLine", "streams.nim")
	result = 0;
#line 302 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(302, "streams.nim");	pos = getposition_142302(s);
#line 303 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(303, "streams.nim");	pushSafePoint(&TMP618);	TMP618.status = setjmp(TMP618.context);	if (TMP618.status == 0) {
#line 304 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(304, "streams.nim");		result = readline_142933(s);		popSafePoint();	}
	else {		popSafePoint();		setFrame((TFrame*)&FR);	}
	{
#line 303 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(303, "streams.nim");		setposition_142293(s, pos);
	}
	if (TMP618.status != 0) reraiseException();	popFrame();	return result;}


#line 314 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_BOOL, ssatend_142954)(Streamobj142218* s_142956) {
	NIM_BOOL result;
	Stringstreamobj142949* s;
	nimfr("ssAtEnd", "streams.nim")
{	result = 0;
#line 315 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(315, "streams.nim");	if (s_142956) chckObj((*s_142956).Sup.m_type, (&NTI142949));	s = ((Stringstreamobj142949*) (s_142956));
#line 316 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(316, "streams.nim");
#line 316 "c:\\nim\\lib\\pure\\streams.nim"

#line 353 "c:\\nim\\lib\\system.nim"
	nimln(353, "system.nim");
#line 316 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(316, "streams.nim");	result = (((*s).data ? (*s).data->Sup.len : 0) <= (*s).pos);	goto BeforeRet;
	}BeforeRet: ;
	popFrame();	return result;}


#line 318 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, sssetposition_142959)(Streamobj142218* s_142961, NI pos) {
	Stringstreamobj142949* s;
	nimfr("ssSetPosition", "streams.nim")

#line 319 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(319, "streams.nim");	if (s_142961) chckObj((*s_142961).Sup.m_type, (&NTI142949));	s = ((Stringstreamobj142949*) (s_142961));
#line 320 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(320, "streams.nim");
#line 320 "c:\\nim\\lib\\pure\\streams.nim"
	(*s).pos = clamp_142965(pos, ((NI) 0), ((*s).data ? (*s).data->Sup.len : 0));	popFrame();}


#line 322 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, ssgetposition_142975)(Streamobj142218* s_142977) {
	NI result;
	Stringstreamobj142949* s;
	nimfr("ssGetPosition", "streams.nim")
{	result = 0;
#line 323 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(323, "streams.nim");	if (s_142977) chckObj((*s_142977).Sup.m_type, (&NTI142949));	s = ((Stringstreamobj142949*) (s_142977));
#line 324 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(324, "streams.nim");
#line 324 "c:\\nim\\lib\\pure\\streams.nim"
	result = (*s).pos;	goto BeforeRet;
	}BeforeRet: ;
	popFrame();	return result;}


#line 326 "c:\\nim\\lib\\system\\arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
#line 327 "c:\\nim\\lib\\system\\arithm.nim"

#line 327 "c:\\nim\\lib\\system\\arithm.nim"
	result = (NI)((NU64)(a) - (NU64)(b));
#line 328 "c:\\nim\\lib\\system\\arithm.nim"
	{		NIM_BOOL LOC3;
#line 328 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = 0;
#line 353 "c:\\nim\\lib\\system.nim"

#line 328 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ a));		if (LOC3) goto LA4;

#line 353 "c:\\nim\\lib\\system.nim"

#line 328 "c:\\nim\\lib\\system\\arithm.nim"

#line 328 "c:\\nim\\lib\\system\\arithm.nim"
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));		LA4: ;
		if (!LOC3) goto LA5;

#line 329 "c:\\nim\\lib\\system\\arithm.nim"
		goto BeforeRet;
	}
	LA5: ;

#line 330 "c:\\nim\\lib\\system\\arithm.nim"
	raiseOverflow();
	}BeforeRet: ;
	return result;}


#line 326 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, ssreaddata_142980)(Streamobj142218* s_142982, void* buffer, NI buflen) {
	NI result;
	Stringstreamobj142949* s;
	NI TMP621;	nimfr("ssReadData", "streams.nim")
	result = 0;
#line 327 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(327, "streams.nim");	if (s_142982) chckObj((*s_142982).Sup.m_type, (&NTI142949));	s = ((Stringstreamobj142949*) (s_142982));
#line 328 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(328, "streams.nim");
#line 328 "c:\\nim\\lib\\pure\\streams.nim"

#line 328 "c:\\nim\\lib\\pure\\streams.nim"

#line 328 "c:\\nim\\lib\\pure\\streams.nim"
	TMP621 = subInt(((*s).data ? (*s).data->Sup.len : 0), (*s).pos);	result = ((buflen <= (NI)(TMP621)) ? buflen : (NI)(TMP621));
#line 329 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(329, "streams.nim");	{		NI TMP622;
#line 357 "c:\\nim\\lib\\system.nim"
		nimln(357, "system.nim");		if (!(((NI) 0) < result)) goto LA3;

#line 330 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(330, "streams.nim");		if ((NU)((*s).pos) > (NU)((*s).data->Sup.len)) raiseIndexError();		memcpy(buffer, ((void*) ((&(*s).data->data[(*s).pos]))), ((NI)chckRange(result, ((NI) 0), ((NI) IL64(9223372036854775807)))));

#line 331 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(331, "streams.nim");		TMP622 = addInt((*s).pos, result);		(*s).pos = (NI)(TMP622);	}
	LA3: ;
	popFrame();	return result;}


#line 333 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, sspeekdata_143001)(Streamobj142218* s_143003, void* buffer, NI buflen) {
	NI result;
	Stringstreamobj142949* s;
	NI TMP623;	nimfr("ssPeekData", "streams.nim")
	result = 0;
#line 334 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(334, "streams.nim");	if (s_143003) chckObj((*s_143003).Sup.m_type, (&NTI142949));	s = ((Stringstreamobj142949*) (s_143003));
#line 335 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(335, "streams.nim");
#line 335 "c:\\nim\\lib\\pure\\streams.nim"

#line 335 "c:\\nim\\lib\\pure\\streams.nim"

#line 335 "c:\\nim\\lib\\pure\\streams.nim"
	TMP623 = subInt(((*s).data ? (*s).data->Sup.len : 0), (*s).pos);	result = ((buflen <= (NI)(TMP623)) ? buflen : (NI)(TMP623));
#line 336 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(336, "streams.nim");	{
#line 357 "c:\\nim\\lib\\system.nim"
		nimln(357, "system.nim");		if (!(((NI) 0) < result)) goto LA3;

#line 337 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(337, "streams.nim");		if ((NU)((*s).pos) > (NU)((*s).data->Sup.len)) raiseIndexError();		memcpy(buffer, ((void*) ((&(*s).data->data[(*s).pos]))), ((NI)chckRange(result, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA3: ;
	popFrame();	return result;}


#line 339 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, sswritedata_143013)(Streamobj142218* s_143015, void* buffer, NI buflen) {
	Stringstreamobj142949* s;
	NI TMP626;	nimfr("ssWriteData", "streams.nim")
{
#line 340 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(340, "streams.nim");	if (s_143015) chckObj((*s_143015).Sup.m_type, (&NTI142949));	s = ((Stringstreamobj142949*) (s_143015));
#line 341 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(341, "streams.nim");	{
#line 341 "c:\\nim\\lib\\pure\\streams.nim"
		if (!(buflen <= ((NI) 0))) goto LA3;

#line 342 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(342, "streams.nim");		goto BeforeRet;
	}
	LA3: ;

#line 343 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(343, "streams.nim");	{		NI TMP624;		NI TMP625;
#line 357 "c:\\nim\\lib\\system.nim"
		nimln(357, "system.nim");
#line 343 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(343, "streams.nim");
#line 343 "c:\\nim\\lib\\pure\\streams.nim"
		TMP624 = addInt((*s).pos, buflen);		if (!(((*s).data ? (*s).data->Sup.len : 0) < (NI)(TMP624))) goto LA7;

#line 344 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(344, "streams.nim");
#line 344 "c:\\nim\\lib\\pure\\streams.nim"
		TMP625 = addInt((*s).pos, buflen);		(*s).data = setLengthStr((*s).data, ((NI)chckRange((NI)(TMP625), ((NI) 0), ((NI) IL64(9223372036854775807)))));	}
	LA7: ;

#line 345 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(345, "streams.nim");	if ((NU)((*s).pos) > (NU)((*s).data->Sup.len)) raiseIndexError();	memcpy(((void*) ((&(*s).data->data[(*s).pos]))), buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));

#line 346 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(346, "streams.nim");	TMP626 = addInt((*s).pos, buflen);	(*s).pos = (NI)(TMP626);	}BeforeRet: ;
	popFrame();}


#line 348 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, ssclose_143029)(Streamobj142218* s_143031) {
	Stringstreamobj142949* s;
	NimStringDesc* LOC1;	nimfr("ssClose", "streams.nim")

#line 349 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(349, "streams.nim");	if (s_143031) chckObj((*s_143031).Sup.m_type, (&NTI142949));	s = ((Stringstreamobj142949*) (s_143031));
#line 350 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(350, "streams.nim");	LOC1 = 0;	LOC1 = (*s).data; (*s).data = copyStringRC1(NIM_NIL);	if (LOC1) nimGCunrefNoCycle(LOC1);	popFrame();}
N_NIMCALL(void, TMP627)(void* p, NI op) {
	Stringstreamobj142949* a;
	a = (Stringstreamobj142949*)p;
	nimGCvisit((void*)(*a).data, op);}


#line 352 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(Stringstreamobj142949*, newstringstream_143033)(NimStringDesc* s) {
	Stringstreamobj142949* result;
	NimStringDesc* LOC1;	nimfr("newStringStream", "streams.nim")
	result = 0;
#line 354 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(354, "streams.nim");	result = (Stringstreamobj142949*) newObj((&NTI142947), sizeof(Stringstreamobj142949));	(*result).Sup.Sup.m_type = (&NTI142949);
#line 355 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(355, "streams.nim");	LOC1 = 0;	LOC1 = (*result).data; (*result).data = copyStringRC1(s);	if (LOC1) nimGCunrefNoCycle(LOC1);
#line 356 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(356, "streams.nim");	(*result).pos = ((NI) 0);
#line 357 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(357, "streams.nim");	(*result).Sup.closeimpl = ssclose_143029;
#line 358 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(358, "streams.nim");	(*result).Sup.atendimpl = ssatend_142954;
#line 359 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(359, "streams.nim");	(*result).Sup.setpositionimpl = sssetposition_142959;
#line 360 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(360, "streams.nim");	(*result).Sup.getpositionimpl = ssgetposition_142975;
#line 361 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(361, "streams.nim");	(*result).Sup.readdataimpl = ssreaddata_142980;
#line 362 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(362, "streams.nim");	(*result).Sup.peekdataimpl = sspeekdata_143001;
#line 363 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(363, "streams.nim");	(*result).Sup.writedataimpl = sswritedata_143013;	popFrame();	return result;}


#line 373 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, fsclose_143052)(Streamobj142218* s) {
	nimfr("fsClose", "streams.nim")

#line 374 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(374, "streams.nim");	{
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"
		if (s) chckObj((*s).Sup.m_type, (&NTI143048));		if (!!(((*((Filestreamobj143048*) (s))).f == NIM_NIL))) goto LA3;

#line 375 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(375, "streams.nim");		if (s) chckObj((*s).Sup.m_type, (&NTI143048));		fclose((*((Filestreamobj143048*) (s))).f);

#line 376 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(376, "streams.nim");		if (s) chckObj((*s).Sup.m_type, (&NTI143048));		(*((Filestreamobj143048*) (s))).f = NIM_NIL;	}
	LA3: ;
	popFrame();}


#line 377 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, fsflush_143067)(Streamobj142218* s) {
	nimfr("fsFlush", "streams.nim")

#line 377 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(377, "streams.nim");	if (s) chckObj((*s).Sup.m_type, (&NTI143048));	fflush((*((Filestreamobj143048*) (s))).f);
	popFrame();}


#line 378 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NIM_BOOL, fsatend_143070)(Streamobj142218* s) {
	NIM_BOOL result;
	nimfr("fsAtEnd", "streams.nim")
{	result = 0;
#line 378 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(378, "streams.nim");
#line 378 "c:\\nim\\lib\\pure\\streams.nim"
	if (s) chckObj((*s).Sup.m_type, (&NTI143048));	result = endoffile_15454((*((Filestreamobj143048*) (s))).f);	goto BeforeRet;
	}BeforeRet: ;
	popFrame();	return result;}


#line 379 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, fssetposition_143074)(Streamobj142218* s, NI pos) {
	nimfr("fsSetPosition", "streams.nim")

#line 379 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(379, "streams.nim");	if (s) chckObj((*s).Sup.m_type, (&NTI143048));	setfilepos_15581((*((Filestreamobj143048*) (s))).f, ((NI64) (pos)));
	popFrame();}


#line 380 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, fsgetposition_143078)(Streamobj142218* s) {
	NI result;
	NI64 LOC1;	nimfr("fsGetPosition", "streams.nim")
{	result = 0;
#line 380 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(380, "streams.nim");
#line 380 "c:\\nim\\lib\\pure\\streams.nim"

#line 380 "c:\\nim\\lib\\pure\\streams.nim"
	if (s) chckObj((*s).Sup.m_type, (&NTI143048));	LOC1 = 0;	LOC1 = getfilepos_15585((*((Filestreamobj143048*) (s))).f);	result = ((NI) (LOC1));	goto BeforeRet;
	}BeforeRet: ;
	popFrame();	return result;}


#line 382 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, fsreaddata_143083)(Streamobj142218* s, void* buffer, NI buflen) {
	NI result;
	nimfr("fsReadData", "streams.nim")
	result = 0;
#line 383 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(383, "streams.nim");	if (s) chckObj((*s).Sup.m_type, (&NTI143048));	result = readbuffer_15554((*((Filestreamobj143048*) (s))).f, buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));	popFrame();	return result;}


#line 385 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(NI, fspeekdata_143089)(Streamobj142218* s, void* buffer, NI buflen) {
	NI volatile result;
	NI pos;
	TSafePoint TMP628;	nimfr("fsPeekData", "streams.nim")
	result = 0;
#line 386 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(386, "streams.nim");	pos = fsgetposition_143078(s);
#line 387 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(387, "streams.nim");	pushSafePoint(&TMP628);	TMP628.status = setjmp(TMP628.context);	if (TMP628.status == 0) {
#line 388 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(388, "streams.nim");		if (s) chckObj((*s).Sup.m_type, (&NTI143048));		result = readbuffer_15554((*((Filestreamobj143048*) (s))).f, buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));		popSafePoint();	}
	else {		popSafePoint();		setFrame((TFrame*)&FR);	}
	{
#line 387 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(387, "streams.nim");		fssetposition_143074(s, pos);
	}
	if (TMP628.status != 0) reraiseException();	popFrame();	return result;}


#line 390 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(void, fswritedata_143096)(Streamobj142218* s, void* buffer, NI buflen) {
	nimfr("fsWriteData", "streams.nim")

#line 391 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(391, "streams.nim");	{		NI LOC3;		Ioerror3628* LOC6;
#line 349 "c:\\nim\\lib\\system.nim"
		nimln(349, "system.nim");
#line 349 "c:\\nim\\lib\\system.nim"

#line 391 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(391, "streams.nim");		if (s) chckObj((*s).Sup.m_type, (&NTI143048));		LOC3 = 0;		LOC3 = writebuffer_15576((*((Filestreamobj143048*) (s))).f, buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));		if (!!((LOC3 == buflen))) goto LA4;

#line 392 "c:\\nim\\lib\\pure\\streams.nim"
		nimln(392, "streams.nim");		LOC6 = 0;		LOC6 = neweio_142202(((NimStringDesc*) &TMP629));
#line 392 "c:\\nim\\lib\\pure\\streams.nim"
		raiseException((Exception*)LOC6, "IOError");	}
	LA4: ;
	popFrame();}
N_NIMCALL(void, TMP630)(void* p, NI op) {
	Filestreamobj143048* a;
	a = (Filestreamobj143048*)p;
}


#line 394 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(Filestreamobj143048*, newfilestream_143101)(FILE* f) {
	Filestreamobj143048* result;
	nimfr("newFileStream", "streams.nim")
	result = 0;
#line 396 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(396, "streams.nim");	result = (Filestreamobj143048*) newObj((&NTI143046), sizeof(Filestreamobj143048));	(*result).Sup.Sup.m_type = (&NTI143048);
#line 397 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(397, "streams.nim");	(*result).f = f;
#line 398 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(398, "streams.nim");	(*result).Sup.closeimpl = fsclose_143052;
#line 399 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(399, "streams.nim");	(*result).Sup.atendimpl = fsatend_143070;
#line 400 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(400, "streams.nim");	(*result).Sup.setpositionimpl = fssetposition_143074;
#line 401 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(401, "streams.nim");	(*result).Sup.getpositionimpl = fsgetposition_143078;
#line 402 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(402, "streams.nim");	(*result).Sup.readdataimpl = fsreaddata_143083;
#line 403 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(403, "streams.nim");	(*result).Sup.peekdataimpl = fspeekdata_143089;
#line 404 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(404, "streams.nim");	(*result).Sup.writedataimpl = fswritedata_143096;
#line 405 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(405, "streams.nim");	(*result).Sup.flushimpl = fsflush_143067;	popFrame();	return result;}


#line 407 "c:\\nim\\lib\\pure\\streams.nim"
N_NIMCALL(Filestreamobj143048*, newfilestream_143113)(NimStringDesc* filename, NU8 mode) {
	Filestreamobj143048* result;
	FILE* f;
	nimfr("newFileStream", "streams.nim")
	result = 0;	f = 0;
#line 412 "c:\\nim\\lib\\pure\\streams.nim"
	nimln(412, "streams.nim");	{		NIM_BOOL LOC3;
#line 412 "c:\\nim\\lib\\pure\\streams.nim"
		LOC3 = 0;		LOC3 = open_15403(&f, filename, mode, ((NI) -1));		if (!LOC3) goto LA4;

#line 412 "c:\\nim\\lib\\pure\\streams.nim"
		result = newfilestream_143101(f);	}
	LA4: ;
	popFrame();	return result;}
N_NIMCALL(void, TMP968)(void* p, NI op) {
	Streamobj142218* a;
	a = (Streamobj142218*)p;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void) {
	nimfr("streams", "streams.nim")
	popFrame();}

NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void) {
static TNimNode* TMP619[8];
static TNimNode* TMP620[2];
static TNimNode TMP607[13];NTI142218.size = sizeof(Streamobj142218);
NTI142218.kind = 17;
NTI142218.base = (&NTI3608);
NTI142218.flags = 1;
TMP619[0] = &TMP607[1];
NTI142219.size = sizeof(TY142219);
NTI142219.kind = 25;
NTI142219.base = 0;
NTI142219.flags = 3;
TMP607[1].kind = 1;
TMP607[1].offset = offsetof(Streamobj142218, closeimpl);
TMP607[1].typ = (&NTI142219);
TMP607[1].name = "closeImpl";
TMP619[1] = &TMP607[2];
NTI142223.size = sizeof(TY142223);
NTI142223.kind = 25;
NTI142223.base = 0;
NTI142223.flags = 3;
TMP607[2].kind = 1;
TMP607[2].offset = offsetof(Streamobj142218, atendimpl);
TMP607[2].typ = (&NTI142223);
TMP607[2].name = "atEndImpl";
TMP619[2] = &TMP607[3];
NTI142227.size = sizeof(TY142227);
NTI142227.kind = 25;
NTI142227.base = 0;
NTI142227.flags = 3;
TMP607[3].kind = 1;
TMP607[3].offset = offsetof(Streamobj142218, setpositionimpl);
TMP607[3].typ = (&NTI142227);
TMP607[3].name = "setPositionImpl";
TMP619[3] = &TMP607[4];
NTI142232.size = sizeof(TY142232);
NTI142232.kind = 25;
NTI142232.base = 0;
NTI142232.flags = 3;
TMP607[4].kind = 1;
TMP607[4].offset = offsetof(Streamobj142218, getpositionimpl);
TMP607[4].typ = (&NTI142232);
TMP607[4].name = "getPositionImpl";
TMP619[4] = &TMP607[5];
NTI142236.size = sizeof(TY142236);
NTI142236.kind = 25;
NTI142236.base = 0;
NTI142236.flags = 3;
TMP607[5].kind = 1;
TMP607[5].offset = offsetof(Streamobj142218, readdataimpl);
TMP607[5].typ = (&NTI142236);
TMP607[5].name = "readDataImpl";
TMP619[5] = &TMP607[6];
NTI142242.size = sizeof(TY142242);
NTI142242.kind = 25;
NTI142242.base = 0;
NTI142242.flags = 3;
TMP607[6].kind = 1;
TMP607[6].offset = offsetof(Streamobj142218, peekdataimpl);
TMP607[6].typ = (&NTI142242);
TMP607[6].name = "peekDataImpl";
TMP619[6] = &TMP607[7];
NTI142248.size = sizeof(TY142248);
NTI142248.kind = 25;
NTI142248.base = 0;
NTI142248.flags = 3;
TMP607[7].kind = 1;
TMP607[7].offset = offsetof(Streamobj142218, writedataimpl);
TMP607[7].typ = (&NTI142248);
TMP607[7].name = "writeDataImpl";
TMP619[7] = &TMP607[8];
NTI142254.size = sizeof(TY142254);
NTI142254.kind = 25;
NTI142254.base = 0;
NTI142254.flags = 3;
TMP607[8].kind = 1;
TMP607[8].offset = offsetof(Streamobj142218, flushimpl);
TMP607[8].typ = (&NTI142254);
TMP607[8].name = "flushImpl";
TMP607[0].len = 8; TMP607[0].kind = 2; TMP607[0].sons = &TMP619[0];
NTI142218.node = &TMP607[0];
NTI142949.size = sizeof(Stringstreamobj142949);
NTI142949.kind = 17;
NTI142949.base = (&NTI142218);
TMP620[0] = &TMP607[10];
TMP607[10].kind = 1;
TMP607[10].offset = offsetof(Stringstreamobj142949, data);
TMP607[10].typ = (&NTI138);
TMP607[10].name = "data";
TMP620[1] = &TMP607[11];
TMP607[11].kind = 1;
TMP607[11].offset = offsetof(Stringstreamobj142949, pos);
TMP607[11].typ = (&NTI104);
TMP607[11].name = "pos";
TMP607[9].len = 2; TMP607[9].kind = 2; TMP607[9].sons = &TMP620[0];
NTI142949.node = &TMP607[9];
NTI142947.size = sizeof(Stringstreamobj142949*);
NTI142947.kind = 22;
NTI142947.base = (&NTI142949);
NTI142947.marker = TMP627;
NTI143048.size = sizeof(Filestreamobj143048);
NTI143048.kind = 17;
NTI143048.base = (&NTI142218);
NTI143048.flags = 1;
TMP607[12].kind = 1;
TMP607[12].offset = offsetof(Filestreamobj143048, f);
TMP607[12].typ = (&NTI15004);
TMP607[12].name = "f";
NTI143048.node = &TMP607[12];
NTI143046.size = sizeof(Filestreamobj143048*);
NTI143046.kind = 22;
NTI143046.base = (&NTI143048);
NTI143046.marker = TMP630;
NTI142216.size = sizeof(Streamobj142218*);
NTI142216.kind = 22;
NTI142216.base = (&NTI142218);
NTI142216.marker = TMP968;
}

